-- This file is generated by SWIG. Please do *not* modify by hand.
--
with gmp_c.a_a_gmp_randstate_struct_a_mp_algdata;
with gmp_c.mpz_t;
with Interfaces.C;

package gmp_c.a_a_gmp_randstate_struct is

   -- Item
   --

   type Item is record
      a_mp_seed    : aliased gmp_c.mpz_t.Item;
      a_mp_alg     : aliased gmp_c.gmp_randalg_t;
      a_mp_algdata : aliased gmp_c.a_a_gmp_randstate_struct_a_mp_algdata.Item;
   end record;

   -- Items
   --
   type Items is
     array
       (Interfaces.C
          .size_t range <>) of aliased gmp_c.a_a_gmp_randstate_struct.Item;

   -- Pointer
   --
   type Pointer is access all gmp_c.a_a_gmp_randstate_struct.Item;

   -- Pointers
   --
   type Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased gmp_c.a_a_gmp_randstate_struct.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all gmp_c.a_a_gmp_randstate_struct.Pointer;

   function construct return gmp_c.a_a_gmp_randstate_struct.Item;

private

   pragma Import (C, construct, "Ada_new___gmp_randstate_struct");

end gmp_c.a_a_gmp_randstate_struct;
