-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Interfaces.C.Strings;
with Interfaces.C;

package gmp_c is

   -- mp_limb_t
   --
   subtype mp_limb_t is Interfaces.C.unsigned_long;

   type mp_limb_t_array is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.mp_limb_t;

   -- mp_limb_signed_t
   --
   subtype mp_limb_signed_t is Interfaces.C.long;

   type mp_limb_signed_t_array is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.mp_limb_signed_t;

   -- mp_bitcnt_t
   --
   subtype mp_bitcnt_t is Interfaces.C.unsigned_long;

   type mp_bitcnt_t_array is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.mp_bitcnt_t;

   -- mp_size_t
   --
   subtype mp_size_t is Interfaces.C.long;

   type mp_size_t_array is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.mp_size_t;

   -- mp_exp_t
   --
   subtype mp_exp_t is Interfaces.C.long;

   type mp_exp_t_array is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.mp_exp_t;

   -- gmp_randalg_t
   --
   type gmp_randalg_t is (GMP_RAND_ALG_DEFAULT);

   for gmp_randalg_t use (GMP_RAND_ALG_DEFAULT => 0);

   pragma Convention (C, gmp_randalg_t);

   type gmp_randalg_t_array is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.gmp_randalg_t;

   -- anonymous_enum_1
   --
   type anonymous_enum_1 is
     (GMP_ERROR_NONE,
      GMP_ERROR_UNSUPPORTED_ARGUMENT,
      GMP_ERROR_DIVISION_BY_ZERO,
      GMP_ERROR_SQRT_OF_NEGATIVE,
      GMP_ERROR_INVALID_ARGUMENT);

   for anonymous_enum_1 use
     (GMP_ERROR_NONE                 => 0,
      GMP_ERROR_UNSUPPORTED_ARGUMENT => 1,
      GMP_ERROR_DIVISION_BY_ZERO     => 2,
      GMP_ERROR_SQRT_OF_NEGATIVE     => 4,
      GMP_ERROR_INVALID_ARGUMENT     => 8);

   pragma Convention (C, anonymous_enum_1);

   type anonymous_enum_1_array is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.anonymous_enum_1;

   GMP_RAND_ALG_LC : aliased constant gmp_c.gmp_randalg_t :=
     GMP_RAND_ALG_DEFAULT;
   a_a_GMP_HAVE_HOST_CPU_FAMILY_power   : constant := 0;
   a_a_GMP_HAVE_HOST_CPU_FAMILY_powerpc : constant := 0;
   GMP_LIMB_BITS                        : constant := 64;
   GMP_NAIL_BITS                        : constant := 0;
   a_a_GNU_MP_a_a                       : constant := 5;
   a_a_GMP_LIBGMP_DLL                   : constant := 0;
   a_a_GMP_MP_SIZE_T_INT                : constant := 0;
   a_a_GMP_INLINE_PROTOTYPES            : constant := 0;
   bits_per_limb                        : aliased Interfaces.C.int;
   errno                                : aliased Interfaces.C.int;
   version : aliased Interfaces.C.Strings.chars_ptr;
   a_a_GNU_MP_VERSION                   : constant := 6;
   a_a_GNU_MP_VERSION_MINOR             : constant := 1;
   a_a_GNU_MP_VERSION_PATCHLEVEL        : constant := 0;
   a_a_GNU_MP_RELEASE                   : constant := 60100;

private

   pragma Import (Cpp, bits_per_limb, "_ZN5gmp_c13bits_per_limbE");
   pragma Import (Cpp, errno, "_ZN5gmp_c5errnoE");
   pragma Import (Cpp, version, "_ZN5gmp_c7versionE");

end gmp_c;
