-- This file is generated by SWIG. Please do *not* modify by hand.
--
with gmp_c.a_a_gmp_randstate_struct;
with Interfaces.C;

package gmp_c.gmp_randstate_t is

   -- Item
   --
   type Item is
     array
     (Interfaces.C
        .size_t range
        0 ..
          0) of aliased gmp_c.a_a_gmp_randstate_struct.Item;

   -- Items
   --
   type Items is
     array
       (Interfaces.C.size_t range <>) of aliased gmp_c.gmp_randstate_t.Item;

   -- Pointer
   --
   type Pointer is access all gmp_c.gmp_randstate_t.Item;

   -- Pointers
   --
   type Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased gmp_c.gmp_randstate_t.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all gmp_c.gmp_randstate_t.Pointer;

end gmp_c.gmp_randstate_t;
