-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Interfaces.C;

package gmp_c.a_a_mpz_struct is

   -- Item
   --

   type Item is record
      a_mp_alloc : aliased Interfaces.C.int;
      a_mp_size  : aliased Interfaces.C.int;
      a_mp_d     : access gmp_c.mp_limb_t;
   end record;

   -- Items
   --
   type Items is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.a_a_mpz_struct.Item;

   -- Pointer
   --
   type Pointer is access all gmp_c.a_a_mpz_struct.Item;

   -- Pointers
   --
   type Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased gmp_c.a_a_mpz_struct.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all gmp_c.a_a_mpz_struct.Pointer;

   function construct return gmp_c.a_a_mpz_struct.Item;

private

   pragma Import (C, construct, "Ada_new___mpz_struct");

end gmp_c.a_a_mpz_struct;
