-- This file is generated by SWIG. Please do *not* modify by hand.
--
with gmp_c.a_a_mpz_struct;
with Interfaces.C;

package gmp_c.a_a_mpq_struct is

   -- Item
   --

   type Item is record
      a_mp_num : aliased gmp_c.a_a_mpz_struct.Item;
      a_mp_den : aliased gmp_c.a_a_mpz_struct.Item;
   end record;

   -- Items
   --
   type Items is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.a_a_mpq_struct.Item;

   -- Pointer
   --
   type Pointer is access all gmp_c.a_a_mpq_struct.Item;

   -- Pointers
   --
   type Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased gmp_c.a_a_mpq_struct.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all gmp_c.a_a_mpq_struct.Pointer;

   function construct return gmp_c.a_a_mpq_struct.Item;

private

   pragma Import (C, construct, "Ada_new___mpq_struct");

end gmp_c.a_a_mpq_struct;
