-- This file is generated by SWIG. Please do *not* modify by hand.
--
with gmp_c.a_a_mpf_struct;
with Interfaces.C;

package gmp_c.mpf_t is

   -- Item
   --
   type Item is
     array
     (Interfaces.C.size_t range 0 .. 0) of aliased gmp_c.a_a_mpf_struct.Item;

   -- Items
   --
   type Items is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.mpf_t.Item;

   -- Pointer
   --
   type Pointer is access all gmp_c.mpf_t.Item;

   -- Pointers
   --
   type Pointers is
     array (Interfaces.C.size_t range <>) of aliased gmp_c.mpf_t.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all gmp_c.mpf_t.Pointer;

end gmp_c.mpf_t;
