#!/bin/bash

echo
echo Removing prior build
echo

rm *.ads
rm *.adb
rm *.cxx

set -e

echo
echo Generating the binding ...
echo

swig_ada  -ada -I/usr/include  tensorflow.i 

echo
echo Pretty printing ...
echo

gnatpp  -rnb  --max-line-length=120 --vertical-named-aggregates *.ads
indent  -sob  -di16  *.c

gcc -c -I/usr/include/tensorflow *.c
rm *.o

echo Done.