-- This file is generated by SWIG. Please do *not* modify by hand.
--
with speech_tools_c.Pointers;
with interfaces.C;



package speech_tools_c.pointer_Pointers
is

   -- EST_Wave_Pointer_Pointer
   -- 
   type EST_Wave_Pointer_Pointer is access all speech_tools_c.Pointers.EST_Wave_Pointer;



   -- EST_String_Pointer_Pointer
   -- 
   type EST_String_Pointer_Pointer is access all speech_tools_c.Pointers.EST_String_Pointer;



   -- EST_Item_featfunc_Pointer_Pointer
   -- 
   type EST_Item_featfunc_Pointer_Pointer is access all speech_tools_c.Pointers.EST_Item_featfunc_Pointer;



   -- EST_Item_Pointer_Pointer
   -- 
   type EST_Item_Pointer_Pointer is access all speech_tools_c.Pointers.EST_Item_Pointer;



   -- EST_Val_Pointer_Pointer
   -- 
   type EST_Val_Pointer_Pointer is access all speech_tools_c.Pointers.EST_Val_Pointer;



   -- LISP_Pointer_Pointer
   -- 
   type LISP_Pointer_Pointer is access all speech_tools_c.Pointers.LISP_Pointer;



   -- EST_Ngrammar_Pointer_Pointer
   -- 
   type EST_Ngrammar_Pointer_Pointer is access all speech_tools_c.Pointers.EST_Ngrammar_Pointer;



   -- EST_WFST_Pointer_Pointer
   -- 
   type EST_WFST_Pointer_Pointer is access all speech_tools_c.Pointers.EST_WFST_Pointer;



   -- EST_Utterance_Pointer_Pointer
   -- 
   type EST_Utterance_Pointer_Pointer is access all speech_tools_c.Pointers.EST_Utterance_Pointer;



   -- UnitDatabase_Pointer_Pointer
   -- 
   type UnitDatabase_Pointer_Pointer is access all speech_tools_c.Pointers.UnitDatabase_Pointer;


end speech_tools_c.pointer_Pointers;
