-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.c;
with interfaces.c.strings;
with speech_tools_c.Pointers;
with swig.pointers;
with interfaces.C;



package speech_tools_c.Binding
is

   function  new_EST_Wave  return speech_tools_c.Pointers.EST_Wave_Pointer;

   function  EST_Wave_num_samples (Self : in speech_tools_c.Pointers.EST_Wave_Pointer) return interfaces.c.int;

   function  EST_Wave_num_channels (Self : in speech_tools_c.Pointers.EST_Wave_Pointer) return interfaces.c.int;

   function  EST_Wave_sample_rate (Self : in speech_tools_c.Pointers.EST_Wave_Pointer) return interfaces.c.int;

   function  EST_Wave_length (Self : in speech_tools_c.Pointers.EST_Wave_Pointer) return interfaces.c.int;

   function  EST_Wave_end (Self : in speech_tools_c.Pointers.EST_Wave_Pointer) return interfaces.c.c_float;

   function  EST_Wave_Data (Self : in speech_tools_c.Pointers.EST_Wave_Pointer) return swig.pointers.short_Pointer;

   procedure EST_Wave_resample (Self : in speech_tools_c.Pointers.EST_Wave_Pointer;
                                new_Rate : in interfaces.c.int);

   function  new_EST_String  return speech_tools_c.Pointers.EST_String_Pointer;

   function  new_EST_String (From : in interfaces.c.strings.chars_ptr) return speech_tools_c.Pointers.EST_String_Pointer;


private

   pragma Import (C, new_EST_Wave, "Ada_new_EST_Wave");
   pragma Import (C, EST_Wave_num_samples, "Ada_EST_Wave_num_samples");
   pragma Import (C, EST_Wave_num_channels, "Ada_EST_Wave_num_channels");
   pragma Import (C, EST_Wave_sample_rate, "Ada_EST_Wave_sample_rate");
   pragma Import (C, EST_Wave_length, "Ada_EST_Wave_length");
   pragma Import (C, EST_Wave_end, "Ada_EST_Wave_end");
   pragma Import (C, EST_Wave_Data, "Ada_EST_Wave_Data");
   pragma Import (C, EST_Wave_resample, "Ada_EST_Wave_resample");

   function  new_EST_String_v1  return speech_tools_c.Pointers.EST_String_Pointer;

   function  new_EST_String  return speech_tools_c.Pointers.EST_String_Pointer
     renames new_EST_String_v1;


   pragma Import (C, new_EST_String_v1, "Ada_new_EST_String__SWIG_0");

   function  new_EST_String_v2 (From : in interfaces.c.strings.chars_ptr) return speech_tools_c.Pointers.EST_String_Pointer;


   function  new_EST_String (From : in interfaces.c.strings.chars_ptr) return speech_tools_c.Pointers.EST_String_Pointer
                             renames new_EST_String_v2;

   pragma Import (C, new_EST_String_v2, "Ada_new_EST_String__SWIG_1");


end speech_tools_c.Binding;
