-- This file is generated by SWIG. Please do *not* modify by hand.
--
with swig;
with interfaces.C;


package speech_tools_c 
is

   -- EST_Wave
   -- 
   subtype EST_Wave is swig.incomplete_class;

   type EST_Wave_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_Wave;

   -- EST_String
   -- 
   subtype EST_String is swig.incomplete_class;

   type EST_String_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_String;

   -- EST_Item_featfunc
   -- 
   subtype EST_Item_featfunc is swig.incomplete_class;

   type EST_Item_featfunc_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_Item_featfunc;

   -- EST_Item
   -- 
   subtype EST_Item is swig.incomplete_class;

   type EST_Item_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_Item;

   -- EST_Val
   -- 
   subtype EST_Val is swig.incomplete_class;

   type EST_Val_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_Val;

   -- LISP
   -- 
   subtype LISP is swig.incomplete_class;

   type LISP_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.LISP;

   -- EST_Ngrammar
   -- 
   subtype EST_Ngrammar is swig.incomplete_class;

   type EST_Ngrammar_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_Ngrammar;

   -- EST_WFST
   -- 
   subtype EST_WFST is swig.incomplete_class;

   type EST_WFST_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_WFST;

   -- EST_Utterance
   -- 
   subtype EST_Utterance is swig.incomplete_class;

   type EST_Utterance_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.EST_Utterance;

   -- UnitDatabase
   -- 
   subtype UnitDatabase is swig.incomplete_class;

   type UnitDatabase_array is array (interfaces.C.Size_t range <>) of aliased speech_tools_c.UnitDatabase;


end speech_tools_c;
