### Setup the Ada project paths.
##
#

ADA_PROJECT_PATH=$CBOUND/tier-0/swig/library:$ADA_PROJECT_PATH


ADA_PROJECT_PATH=$CBOUND/tier-1/assimp/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/clib/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/fann/library:$ADA_PROJECT_PATH
#ADA_PROJECT_PATH=$CBOUND/tier-1/freetype/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/glfw/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/gmp/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/oak/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/ogg/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/portaudio/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/sdl1.2/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/speech_tools/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-1/unicap/library:$ADA_PROJECT_PATH


ADA_PROJECT_PATH=$CBOUND/tier-2/festival/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-2/glib/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-2/theora/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-2/vorbis/library:$ADA_PROJECT_PATH


ADA_PROJECT_PATH=$CBOUND/tier-3/gts/contrib/gts-0.7.6/library:$ADA_PROJECT_PATH
ADA_PROJECT_PATH=$CBOUND/tier-3/gts/library:$ADA_PROJECT_PATH


export ADA_PROJECT_PATH    
