### Setup the Ada project paths.
##
#

GPR_PROJECT_PATH=$CBOUND/tier-0/swig/library:$GPR_PROJECT_PATH

GPR_PROJECT_PATH=$CBOUND/tier-1/tensorflow/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/assimp/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/clib/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/fann/library:$GPR_PROJECT_PATH
#GPR_PROJECT_PATH=$CBOUND/tier-1/freetype/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/glfw/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/gmp/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/oak/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/ogg/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/portaudio/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/sdl1.2/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/speech_tools/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/unicap/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/gaul/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-1/xcb/library:$GPR_PROJECT_PATH


GPR_PROJECT_PATH=$CBOUND/tier-2/festival/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-2/glib/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-2/theora/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-2/vorbis/library:$GPR_PROJECT_PATH


GPR_PROJECT_PATH=$CBOUND/tier-3/gts/contrib/gts-0.7.6/library:$GPR_PROJECT_PATH
GPR_PROJECT_PATH=$CBOUND/tier-3/gts/library:$GPR_PROJECT_PATH


export GPR_PROJECT_PATH    
