-- This file is generated by SWIG. Please do *not* modify by hand.
--
with fann_c.fann_neuron;
with interfaces.C;



package fann_c.fann_layer is

   -- Item
   -- 

type Item is 
      record
         first_neuron : access fann_c.fann_neuron.Item;
         last_neuron : access fann_c.fann_neuron.Item;
      end record;



   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_layer.Item;



   -- Pointer
   -- 
   type Pointer is access all fann_c.fann_layer.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_layer.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all fann_c.fann_layer.Pointer;










end fann_c.fann_layer;
