-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.c.strings;
with interfaces.C;



package fann_c.fann_error is

   -- Item
   -- 

type Item is 
      record
         errno_f : aliased fann_c.fann_errno_enum;
         error_log : access fann_c.FILE;
         errstr : aliased interfaces.c.strings.chars_ptr;
      end record;



   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_error.Item;



   -- Pointer
   -- 
   type Pointer is access all fann_c.fann_error.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_error.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all fann_c.fann_error.Pointer;










end fann_c.fann_error;
