-- This file is generated by SWIG. Please do *not* modify by hand.
--
with fann_c.fann_callback_type;
with fann_c.fann_layer;
with fann_c.fann_neuron;
with interfaces.c;
with interfaces.c.strings;
with swig;
with interfaces.C;



package fann_c.fann is

   -- Item
   -- 

type Item is 
      record
         errno_f : aliased fann_c.fann_errno_enum;
         error_log : access fann_c.FILE;
         errstr : aliased interfaces.c.strings.chars_ptr;
         learning_rate : aliased interfaces.c.c_float;
         learning_momentum : aliased interfaces.c.c_float;
         connection_rate : aliased interfaces.c.c_float;
         network_type : aliased fann_c.fann_nettype_enum;
         first_layer : access fann_c.fann_layer.Item;
         last_layer : access fann_c.fann_layer.Item;
         total_neurons : aliased interfaces.c.unsigned;
         num_input : aliased interfaces.c.unsigned;
         num_output : aliased interfaces.c.unsigned;
         weights : access fann_c.fann_type;
         connections : access fann_c.fann_neuron.Pointer;
         train_errors : access fann_c.fann_type;
         training_algorithm : aliased fann_c.fann_train_enum;
         total_connections : aliased interfaces.c.unsigned;
         output : access fann_c.fann_type;
         num_MSE : aliased interfaces.c.unsigned;
         MSE_value : aliased interfaces.c.c_float;
         num_bit_fail : aliased interfaces.c.unsigned;
         bit_fail_limit : aliased fann_c.fann_type;
         train_error_function : aliased fann_c.fann_errorfunc_enum;
         train_stop_function : aliased fann_c.fann_stopfunc_enum;
         callback : aliased fann_c.fann_callback_type.Item;
         user_data : aliased swig.void_ptr;
         cascade_output_change_fraction : aliased interfaces.c.c_float;
         cascade_output_stagnation_epochs : aliased interfaces.c.unsigned;
         cascade_candidate_change_fraction : aliased interfaces.c.c_float;
         cascade_candidate_stagnation_epochs : aliased interfaces.c.unsigned;
         cascade_best_candidate : aliased interfaces.c.unsigned;
         cascade_candidate_limit : aliased fann_c.fann_type;
         cascade_weight_multiplier : aliased fann_c.fann_type;
         cascade_max_out_epochs : aliased interfaces.c.unsigned;
         cascade_max_cand_epochs : aliased interfaces.c.unsigned;
         cascade_min_out_epochs : aliased interfaces.c.unsigned;
         cascade_min_cand_epochs : aliased interfaces.c.unsigned;
         cascade_activation_functions : access fann_c.fann_activationfunc_enum;
         cascade_activation_functions_count : aliased interfaces.c.unsigned;
         cascade_activation_steepnesses : access fann_c.fann_type;
         cascade_activation_steepnesses_count : aliased interfaces.c.unsigned;
         cascade_num_candidate_groups : aliased interfaces.c.unsigned;
         cascade_candidate_scores : access fann_c.fann_type;
         total_neurons_allocated : aliased interfaces.c.unsigned;
         total_connections_allocated : aliased interfaces.c.unsigned;
         quickprop_decay : aliased interfaces.c.c_float;
         quickprop_mu : aliased interfaces.c.c_float;
         rprop_increase_factor : aliased interfaces.c.c_float;
         rprop_decrease_factor : aliased interfaces.c.c_float;
         rprop_delta_min : aliased interfaces.c.c_float;
         rprop_delta_max : aliased interfaces.c.c_float;
         rprop_delta_zero : aliased interfaces.c.c_float;
         sarprop_weight_decay_shift : aliased interfaces.c.c_float;
         sarprop_step_error_threshold_factor : aliased interfaces.c.c_float;
         sarprop_step_error_shift : aliased interfaces.c.c_float;
         sarprop_temperature : aliased interfaces.c.c_float;
         sarprop_epoch : aliased interfaces.c.unsigned;
         train_slopes : access fann_c.fann_type;
         prev_steps : access fann_c.fann_type;
         prev_train_slopes : access fann_c.fann_type;
         prev_weights_deltas : access fann_c.fann_type;
         scale_mean_in : access interfaces.c.c_float;
         scale_deviation_in : access interfaces.c.c_float;
         scale_new_min_in : access interfaces.c.c_float;
         scale_factor_in : access interfaces.c.c_float;
         scale_mean_out : access interfaces.c.c_float;
         scale_deviation_out : access interfaces.c.c_float;
         scale_new_min_out : access interfaces.c.c_float;
         scale_factor_out : access interfaces.c.c_float;
      end record;



   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased fann_c.fann.Item;



   -- Pointer
   -- 
   type Pointer is access all fann_c.fann.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased fann_c.fann.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all fann_c.fann.Pointer;










end fann_c.fann;
