/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#if defined(_WIN32) || defined(__CYGWIN32__)
#  define DllExport   __declspec( dllexport )
#  define SWIGSTDCALL __stdcall
#else
#  define DllExport  
#  define SWIGSTDCALL
#endif 

#ifdef __cplusplus
#  include <new>
#endif





#define protected public
#define private   public

#include <floatfann.h>
//#include <parallel_fann.h>
#include <fann.h>


  typedef void (*user_function)(unsigned int,
                                unsigned int,
                                unsigned int,
                                fann_type * ,
                                fann_type * );


  struct fann_train_data * 
  create_train_from_callback (unsigned int    num_data,
                              unsigned int    num_input,
                              unsigned int    num_output,
                              user_function   the_user_function)
  {
    return fann_create_train_from_callback (num_data, num_input, num_output,  the_user_function);
  }

#undef protected
#undef private
#ifdef __cplusplus 
extern "C" {
#endif
DllExport void SWIGSTDCALL Ada_fann_set_error_log (
  void * jarg1
  ,
  
  FILE* jarg2
  )
{
  struct fann_error *arg1 = (struct fann_error *) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  
  arg1 = (struct fann_error *)jarg1; 
  
  
  arg2 = (FILE *) jarg2;
  
  
  fann_set_error_log(arg1,arg2);
  
  
}



DllExport int SWIGSTDCALL Ada_fann_get_errno (
  void * jarg1
  )
{
  int jresult ;
  struct fann_error *arg1 = (struct fann_error *) 0 ;
  enum fann_errno_enum result;
  
  arg1 = (struct fann_error *)jarg1; 
  
  result = (enum fann_errno_enum)fann_get_errno(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_reset_errno (
  void * jarg1
  )
{
  struct fann_error *arg1 = (struct fann_error *) 0 ;
  
  arg1 = (struct fann_error *)jarg1; 
  
  fann_reset_errno(arg1);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_reset_errstr (
  void * jarg1
  )
{
  struct fann_error *arg1 = (struct fann_error *) 0 ;
  
  arg1 = (struct fann_error *)jarg1; 
  
  fann_reset_errstr(arg1);
  
  
}



DllExport char * SWIGSTDCALL Ada_fann_get_errstr (
  void * jarg1
  )
{
  char * jresult ;
  struct fann_error *arg1 = (struct fann_error *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct fann_error *)jarg1; 
  
  result = (char *)fann_get_errstr(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_print_error (
  void * jarg1
  )
{
  struct fann_error *arg1 = (struct fann_error *) 0 ;
  
  arg1 = (struct fann_error *)jarg1; 
  
  fann_print_error(arg1);
  
  
}



DllExport void * SWIGSTDCALL Ada_create_train_from_callback (
  unsigned int jarg1
  ,
  
  unsigned int jarg2
  ,
  
  unsigned int jarg3
  ,
  
  void * jarg4
  )
{
  void * jresult ;
  unsigned int arg1 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  user_function arg4 = (user_function) 0 ;
  struct fann_train_data *result = 0 ;
  
  
  arg1 = (unsigned int) jarg1; 
  
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  arg4 = (user_function)jarg4; 
  
  result = (struct fann_train_data *)create_train_from_callback(arg1,arg2,arg3,arg4);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_train (
  void * jarg1
  ,
  
  float* jarg2
  ,
  
  float* jarg3
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  fann_type *arg3 = (fann_type *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  
  arg3 = (fann_type *) jarg3;
  
  
  fann_train(arg1,arg2,arg3);
  
  
}



DllExport float* SWIGSTDCALL Ada_fann_test (
  void * jarg1
  ,
  
  float* jarg2
  ,
  
  float* jarg3
  )
{
  float* jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  fann_type *arg3 = (fann_type *) 0 ;
  fann_type *result = 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  
  arg3 = (fann_type *) jarg3;
  
  
  result = (fann_type *)fann_test(arg1,arg2,arg3);
  
  jresult = (fann_type *) result; 
  
  
  
  
  return jresult;
  
}



DllExport float SWIGSTDCALL Ada_fann_get_MSE (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_MSE(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_bit_fail (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_bit_fail(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_reset_MSE (
  void * jarg1
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  fann_reset_MSE(arg1);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_train_on_data (
  void * jarg1
  ,
  
  void * jarg2
  ,
  
  unsigned int jarg3
  ,
  
  unsigned int jarg4
  ,
  
  float jarg5
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  float arg5 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  
  arg4 = (unsigned int) jarg4; 
  
  
  
  arg5 = (float) jarg5; 
  
  
  fann_train_on_data(arg1,arg2,arg3,arg4,arg5);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_train_on_file (
  void * jarg1
  ,
  
  char * jarg2
  ,
  
  unsigned int jarg3
  ,
  
  unsigned int jarg4
  ,
  
  float jarg5
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  char *arg2 = (char *) 0 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  float arg5 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = jarg2; 
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  
  arg4 = (unsigned int) jarg4; 
  
  
  
  arg5 = (float) jarg5; 
  
  
  fann_train_on_file(arg1,(char const *)arg2,arg3,arg4,arg5);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_train_epoch (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  result = (float)fann_train_epoch(arg1,arg2);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport float SWIGSTDCALL Ada_fann_test_data (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  result = (float)fann_test_data(arg1,arg2);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_read_train_from_file (
  char * jarg1
  )
{
  void * jresult ;
  char *arg1 = (char *) 0 ;
  struct fann_train_data *result = 0 ;
  
  arg1 = jarg1; 
  
  result = (struct fann_train_data *)fann_read_train_from_file((char const *)arg1);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_train (
  unsigned int jarg1
  ,
  
  unsigned int jarg2
  ,
  
  unsigned int jarg3
  )
{
  void * jresult ;
  unsigned int arg1 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  struct fann_train_data *result = 0 ;
  
  
  arg1 = (unsigned int) jarg1; 
  
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  result = (struct fann_train_data *)fann_create_train(arg1,arg2,arg3);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_destroy_train (
  void * jarg1
  )
{
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  fann_destroy_train(arg1);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_shuffle_train_data (
  void * jarg1
  )
{
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  fann_shuffle_train_data(arg1);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_scale_train (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  fann_scale_train(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_descale_train (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  fann_descale_train(arg1,arg2);
  
  
}



DllExport int SWIGSTDCALL Ada_fann_set_input_scaling_params (
  void * jarg1
  ,
  
  void * jarg2
  ,
  
  float jarg3
  ,
  
  float jarg4
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  float arg3 ;
  float arg4 ;
  int result;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  
  arg3 = (float) jarg3; 
  
  
  
  arg4 = (float) jarg4; 
  
  
  result = (int)fann_set_input_scaling_params(arg1,(struct fann_train_data const *)arg2,arg3,arg4);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_set_output_scaling_params (
  void * jarg1
  ,
  
  void * jarg2
  ,
  
  float jarg3
  ,
  
  float jarg4
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  float arg3 ;
  float arg4 ;
  int result;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  
  arg3 = (float) jarg3; 
  
  
  
  arg4 = (float) jarg4; 
  
  
  result = (int)fann_set_output_scaling_params(arg1,(struct fann_train_data const *)arg2,arg3,arg4);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_set_scaling_params (
  void * jarg1
  ,
  
  void * jarg2
  ,
  
  float jarg3
  ,
  
  float jarg4
  ,
  
  float jarg5
  ,
  
  float jarg6
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  float arg6 ;
  int result;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  
  arg3 = (float) jarg3; 
  
  
  
  arg4 = (float) jarg4; 
  
  
  
  arg5 = (float) jarg5; 
  
  
  
  arg6 = (float) jarg6; 
  
  
  result = (int)fann_set_scaling_params(arg1,(struct fann_train_data const *)arg2,arg3,arg4,arg5,arg6);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_clear_scaling_params (
  void * jarg1
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (int)fann_clear_scaling_params(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_scale_input (
  void * jarg1
  ,
  
  float* jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  fann_scale_input(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_scale_output (
  void * jarg1
  ,
  
  float* jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  fann_scale_output(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_descale_input (
  void * jarg1
  ,
  
  float* jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  fann_descale_input(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_descale_output (
  void * jarg1
  ,
  
  float* jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  fann_descale_output(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_scale_input_train_data (
  void * jarg1
  ,
  
  float jarg2
  ,
  
  float jarg3
  )
{
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  fann_type arg2 ;
  fann_type arg3 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  
  arg3 = (fann_type) jarg3; 
  
  
  fann_scale_input_train_data(arg1,arg2,arg3);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_scale_output_train_data (
  void * jarg1
  ,
  
  float jarg2
  ,
  
  float jarg3
  )
{
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  fann_type arg2 ;
  fann_type arg3 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  
  arg3 = (fann_type) jarg3; 
  
  
  fann_scale_output_train_data(arg1,arg2,arg3);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_scale_train_data (
  void * jarg1
  ,
  
  float jarg2
  ,
  
  float jarg3
  )
{
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  fann_type arg2 ;
  fann_type arg3 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  
  arg3 = (fann_type) jarg3; 
  
  
  fann_scale_train_data(arg1,arg2,arg3);
  
  
}



DllExport void * SWIGSTDCALL Ada_fann_merge_train_data (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  void * jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  struct fann_train_data *result = 0 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  result = (struct fann_train_data *)fann_merge_train_data(arg1,arg2);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_duplicate_train_data (
  void * jarg1
  )
{
  void * jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  struct fann_train_data *result = 0 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  result = (struct fann_train_data *)fann_duplicate_train_data(arg1);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_subset_train_data (
  void * jarg1
  ,
  
  unsigned int jarg2
  ,
  
  unsigned int jarg3
  )
{
  void * jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  struct fann_train_data *result = 0 ;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  result = (struct fann_train_data *)fann_subset_train_data(arg1,arg2,arg3);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_length_train_data (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  result = (unsigned int)fann_length_train_data(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_num_input_train_data (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  result = (unsigned int)fann_num_input_train_data(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_num_output_train_data (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  result = (unsigned int)fann_num_output_train_data(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_save_train (
  void * jarg1
  ,
  
  char * jarg2
  )
{
  int jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  arg2 = jarg2; 
  
  result = (int)fann_save_train(arg1,(char const *)arg2);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_save_train_to_fixed (
  void * jarg1
  ,
  
  char * jarg2
  ,
  
  unsigned int jarg3
  )
{
  int jresult ;
  struct fann_train_data *arg1 = (struct fann_train_data *) 0 ;
  char *arg2 = (char *) 0 ;
  unsigned int arg3 ;
  int result;
  
  arg1 = (struct fann_train_data *)jarg1; 
  
  arg2 = jarg2; 
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  result = (int)fann_save_train_to_fixed(arg1,(char const *)arg2,arg3);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_get_training_algorithm (
  void * jarg1
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_train_enum result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (enum fann_train_enum)fann_get_training_algorithm(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_training_algorithm (
  void * jarg1
  ,
  
  int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_train_enum arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_train_enum) jarg2; 
  
  fann_set_training_algorithm(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_learning_rate (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_learning_rate(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_learning_rate (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_learning_rate(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_learning_momentum (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_learning_momentum(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_learning_momentum (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_learning_momentum(arg1,arg2);
  
  
}



DllExport int SWIGSTDCALL Ada_fann_get_activation_function (
  void * jarg1
  ,
  
  int jarg2
  ,
  
  int jarg3
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  int arg2 ;
  int arg3 ;
  enum fann_activationfunc_enum result;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (int) jarg2; 
  
  
  
  arg3 = (int) jarg3; 
  
  
  result = (enum fann_activationfunc_enum)fann_get_activation_function(arg1,arg2,arg3);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_function (
  void * jarg1
  ,
  
  int jarg2
  ,
  
  int jarg3
  ,
  
  int jarg4
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_activationfunc_enum arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_activationfunc_enum) jarg2; 
  
  
  arg3 = (int) jarg3; 
  
  
  
  arg4 = (int) jarg4; 
  
  
  fann_set_activation_function(arg1,arg2,arg3,arg4);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_function_layer (
  void * jarg1
  ,
  
  int jarg2
  ,
  
  int jarg3
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_activationfunc_enum arg2 ;
  int arg3 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_activationfunc_enum) jarg2; 
  
  
  arg3 = (int) jarg3; 
  
  
  fann_set_activation_function_layer(arg1,arg2,arg3);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_function_hidden (
  void * jarg1
  ,
  
  int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_activationfunc_enum arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_activationfunc_enum) jarg2; 
  
  fann_set_activation_function_hidden(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_function_output (
  void * jarg1
  ,
  
  int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_activationfunc_enum arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_activationfunc_enum) jarg2; 
  
  fann_set_activation_function_output(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_activation_steepness (
  void * jarg1
  ,
  
  int jarg2
  ,
  
  int jarg3
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  int arg2 ;
  int arg3 ;
  fann_type result;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (int) jarg2; 
  
  
  
  arg3 = (int) jarg3; 
  
  
  result = (fann_type)fann_get_activation_steepness(arg1,arg2,arg3);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_steepness (
  void * jarg1
  ,
  
  float jarg2
  ,
  
  int jarg3
  ,
  
  int jarg4
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  
  arg3 = (int) jarg3; 
  
  
  
  arg4 = (int) jarg4; 
  
  
  fann_set_activation_steepness(arg1,arg2,arg3,arg4);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_steepness_layer (
  void * jarg1
  ,
  
  float jarg2
  ,
  
  int jarg3
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  int arg3 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  
  arg3 = (int) jarg3; 
  
  
  fann_set_activation_steepness_layer(arg1,arg2,arg3);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_steepness_hidden (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  fann_set_activation_steepness_hidden(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_activation_steepness_output (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  fann_set_activation_steepness_output(arg1,arg2);
  
  
}



DllExport int SWIGSTDCALL Ada_fann_get_train_error_function (
  void * jarg1
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_errorfunc_enum result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (enum fann_errorfunc_enum)fann_get_train_error_function(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_train_error_function (
  void * jarg1
  ,
  
  int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_errorfunc_enum arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_errorfunc_enum) jarg2; 
  
  fann_set_train_error_function(arg1,arg2);
  
  
}



DllExport int SWIGSTDCALL Ada_fann_get_train_stop_function (
  void * jarg1
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_stopfunc_enum result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (enum fann_stopfunc_enum)fann_get_train_stop_function(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_train_stop_function (
  void * jarg1
  ,
  
  int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_stopfunc_enum arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_stopfunc_enum) jarg2; 
  
  fann_set_train_stop_function(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_bit_fail_limit (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (fann_type)fann_get_bit_fail_limit(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_bit_fail_limit (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  fann_set_bit_fail_limit(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_callback (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_callback_type arg2 = (fann_callback_type) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (fann_callback_type)jarg2; 
  
  fann_set_callback(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_quickprop_decay (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_quickprop_decay(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_quickprop_decay (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_quickprop_decay(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_quickprop_mu (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_quickprop_mu(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_quickprop_mu (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_quickprop_mu(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_rprop_increase_factor (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_rprop_increase_factor(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_rprop_increase_factor (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_rprop_increase_factor(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_rprop_decrease_factor (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_rprop_decrease_factor(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_rprop_decrease_factor (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_rprop_decrease_factor(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_rprop_delta_min (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_rprop_delta_min(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_rprop_delta_min (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_rprop_delta_min(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_rprop_delta_max (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_rprop_delta_max(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_rprop_delta_max (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_rprop_delta_max(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_rprop_delta_zero (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_rprop_delta_zero(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_rprop_delta_zero (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_rprop_delta_zero(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_sarprop_weight_decay_shift (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_sarprop_weight_decay_shift(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_sarprop_weight_decay_shift (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_sarprop_weight_decay_shift(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_sarprop_step_error_threshold_factor (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_sarprop_step_error_threshold_factor(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_sarprop_step_error_threshold_factor (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_sarprop_step_error_threshold_factor(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_sarprop_step_error_shift (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_sarprop_step_error_shift(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_sarprop_step_error_shift (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_sarprop_step_error_shift(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_sarprop_temperature (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_sarprop_temperature(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_sarprop_temperature (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_sarprop_temperature(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_cascadetrain_on_data (
  void * jarg1
  ,
  
  void * jarg2
  ,
  
  unsigned int jarg3
  ,
  
  unsigned int jarg4
  ,
  
  float jarg5
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  float arg5 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  
  arg4 = (unsigned int) jarg4; 
  
  
  
  arg5 = (float) jarg5; 
  
  
  fann_cascadetrain_on_data(arg1,arg2,arg3,arg4,arg5);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_cascadetrain_on_file (
  void * jarg1
  ,
  
  char * jarg2
  ,
  
  unsigned int jarg3
  ,
  
  unsigned int jarg4
  ,
  
  float jarg5
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  char *arg2 = (char *) 0 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  float arg5 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = jarg2; 
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  
  arg4 = (unsigned int) jarg4; 
  
  
  
  arg5 = (float) jarg5; 
  
  
  fann_cascadetrain_on_file(arg1,(char const *)arg2,arg3,arg4,arg5);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_cascade_output_change_fraction (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_cascade_output_change_fraction(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_output_change_fraction (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_cascade_output_change_fraction(arg1,arg2);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_output_stagnation_epochs (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_output_stagnation_epochs(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_output_stagnation_epochs (
  void * jarg1
  ,
  
  unsigned int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  fann_set_cascade_output_stagnation_epochs(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_cascade_candidate_change_fraction (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_cascade_candidate_change_fraction(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_candidate_change_fraction (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  float arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (float) jarg2; 
  
  
  fann_set_cascade_candidate_change_fraction(arg1,arg2);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_candidate_stagnation_epochs (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_candidate_stagnation_epochs(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_candidate_stagnation_epochs (
  void * jarg1
  ,
  
  unsigned int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  fann_set_cascade_candidate_stagnation_epochs(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_cascade_weight_multiplier (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (fann_type)fann_get_cascade_weight_multiplier(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_weight_multiplier (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  fann_set_cascade_weight_multiplier(arg1,arg2);
  
  
}



DllExport float SWIGSTDCALL Ada_fann_get_cascade_candidate_limit (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (fann_type)fann_get_cascade_candidate_limit(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_candidate_limit (
  void * jarg1
  ,
  
  float jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  fann_set_cascade_candidate_limit(arg1,arg2);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_max_out_epochs (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_max_out_epochs(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_max_out_epochs (
  void * jarg1
  ,
  
  unsigned int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  fann_set_cascade_max_out_epochs(arg1,arg2);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_min_out_epochs (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_min_out_epochs(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_min_out_epochs (
  void * jarg1
  ,
  
  unsigned int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  fann_set_cascade_min_out_epochs(arg1,arg2);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_max_cand_epochs (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_max_cand_epochs(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_max_cand_epochs (
  void * jarg1
  ,
  
  unsigned int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  fann_set_cascade_max_cand_epochs(arg1,arg2);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_min_cand_epochs (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_min_cand_epochs(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_min_cand_epochs (
  void * jarg1
  ,
  
  unsigned int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  fann_set_cascade_min_cand_epochs(arg1,arg2);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_num_candidates (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_num_candidates(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_activation_functions_count (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_activation_functions_count(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_get_cascade_activation_functions (
  void * jarg1
  )
{
  void * jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_activationfunc_enum *result = 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (enum fann_activationfunc_enum *)fann_get_cascade_activation_functions(arg1);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_activation_functions (
  void * jarg1
  ,
  
  void * jarg2
  ,
  
  unsigned int jarg3
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_activationfunc_enum *arg2 = (enum fann_activationfunc_enum *) 0 ;
  unsigned int arg3 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (enum fann_activationfunc_enum *)jarg2; 
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  fann_set_cascade_activation_functions(arg1,arg2,arg3);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_activation_steepnesses_count (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_activation_steepnesses_count(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport float* SWIGSTDCALL Ada_fann_get_cascade_activation_steepnesses (
  void * jarg1
  )
{
  float* jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *result = 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (fann_type *)fann_get_cascade_activation_steepnesses(arg1);
  
  jresult = (fann_type *) result; 
  
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_activation_steepnesses (
  void * jarg1
  ,
  
  float* jarg2
  ,
  
  unsigned int jarg3
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  unsigned int arg3 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  fann_set_cascade_activation_steepnesses(arg1,arg2,arg3);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_cascade_num_candidate_groups (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_cascade_num_candidate_groups(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_set_cascade_num_candidate_groups (
  void * jarg1
  ,
  
  unsigned int jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  fann_set_cascade_num_candidate_groups(arg1,arg2);
  
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_from_file (
  char * jarg1
  )
{
  void * jresult ;
  char *arg1 = (char *) 0 ;
  struct fann *result = 0 ;
  
  arg1 = jarg1; 
  
  result = (struct fann *)fann_create_from_file((char const *)arg1);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_save (
  void * jarg1
  ,
  
  char * jarg2
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = jarg2; 
  
  result = (int)fann_save(arg1,(char const *)arg2);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_save_to_fixed (
  void * jarg1
  ,
  
  char * jarg2
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = jarg2; 
  
  result = (int)fann_save_to_fixed(arg1,(char const *)arg2);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_standard (
  unsigned int jarg1
  )
{
  void * jresult ;
  unsigned int arg1 ;
  void *arg2 = 0 ;
  struct fann *result = 0 ;
  
  
  arg1 = (unsigned int) jarg1; 
  
  
  result = (struct fann *)fann_create_standard(arg1,arg2);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_standard_array (
  unsigned int jarg1
  ,
  
  unsigned int* jarg2
  )
{
  void * jresult ;
  unsigned int arg1 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  struct fann *result = 0 ;
  
  
  arg1 = (unsigned int) jarg1; 
  
  
  
  arg2 = (unsigned int *) jarg2;
  
  
  result = (struct fann *)fann_create_standard_array(arg1,(unsigned int const *)arg2);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_sparse (
  float jarg1
  ,
  
  unsigned int jarg2
  )
{
  void * jresult ;
  float arg1 ;
  unsigned int arg2 ;
  void *arg3 = 0 ;
  struct fann *result = 0 ;
  
  
  arg1 = (float) jarg1; 
  
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  result = (struct fann *)fann_create_sparse(arg1,arg2,arg3);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_sparse_array (
  float jarg1
  ,
  
  unsigned int jarg2
  ,
  
  unsigned int* jarg3
  )
{
  void * jresult ;
  float arg1 ;
  unsigned int arg2 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  struct fann *result = 0 ;
  
  
  arg1 = (float) jarg1; 
  
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  
  arg3 = (unsigned int *) jarg3;
  
  
  result = (struct fann *)fann_create_sparse_array(arg1,arg2,(unsigned int const *)arg3);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_shortcut (
  unsigned int jarg1
  )
{
  void * jresult ;
  unsigned int arg1 ;
  void *arg2 = 0 ;
  struct fann *result = 0 ;
  
  
  arg1 = (unsigned int) jarg1; 
  
  
  result = (struct fann *)fann_create_shortcut(arg1,arg2);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void * SWIGSTDCALL Ada_fann_create_shortcut_array (
  unsigned int jarg1
  ,
  
  unsigned int* jarg2
  )
{
  void * jresult ;
  unsigned int arg1 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  struct fann *result = 0 ;
  
  
  arg1 = (unsigned int) jarg1; 
  
  
  
  arg2 = (unsigned int *) jarg2;
  
  
  result = (struct fann *)fann_create_shortcut_array(arg1,(unsigned int const *)arg2);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_destroy (
  void * jarg1
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  fann_destroy(arg1);
  
  
}



DllExport void * SWIGSTDCALL Ada_fann_copy (
  void * jarg1
  )
{
  void * jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann *result = 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (struct fann *)fann_copy(arg1);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



DllExport float* SWIGSTDCALL Ada_fann_run (
  void * jarg1
  ,
  
  float* jarg2
  )
{
  float* jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type *arg2 = (fann_type *) 0 ;
  fann_type *result = 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type *) jarg2;
  
  
  result = (fann_type *)fann_run(arg1,arg2);
  
  jresult = (fann_type *) result; 
  
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_randomize_weights (
  void * jarg1
  ,
  
  float jarg2
  ,
  
  float jarg3
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  fann_type arg2 ;
  fann_type arg3 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (fann_type) jarg2; 
  
  
  
  arg3 = (fann_type) jarg3; 
  
  
  fann_randomize_weights(arg1,arg2,arg3);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_init_weights (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_train_data *arg2 = (struct fann_train_data *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_train_data *)jarg2; 
  
  fann_init_weights(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_print_connections (
  void * jarg1
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  fann_print_connections(arg1);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_print_parameters (
  void * jarg1
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  fann_print_parameters(arg1);
  
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_num_input (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_num_input(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_num_output (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_num_output(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_total_neurons (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_total_neurons(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_total_connections (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_total_connections(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport int SWIGSTDCALL Ada_fann_get_network_type (
  void * jarg1
  )
{
  int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  enum fann_nettype_enum result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (enum fann_nettype_enum)fann_get_network_type(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport float SWIGSTDCALL Ada_fann_get_connection_rate (
  void * jarg1
  )
{
  float jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  float result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (float)fann_get_connection_rate(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport unsigned int SWIGSTDCALL Ada_fann_get_num_layers (
  void * jarg1
  )
{
  unsigned int jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int result;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (unsigned int)fann_get_num_layers(arg1);
  jresult = result; 
  
  
  
  return jresult;
  
}



DllExport void SWIGSTDCALL Ada_fann_get_layer_array (
  void * jarg1
  ,
  
  unsigned int* jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int *) jarg2;
  
  
  fann_get_layer_array(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_get_bias_array (
  void * jarg1
  ,
  
  unsigned int* jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int *) jarg2;
  
  
  fann_get_bias_array(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_get_connection_array (
  void * jarg1
  ,
  
  void * jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_connection *arg2 = (struct fann_connection *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_connection *)jarg2; 
  
  fann_get_connection_array(arg1,arg2);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_weight_array (
  void * jarg1
  ,
  
  void * jarg2
  ,
  
  unsigned int jarg3
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  struct fann_connection *arg2 = (struct fann_connection *) 0 ;
  unsigned int arg3 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (struct fann_connection *)jarg2; 
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  fann_set_weight_array(arg1,arg2,arg3);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_weight (
  void * jarg1
  ,
  
  unsigned int jarg2
  ,
  
  unsigned int jarg3
  ,
  
  float jarg4
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  fann_type arg4 ;
  
  arg1 = (struct fann *)jarg1; 
  
  
  arg2 = (unsigned int) jarg2; 
  
  
  
  arg3 = (unsigned int) jarg3; 
  
  
  
  arg4 = (fann_type) jarg4; 
  
  
  fann_set_weight(arg1,arg2,arg3,arg4);
  
  
}



DllExport void SWIGSTDCALL Ada_fann_set_user_data (
  void * jarg1
  ,
  
  void* jarg2
  )
{
  struct fann *arg1 = (struct fann *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  arg2 = (void *)jarg2; 
  
  fann_set_user_data(arg1,arg2);
  
  
}



DllExport void* SWIGSTDCALL Ada_fann_get_user_data (
  void * jarg1
  )
{
  void* jresult ;
  struct fann *arg1 = (struct fann *) 0 ;
  void *result = 0 ;
  
  arg1 = (struct fann *)jarg1; 
  
  result = (void *)fann_get_user_data(arg1);
  jresult = (void *) result;      
  
  
  
  return jresult;
  
}



#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif

