-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.c;
with interfaces.C;



package fann_c.fann_neuron is

   -- Item
   -- 

type Item is 
      record
         first_con : aliased interfaces.c.unsigned;
         last_con : aliased interfaces.c.unsigned;
         sum : aliased fann_c.fann_type;
         value : aliased fann_c.fann_type;
         activation_steepness : aliased fann_c.fann_type;
         activation_function : aliased fann_c.fann_activationfunc_enum;
      end record;



   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_neuron.Item;



   -- Pointer
   -- 
   type Pointer is access all fann_c.fann_neuron.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_neuron.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all fann_c.fann_neuron.Pointer;










end fann_c.fann_neuron;
