-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.c;
with interfaces.C;



package fann_c.fann_connection is

   -- Item
   -- 

type Item is 
      record
         from_neuron : aliased interfaces.c.unsigned;
         to_neuron : aliased interfaces.c.unsigned;
         weight : aliased fann_c.fann_type;
      end record;



   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_connection.Item;



   -- Pointer
   -- 
   type Pointer is access all fann_c.fann_connection.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased fann_c.fann_connection.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all fann_c.fann_connection.Pointer;










end fann_c.fann_connection;
