-- This file is generated by SWIG. Please do *not* modify by hand.
--
with fann_c.Pointers;
with interfaces.c;
with interfaces.C;



package fann_c.user_function is

   -- Item
   -- 
   type Item is access 

   procedure  (arg_5_1 : in interfaces.c.unsigned;
arg_5_2 : in interfaces.c.unsigned;
arg_5_3 : in interfaces.c.unsigned;
arg_5_4 : in fann_c.Pointers.fann_type_Pointer;
arg_5_5 : in fann_c.Pointers.fann_type_Pointer);
pragma convention (C, Item);

   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased fann_c.user_function.Item;



   -- Pointer
   -- 
   type Pointer is access all fann_c.user_function.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased fann_c.user_function.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all fann_c.user_function.Pointer;










end fann_c.user_function;
