-- This file is generated by SWIG. Please do *not* modify by hand.
--
with fann_c.Pointers;
with fann_c.fann;
with fann_c.fann_callback_type;
with fann_c.fann_connection;
with fann_c.fann_error;
with fann_c.fann_train_data;
with fann_c.user_function;
with interfaces.c;
with interfaces.c.strings;
with swig;
with swig.pointers;
with interfaces.C;



package fann_c.Binding is






   procedure fann_set_error_log (errdat : in fann_c.fann_error.Pointer;
log_file : in fann_c.Pointers.FILE_Pointer);

   function  fann_get_errno (errdat : in fann_c.fann_error.Pointer) return fann_c.fann_errno_enum;

   procedure fann_reset_errno (errdat : in fann_c.fann_error.Pointer);

   procedure fann_reset_errstr (errdat : in fann_c.fann_error.Pointer);

   function  fann_get_errstr (errdat : in fann_c.fann_error.Pointer) return interfaces.c.strings.chars_ptr;

   procedure fann_print_error (errdat : in fann_c.fann_error.Pointer);

   function  create_train_from_callback (num_data : in interfaces.c.unsigned;
num_input : in interfaces.c.unsigned;
num_output : in interfaces.c.unsigned;
the_user_function : in fann_c.user_function.Item) return fann_c.fann_train_data.Pointer;

   procedure fann_train (ann : in fann_c.fann.Pointer;
input : in fann_c.Pointers.fann_type_Pointer;
desired_output : in fann_c.Pointers.fann_type_Pointer);

   function  fann_test (ann : in fann_c.fann.Pointer;
input : in fann_c.Pointers.fann_type_Pointer;
desired_output : in fann_c.Pointers.fann_type_Pointer) return fann_c.Pointers.fann_type_Pointer;

   function  fann_get_MSE (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   function  fann_get_bit_fail (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_reset_MSE (ann : in fann_c.fann.Pointer);

   procedure fann_train_on_data (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer;
max_epochs : in interfaces.c.unsigned;
epochs_between_reports : in interfaces.c.unsigned;
desired_error : in interfaces.c.c_float);

   procedure fann_train_on_file (ann : in fann_c.fann.Pointer;
filename : in interfaces.c.strings.chars_ptr;
max_epochs : in interfaces.c.unsigned;
epochs_between_reports : in interfaces.c.unsigned;
desired_error : in interfaces.c.c_float);

   function  fann_train_epoch (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer) return interfaces.c.c_float;

   function  fann_test_data (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer) return interfaces.c.c_float;

   function  fann_read_train_from_file (filename : in interfaces.c.strings.chars_ptr) return fann_c.fann_train_data.Pointer;

   function  fann_create_train (num_data : in interfaces.c.unsigned;
num_input : in interfaces.c.unsigned;
num_output : in interfaces.c.unsigned) return fann_c.fann_train_data.Pointer;

   procedure fann_destroy_train (train_data : in fann_c.fann_train_data.Pointer);

   procedure fann_shuffle_train_data (train_data : in fann_c.fann_train_data.Pointer);

   procedure fann_scale_train (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer);

   procedure fann_descale_train (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer);

   function  fann_set_input_scaling_params (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer;
new_input_min : in interfaces.c.c_float;
new_input_max : in interfaces.c.c_float) return interfaces.c.int;

   function  fann_set_output_scaling_params (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer;
new_output_min : in interfaces.c.c_float;
new_output_max : in interfaces.c.c_float) return interfaces.c.int;

   function  fann_set_scaling_params (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer;
new_input_min : in interfaces.c.c_float;
new_input_max : in interfaces.c.c_float;
new_output_min : in interfaces.c.c_float;
new_output_max : in interfaces.c.c_float) return interfaces.c.int;

   function  fann_clear_scaling_params (ann : in fann_c.fann.Pointer) return interfaces.c.int;

   procedure fann_scale_input (ann : in fann_c.fann.Pointer;
input_vector : in fann_c.Pointers.fann_type_Pointer);

   procedure fann_scale_output (ann : in fann_c.fann.Pointer;
output_vector : in fann_c.Pointers.fann_type_Pointer);

   procedure fann_descale_input (ann : in fann_c.fann.Pointer;
input_vector : in fann_c.Pointers.fann_type_Pointer);

   procedure fann_descale_output (ann : in fann_c.fann.Pointer;
output_vector : in fann_c.Pointers.fann_type_Pointer);

   procedure fann_scale_input_train_data (train_data : in fann_c.fann_train_data.Pointer;
new_min : in fann_c.fann_type;
new_max : in fann_c.fann_type);

   procedure fann_scale_output_train_data (train_data : in fann_c.fann_train_data.Pointer;
new_min : in fann_c.fann_type;
new_max : in fann_c.fann_type);

   procedure fann_scale_train_data (train_data : in fann_c.fann_train_data.Pointer;
new_min : in fann_c.fann_type;
new_max : in fann_c.fann_type);

   function  fann_merge_train_data (data1 : in fann_c.fann_train_data.Pointer;
data2 : in fann_c.fann_train_data.Pointer) return fann_c.fann_train_data.Pointer;

   function  fann_duplicate_train_data (data : in fann_c.fann_train_data.Pointer) return fann_c.fann_train_data.Pointer;

   function  fann_subset_train_data (data : in fann_c.fann_train_data.Pointer;
pos : in interfaces.c.unsigned;
length : in interfaces.c.unsigned) return fann_c.fann_train_data.Pointer;

   function  fann_length_train_data (data : in fann_c.fann_train_data.Pointer) return interfaces.c.unsigned;

   function  fann_num_input_train_data (data : in fann_c.fann_train_data.Pointer) return interfaces.c.unsigned;

   function  fann_num_output_train_data (data : in fann_c.fann_train_data.Pointer) return interfaces.c.unsigned;

   function  fann_save_train (data : in fann_c.fann_train_data.Pointer;
filename : in interfaces.c.strings.chars_ptr) return interfaces.c.int;

   function  fann_save_train_to_fixed (data : in fann_c.fann_train_data.Pointer;
filename : in interfaces.c.strings.chars_ptr;
decimal_point : in interfaces.c.unsigned) return interfaces.c.int;

   function  fann_get_training_algorithm (ann : in fann_c.fann.Pointer) return fann_c.fann_train_enum;

   procedure fann_set_training_algorithm (ann : in fann_c.fann.Pointer;
training_algorithm : in fann_c.fann_train_enum);

   function  fann_get_learning_rate (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_learning_rate (ann : in fann_c.fann.Pointer;
learning_rate : in interfaces.c.c_float);

   function  fann_get_learning_momentum (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_learning_momentum (ann : in fann_c.fann.Pointer;
learning_momentum : in interfaces.c.c_float);

   function  fann_get_activation_function (ann : in fann_c.fann.Pointer;
layer : in interfaces.c.int;
neuron : in interfaces.c.int) return fann_c.fann_activationfunc_enum;

   procedure fann_set_activation_function (ann : in fann_c.fann.Pointer;
activation_function : in fann_c.fann_activationfunc_enum;
layer : in interfaces.c.int;
neuron : in interfaces.c.int);

   procedure fann_set_activation_function_layer (ann : in fann_c.fann.Pointer;
activation_function : in fann_c.fann_activationfunc_enum;
layer : in interfaces.c.int);

   procedure fann_set_activation_function_hidden (ann : in fann_c.fann.Pointer;
activation_function : in fann_c.fann_activationfunc_enum);

   procedure fann_set_activation_function_output (ann : in fann_c.fann.Pointer;
activation_function : in fann_c.fann_activationfunc_enum);

   function  fann_get_activation_steepness (ann : in fann_c.fann.Pointer;
layer : in interfaces.c.int;
neuron : in interfaces.c.int) return fann_c.fann_type;

   procedure fann_set_activation_steepness (ann : in fann_c.fann.Pointer;
steepness : in fann_c.fann_type;
layer : in interfaces.c.int;
neuron : in interfaces.c.int);

   procedure fann_set_activation_steepness_layer (ann : in fann_c.fann.Pointer;
steepness : in fann_c.fann_type;
layer : in interfaces.c.int);

   procedure fann_set_activation_steepness_hidden (ann : in fann_c.fann.Pointer;
steepness : in fann_c.fann_type);

   procedure fann_set_activation_steepness_output (ann : in fann_c.fann.Pointer;
steepness : in fann_c.fann_type);

   function  fann_get_train_error_function (ann : in fann_c.fann.Pointer) return fann_c.fann_errorfunc_enum;

   procedure fann_set_train_error_function (ann : in fann_c.fann.Pointer;
train_error_function : in fann_c.fann_errorfunc_enum);

   function  fann_get_train_stop_function (ann : in fann_c.fann.Pointer) return fann_c.fann_stopfunc_enum;

   procedure fann_set_train_stop_function (ann : in fann_c.fann.Pointer;
train_stop_function : in fann_c.fann_stopfunc_enum);

   function  fann_get_bit_fail_limit (ann : in fann_c.fann.Pointer) return fann_c.fann_type;

   procedure fann_set_bit_fail_limit (ann : in fann_c.fann.Pointer;
bit_fail_limit : in fann_c.fann_type);

   procedure fann_set_callback (ann : in fann_c.fann.Pointer;
callback : in fann_c.fann_callback_type.Item);

   function  fann_get_quickprop_decay (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_quickprop_decay (ann : in fann_c.fann.Pointer;
quickprop_decay : in interfaces.c.c_float);

   function  fann_get_quickprop_mu (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_quickprop_mu (ann : in fann_c.fann.Pointer;
quickprop_mu : in interfaces.c.c_float);

   function  fann_get_rprop_increase_factor (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_rprop_increase_factor (ann : in fann_c.fann.Pointer;
rprop_increase_factor : in interfaces.c.c_float);

   function  fann_get_rprop_decrease_factor (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_rprop_decrease_factor (ann : in fann_c.fann.Pointer;
rprop_decrease_factor : in interfaces.c.c_float);

   function  fann_get_rprop_delta_min (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_rprop_delta_min (ann : in fann_c.fann.Pointer;
rprop_delta_min : in interfaces.c.c_float);

   function  fann_get_rprop_delta_max (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_rprop_delta_max (ann : in fann_c.fann.Pointer;
rprop_delta_max : in interfaces.c.c_float);

   function  fann_get_rprop_delta_zero (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_rprop_delta_zero (ann : in fann_c.fann.Pointer;
rprop_delta_max : in interfaces.c.c_float);

   function  fann_get_sarprop_weight_decay_shift (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_sarprop_weight_decay_shift (ann : in fann_c.fann.Pointer;
sarprop_weight_decay_shift : in interfaces.c.c_float);

   function  fann_get_sarprop_step_error_threshold_factor (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_sarprop_step_error_threshold_factor (ann : in fann_c.fann.Pointer;
sarprop_step_error_threshold_factor : in interfaces.c.c_float);

   function  fann_get_sarprop_step_error_shift (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_sarprop_step_error_shift (ann : in fann_c.fann.Pointer;
sarprop_step_error_shift : in interfaces.c.c_float);

   function  fann_get_sarprop_temperature (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_sarprop_temperature (ann : in fann_c.fann.Pointer;
sarprop_temperature : in interfaces.c.c_float);

   procedure fann_cascadetrain_on_data (ann : in fann_c.fann.Pointer;
data : in fann_c.fann_train_data.Pointer;
max_neurons : in interfaces.c.unsigned;
neurons_between_reports : in interfaces.c.unsigned;
desired_error : in interfaces.c.c_float);

   procedure fann_cascadetrain_on_file (ann : in fann_c.fann.Pointer;
filename : in interfaces.c.strings.chars_ptr;
max_neurons : in interfaces.c.unsigned;
neurons_between_reports : in interfaces.c.unsigned;
desired_error : in interfaces.c.c_float);

   function  fann_get_cascade_output_change_fraction (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_cascade_output_change_fraction (ann : in fann_c.fann.Pointer;
cascade_output_change_fraction : in interfaces.c.c_float);

   function  fann_get_cascade_output_stagnation_epochs (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_set_cascade_output_stagnation_epochs (ann : in fann_c.fann.Pointer;
cascade_output_stagnation_epochs : in interfaces.c.unsigned);

   function  fann_get_cascade_candidate_change_fraction (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   procedure fann_set_cascade_candidate_change_fraction (ann : in fann_c.fann.Pointer;
cascade_candidate_change_fraction : in interfaces.c.c_float);

   function  fann_get_cascade_candidate_stagnation_epochs (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_set_cascade_candidate_stagnation_epochs (ann : in fann_c.fann.Pointer;
cascade_candidate_stagnation_epochs : in interfaces.c.unsigned);

   function  fann_get_cascade_weight_multiplier (ann : in fann_c.fann.Pointer) return fann_c.fann_type;

   procedure fann_set_cascade_weight_multiplier (ann : in fann_c.fann.Pointer;
cascade_weight_multiplier : in fann_c.fann_type);

   function  fann_get_cascade_candidate_limit (ann : in fann_c.fann.Pointer) return fann_c.fann_type;

   procedure fann_set_cascade_candidate_limit (ann : in fann_c.fann.Pointer;
cascade_candidate_limit : in fann_c.fann_type);

   function  fann_get_cascade_max_out_epochs (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_set_cascade_max_out_epochs (ann : in fann_c.fann.Pointer;
cascade_max_out_epochs : in interfaces.c.unsigned);

   function  fann_get_cascade_min_out_epochs (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_set_cascade_min_out_epochs (ann : in fann_c.fann.Pointer;
cascade_min_out_epochs : in interfaces.c.unsigned);

   function  fann_get_cascade_max_cand_epochs (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_set_cascade_max_cand_epochs (ann : in fann_c.fann.Pointer;
cascade_max_cand_epochs : in interfaces.c.unsigned);

   function  fann_get_cascade_min_cand_epochs (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_set_cascade_min_cand_epochs (ann : in fann_c.fann.Pointer;
cascade_min_cand_epochs : in interfaces.c.unsigned);

   function  fann_get_cascade_num_candidates (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   function  fann_get_cascade_activation_functions_count (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   function  fann_get_cascade_activation_functions (ann : in fann_c.fann.Pointer) return fann_c.Pointers.fann_activationfunc_enum_Pointer;

   procedure fann_set_cascade_activation_functions (ann : in fann_c.fann.Pointer;
cascade_activation_functions : in fann_c.Pointers.fann_activationfunc_enum_Pointer;
cascade_activation_functions_count : in interfaces.c.unsigned);

   function  fann_get_cascade_activation_steepnesses_count (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   function  fann_get_cascade_activation_steepnesses (ann : in fann_c.fann.Pointer) return fann_c.Pointers.fann_type_Pointer;

   procedure fann_set_cascade_activation_steepnesses (ann : in fann_c.fann.Pointer;
cascade_activation_steepnesses : in fann_c.Pointers.fann_type_Pointer;
cascade_activation_steepnesses_count : in interfaces.c.unsigned);

   function  fann_get_cascade_num_candidate_groups (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_set_cascade_num_candidate_groups (ann : in fann_c.fann.Pointer;
cascade_num_candidate_groups : in interfaces.c.unsigned);

   function  fann_create_from_file (configuration_file : in interfaces.c.strings.chars_ptr) return fann_c.fann.Pointer;

   function  fann_save (ann : in fann_c.fann.Pointer;
configuration_file : in interfaces.c.strings.chars_ptr) return interfaces.c.int;

   function  fann_save_to_fixed (ann : in fann_c.fann.Pointer;
configuration_file : in interfaces.c.strings.chars_ptr) return interfaces.c.int;

   function  fann_create_standard (num_layers : in interfaces.c.unsigned) return fann_c.fann.Pointer;

   function  fann_create_standard_array (num_layers : in interfaces.c.unsigned;
layers : in swig.pointers.unsigned_Pointer) return fann_c.fann.Pointer;

   function  fann_create_sparse (connection_rate : in interfaces.c.c_float;
num_layers : in interfaces.c.unsigned) return fann_c.fann.Pointer;

   function  fann_create_sparse_array (connection_rate : in interfaces.c.c_float;
num_layers : in interfaces.c.unsigned;
layers : in swig.pointers.unsigned_Pointer) return fann_c.fann.Pointer;

   function  fann_create_shortcut (num_layers : in interfaces.c.unsigned) return fann_c.fann.Pointer;

   function  fann_create_shortcut_array (num_layers : in interfaces.c.unsigned;
layers : in swig.pointers.unsigned_Pointer) return fann_c.fann.Pointer;

   procedure fann_destroy (ann : in fann_c.fann.Pointer);

   function  fann_copy (ann : in fann_c.fann.Pointer) return fann_c.fann.Pointer;

   function  fann_run (ann : in fann_c.fann.Pointer;
input : in fann_c.Pointers.fann_type_Pointer) return fann_c.Pointers.fann_type_Pointer;

   procedure fann_randomize_weights (ann : in fann_c.fann.Pointer;
min_weight : in fann_c.fann_type;
max_weight : in fann_c.fann_type);

   procedure fann_init_weights (ann : in fann_c.fann.Pointer;
train_data : in fann_c.fann_train_data.Pointer);

   procedure fann_print_connections (ann : in fann_c.fann.Pointer);

   procedure fann_print_parameters (ann : in fann_c.fann.Pointer);

   function  fann_get_num_input (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   function  fann_get_num_output (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   function  fann_get_total_neurons (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   function  fann_get_total_connections (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   function  fann_get_network_type (ann : in fann_c.fann.Pointer) return fann_c.fann_nettype_enum;

   function  fann_get_connection_rate (ann : in fann_c.fann.Pointer) return interfaces.c.c_float;

   function  fann_get_num_layers (ann : in fann_c.fann.Pointer) return interfaces.c.unsigned;

   procedure fann_get_layer_array (ann : in fann_c.fann.Pointer;
layers : in swig.pointers.unsigned_Pointer);

   procedure fann_get_bias_array (ann : in fann_c.fann.Pointer;
bias : in swig.pointers.unsigned_Pointer);

   procedure fann_get_connection_array (ann : in fann_c.fann.Pointer;
connections : in fann_c.fann_connection.Pointer);

   procedure fann_set_weight_array (ann : in fann_c.fann.Pointer;
connections : in fann_c.fann_connection.Pointer;
num_connections : in interfaces.c.unsigned);

   procedure fann_set_weight (ann : in fann_c.fann.Pointer;
from_neuron : in interfaces.c.unsigned;
to_neuron : in interfaces.c.unsigned;
weight : in fann_c.fann_type);

   procedure fann_set_user_data (ann : in fann_c.fann.Pointer;
user_data : in swig.void_ptr);

   function  fann_get_user_data (ann : in fann_c.fann.Pointer) return swig.void_ptr;









private



   pragma Import (C, fann_set_error_log, "fann_set_error_log");
   pragma Import (C, fann_get_errno, "fann_get_errno");
   pragma Import (C, fann_reset_errno, "fann_reset_errno");
   pragma Import (C, fann_reset_errstr, "fann_reset_errstr");
   pragma Import (C, fann_get_errstr, "fann_get_errstr");
   pragma Import (C, fann_print_error, "fann_print_error");
   pragma Import (C, create_train_from_callback, "create_train_from_callback");
   pragma Import (C, fann_train, "fann_train");
   pragma Import (C, fann_test, "fann_test");
   pragma Import (C, fann_get_MSE, "fann_get_MSE");
   pragma Import (C, fann_get_bit_fail, "fann_get_bit_fail");
   pragma Import (C, fann_reset_MSE, "fann_reset_MSE");
   pragma Import (C, fann_train_on_data, "fann_train_on_data");
   pragma Import (C, fann_train_on_file, "fann_train_on_file");
   pragma Import (C, fann_train_epoch, "fann_train_epoch");
   pragma Import (C, fann_test_data, "fann_test_data");
   pragma Import (C, fann_read_train_from_file, "fann_read_train_from_file");
   pragma Import (C, fann_create_train, "fann_create_train");
   pragma Import (C, fann_destroy_train, "fann_destroy_train");
   pragma Import (C, fann_shuffle_train_data, "fann_shuffle_train_data");
   pragma Import (C, fann_scale_train, "fann_scale_train");
   pragma Import (C, fann_descale_train, "fann_descale_train");
   pragma Import (C, fann_set_input_scaling_params, "fann_set_input_scaling_params");
   pragma Import (C, fann_set_output_scaling_params, "fann_set_output_scaling_params");
   pragma Import (C, fann_set_scaling_params, "fann_set_scaling_params");
   pragma Import (C, fann_clear_scaling_params, "fann_clear_scaling_params");
   pragma Import (C, fann_scale_input, "fann_scale_input");
   pragma Import (C, fann_scale_output, "fann_scale_output");
   pragma Import (C, fann_descale_input, "fann_descale_input");
   pragma Import (C, fann_descale_output, "fann_descale_output");
   pragma Import (C, fann_scale_input_train_data, "fann_scale_input_train_data");
   pragma Import (C, fann_scale_output_train_data, "fann_scale_output_train_data");
   pragma Import (C, fann_scale_train_data, "fann_scale_train_data");
   pragma Import (C, fann_merge_train_data, "fann_merge_train_data");
   pragma Import (C, fann_duplicate_train_data, "fann_duplicate_train_data");
   pragma Import (C, fann_subset_train_data, "fann_subset_train_data");
   pragma Import (C, fann_length_train_data, "fann_length_train_data");
   pragma Import (C, fann_num_input_train_data, "fann_num_input_train_data");
   pragma Import (C, fann_num_output_train_data, "fann_num_output_train_data");
   pragma Import (C, fann_save_train, "fann_save_train");
   pragma Import (C, fann_save_train_to_fixed, "fann_save_train_to_fixed");
   pragma Import (C, fann_get_training_algorithm, "fann_get_training_algorithm");
   pragma Import (C, fann_set_training_algorithm, "fann_set_training_algorithm");
   pragma Import (C, fann_get_learning_rate, "fann_get_learning_rate");
   pragma Import (C, fann_set_learning_rate, "fann_set_learning_rate");
   pragma Import (C, fann_get_learning_momentum, "fann_get_learning_momentum");
   pragma Import (C, fann_set_learning_momentum, "fann_set_learning_momentum");
   pragma Import (C, fann_get_activation_function, "fann_get_activation_function");
   pragma Import (C, fann_set_activation_function, "fann_set_activation_function");
   pragma Import (C, fann_set_activation_function_layer, "fann_set_activation_function_layer");
   pragma Import (C, fann_set_activation_function_hidden, "fann_set_activation_function_hidden");
   pragma Import (C, fann_set_activation_function_output, "fann_set_activation_function_output");
   pragma Import (C, fann_get_activation_steepness, "fann_get_activation_steepness");
   pragma Import (C, fann_set_activation_steepness, "fann_set_activation_steepness");
   pragma Import (C, fann_set_activation_steepness_layer, "fann_set_activation_steepness_layer");
   pragma Import (C, fann_set_activation_steepness_hidden, "fann_set_activation_steepness_hidden");
   pragma Import (C, fann_set_activation_steepness_output, "fann_set_activation_steepness_output");
   pragma Import (C, fann_get_train_error_function, "fann_get_train_error_function");
   pragma Import (C, fann_set_train_error_function, "fann_set_train_error_function");
   pragma Import (C, fann_get_train_stop_function, "fann_get_train_stop_function");
   pragma Import (C, fann_set_train_stop_function, "fann_set_train_stop_function");
   pragma Import (C, fann_get_bit_fail_limit, "fann_get_bit_fail_limit");
   pragma Import (C, fann_set_bit_fail_limit, "fann_set_bit_fail_limit");
   pragma Import (C, fann_set_callback, "fann_set_callback");
   pragma Import (C, fann_get_quickprop_decay, "fann_get_quickprop_decay");
   pragma Import (C, fann_set_quickprop_decay, "fann_set_quickprop_decay");
   pragma Import (C, fann_get_quickprop_mu, "fann_get_quickprop_mu");
   pragma Import (C, fann_set_quickprop_mu, "fann_set_quickprop_mu");
   pragma Import (C, fann_get_rprop_increase_factor, "fann_get_rprop_increase_factor");
   pragma Import (C, fann_set_rprop_increase_factor, "fann_set_rprop_increase_factor");
   pragma Import (C, fann_get_rprop_decrease_factor, "fann_get_rprop_decrease_factor");
   pragma Import (C, fann_set_rprop_decrease_factor, "fann_set_rprop_decrease_factor");
   pragma Import (C, fann_get_rprop_delta_min, "fann_get_rprop_delta_min");
   pragma Import (C, fann_set_rprop_delta_min, "fann_set_rprop_delta_min");
   pragma Import (C, fann_get_rprop_delta_max, "fann_get_rprop_delta_max");
   pragma Import (C, fann_set_rprop_delta_max, "fann_set_rprop_delta_max");
   pragma Import (C, fann_get_rprop_delta_zero, "fann_get_rprop_delta_zero");
   pragma Import (C, fann_set_rprop_delta_zero, "fann_set_rprop_delta_zero");
   pragma Import (C, fann_get_sarprop_weight_decay_shift, "fann_get_sarprop_weight_decay_shift");
   pragma Import (C, fann_set_sarprop_weight_decay_shift, "fann_set_sarprop_weight_decay_shift");
   pragma Import (C, fann_get_sarprop_step_error_threshold_factor, "fann_get_sarprop_step_error_threshold_factor");
   pragma Import (C, fann_set_sarprop_step_error_threshold_factor, "fann_set_sarprop_step_error_threshold_factor");
   pragma Import (C, fann_get_sarprop_step_error_shift, "fann_get_sarprop_step_error_shift");
   pragma Import (C, fann_set_sarprop_step_error_shift, "fann_set_sarprop_step_error_shift");
   pragma Import (C, fann_get_sarprop_temperature, "fann_get_sarprop_temperature");
   pragma Import (C, fann_set_sarprop_temperature, "fann_set_sarprop_temperature");
   pragma Import (C, fann_cascadetrain_on_data, "fann_cascadetrain_on_data");
   pragma Import (C, fann_cascadetrain_on_file, "fann_cascadetrain_on_file");
   pragma Import (C, fann_get_cascade_output_change_fraction, "fann_get_cascade_output_change_fraction");
   pragma Import (C, fann_set_cascade_output_change_fraction, "fann_set_cascade_output_change_fraction");
   pragma Import (C, fann_get_cascade_output_stagnation_epochs, "fann_get_cascade_output_stagnation_epochs");
   pragma Import (C, fann_set_cascade_output_stagnation_epochs, "fann_set_cascade_output_stagnation_epochs");
   pragma Import (C, fann_get_cascade_candidate_change_fraction, "fann_get_cascade_candidate_change_fraction");
   pragma Import (C, fann_set_cascade_candidate_change_fraction, "fann_set_cascade_candidate_change_fraction");
   pragma Import (C, fann_get_cascade_candidate_stagnation_epochs, "fann_get_cascade_candidate_stagnation_epochs");
   pragma Import (C, fann_set_cascade_candidate_stagnation_epochs, "fann_set_cascade_candidate_stagnation_epochs");
   pragma Import (C, fann_get_cascade_weight_multiplier, "fann_get_cascade_weight_multiplier");
   pragma Import (C, fann_set_cascade_weight_multiplier, "fann_set_cascade_weight_multiplier");
   pragma Import (C, fann_get_cascade_candidate_limit, "fann_get_cascade_candidate_limit");
   pragma Import (C, fann_set_cascade_candidate_limit, "fann_set_cascade_candidate_limit");
   pragma Import (C, fann_get_cascade_max_out_epochs, "fann_get_cascade_max_out_epochs");
   pragma Import (C, fann_set_cascade_max_out_epochs, "fann_set_cascade_max_out_epochs");
   pragma Import (C, fann_get_cascade_min_out_epochs, "fann_get_cascade_min_out_epochs");
   pragma Import (C, fann_set_cascade_min_out_epochs, "fann_set_cascade_min_out_epochs");
   pragma Import (C, fann_get_cascade_max_cand_epochs, "fann_get_cascade_max_cand_epochs");
   pragma Import (C, fann_set_cascade_max_cand_epochs, "fann_set_cascade_max_cand_epochs");
   pragma Import (C, fann_get_cascade_min_cand_epochs, "fann_get_cascade_min_cand_epochs");
   pragma Import (C, fann_set_cascade_min_cand_epochs, "fann_set_cascade_min_cand_epochs");
   pragma Import (C, fann_get_cascade_num_candidates, "fann_get_cascade_num_candidates");
   pragma Import (C, fann_get_cascade_activation_functions_count, "fann_get_cascade_activation_functions_count");
   pragma Import (C, fann_get_cascade_activation_functions, "fann_get_cascade_activation_functions");
   pragma Import (C, fann_set_cascade_activation_functions, "fann_set_cascade_activation_functions");
   pragma Import (C, fann_get_cascade_activation_steepnesses_count, "fann_get_cascade_activation_steepnesses_count");
   pragma Import (C, fann_get_cascade_activation_steepnesses, "fann_get_cascade_activation_steepnesses");
   pragma Import (C, fann_set_cascade_activation_steepnesses, "fann_set_cascade_activation_steepnesses");
   pragma Import (C, fann_get_cascade_num_candidate_groups, "fann_get_cascade_num_candidate_groups");
   pragma Import (C, fann_set_cascade_num_candidate_groups, "fann_set_cascade_num_candidate_groups");
   pragma Import (C, fann_create_from_file, "fann_create_from_file");
   pragma Import (C, fann_save, "fann_save");
   pragma Import (C, fann_save_to_fixed, "fann_save_to_fixed");
   pragma Import (C, fann_create_standard, "fann_create_standard");
   pragma Import (C, fann_create_standard_array, "fann_create_standard_array");
   pragma Import (C, fann_create_sparse, "fann_create_sparse");
   pragma Import (C, fann_create_sparse_array, "fann_create_sparse_array");
   pragma Import (C, fann_create_shortcut, "fann_create_shortcut");
   pragma Import (C, fann_create_shortcut_array, "fann_create_shortcut_array");
   pragma Import (C, fann_destroy, "fann_destroy");
   pragma Import (C, fann_copy, "fann_copy");
   pragma Import (C, fann_run, "fann_run");
   pragma Import (C, fann_randomize_weights, "fann_randomize_weights");
   pragma Import (C, fann_init_weights, "fann_init_weights");
   pragma Import (C, fann_print_connections, "fann_print_connections");
   pragma Import (C, fann_print_parameters, "fann_print_parameters");
   pragma Import (C, fann_get_num_input, "fann_get_num_input");
   pragma Import (C, fann_get_num_output, "fann_get_num_output");
   pragma Import (C, fann_get_total_neurons, "fann_get_total_neurons");
   pragma Import (C, fann_get_total_connections, "fann_get_total_connections");
   pragma Import (C, fann_get_network_type, "fann_get_network_type");
   pragma Import (C, fann_get_connection_rate, "fann_get_connection_rate");
   pragma Import (C, fann_get_num_layers, "fann_get_num_layers");
   pragma Import (C, fann_get_layer_array, "fann_get_layer_array");
   pragma Import (C, fann_get_bias_array, "fann_get_bias_array");
   pragma Import (C, fann_get_connection_array, "fann_get_connection_array");
   pragma Import (C, fann_set_weight_array, "fann_set_weight_array");
   pragma Import (C, fann_set_weight, "fann_set_weight");
   pragma Import (C, fann_set_user_data, "fann_set_user_data");
   pragma Import (C, fann_get_user_data, "fann_get_user_data");



end fann_c.Binding;
