-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces.C;
with swig;
with Interfaces.C;

package TensorFlow_C is

   -- TF_Buffer
   --
   subtype TF_Buffer is swig.opaque_structure;

   type TF_Buffer_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Buffer;

   -- TF_Bool
   --
   subtype TF_Bool is swig.bool;

   type TF_Bool_array is
     array (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Bool;

   -- TF_AttrType
   --
   type TF_AttrType is
     (TF_ATTR_STRING, TF_ATTR_INT, TF_ATTR_FLOAT, TF_ATTR_BOOL,
      TF_ATTR_TYPE, TF_ATTR_SHAPE, TF_ATTR_TENSOR, TF_ATTR_PLACEHOLDER,
      TF_ATTR_FUNC);

   for TF_AttrType use
     (TF_ATTR_STRING      => 0,
      TF_ATTR_INT         => 1,
      TF_ATTR_FLOAT       => 2,
      TF_ATTR_BOOL        => 3,
      TF_ATTR_TYPE        => 4,
      TF_ATTR_SHAPE       => 5,
      TF_ATTR_TENSOR      => 6,
      TF_ATTR_PLACEHOLDER => 7,
      TF_ATTR_FUNC        => 8);

   pragma Convention (C, TF_AttrType);

   type TF_AttrType_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_AttrType;

   -- TF_DataType
   --
   type TF_DataType is
     (TF_FLOAT, TF_DOUBLE, TF_INT32, TF_UINT8, TF_INT16, TF_INT8,
      TF_STRING, TF_COMPLEX64, TF_INT64, TF_BOOLEAN, TF_QINT8, TF_QUINT8,
      TF_QINT32, TF_BFLOAT16, TF_QINT16, TF_QUINT16, TF_UINT16,
      TF_COMPLEX128, TF_HALF, TF_RESOURCE, TF_VARIANT, TF_UINT32,
      TF_UINT64);

   for TF_DataType use
     (TF_FLOAT      => 1,
      TF_DOUBLE     => 2,
      TF_INT32      => 3,
      TF_UINT8      => 4,
      TF_INT16      => 5,
      TF_INT8       => 6,
      TF_STRING     => 7,
      TF_COMPLEX64  => 8,
      TF_INT64      => 9,
      TF_BOOLEAN    => 10,
      TF_QINT8      => 11,
      TF_QUINT8     => 12,
      TF_QINT32     => 13,
      TF_BFLOAT16   => 14,
      TF_QINT16     => 15,
      TF_QUINT16    => 16,
      TF_UINT16     => 17,
      TF_COMPLEX128 => 18,
      TF_HALF       => 19,
      TF_RESOURCE   => 20,
      TF_VARIANT    => 21,
      TF_UINT32     => 22,
      TF_UINT64     => 23);

   pragma Convention (C, TF_DataType);

   type TF_DataType_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_DataType;

   -- TF_Status
   --
   subtype TF_Status is swig.opaque_structure;

   type TF_Status_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Status;

   -- TF_Code
   --
   type TF_Code is
     (TF_OK, TF_CANCELLED, TF_UNKNOWN, TF_INVALID_ARGUMENT,
      TF_DEADLINE_EXCEEDED, TF_NOT_FOUND, TF_ALREADY_EXISTS,
      TF_PERMISSION_DENIED, TF_RESOURCE_EXHAUSTED, TF_FAILED_PRECONDITION,
      TF_ABORTED, TF_OUT_OF_RANGE, TF_UNIMPLEMENTED, TF_INTERNAL,
      TF_UNAVAILABLE, TF_DATA_LOSS, TF_UNAUTHENTICATED);

   for TF_Code use
     (TF_OK                  => 0,
      TF_CANCELLED           => 1,
      TF_UNKNOWN             => 2,
      TF_INVALID_ARGUMENT    => 3,
      TF_DEADLINE_EXCEEDED   => 4,
      TF_NOT_FOUND           => 5,
      TF_ALREADY_EXISTS      => 6,
      TF_PERMISSION_DENIED   => 7,
      TF_RESOURCE_EXHAUSTED  => 8,
      TF_FAILED_PRECONDITION => 9,
      TF_ABORTED             => 10,
      TF_OUT_OF_RANGE        => 11,
      TF_UNIMPLEMENTED       => 12,
      TF_INTERNAL            => 13,
      TF_UNAVAILABLE         => 14,
      TF_DATA_LOSS           => 15,
      TF_UNAUTHENTICATED     => 16);

   pragma Convention (C, TF_Code);

   type TF_Code_array is
     array (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Code;

   -- TF_Tensor
   --
   subtype TF_Tensor is swig.opaque_structure;

   type TF_Tensor_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Tensor;

   -- TF_TString
   --
   subtype TF_TString is swig.opaque_structure;

   type TF_TString_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_TString;

   -- TF_TString_Type
   --
   subtype TF_TString_Type is swig.opaque_structure;

   type TF_TString_Type_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_TString_Type;

   -- TF_Operation_ptr_ptr_ptr
   --
   subtype TF_Operation_ptr_ptr_ptr is swig.opaque_structure;

   type TF_Operation_ptr_ptr_ptr_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_Operation_ptr_ptr_ptr;

   -- TF_SessionOptions
   --
   subtype TF_SessionOptions is swig.opaque_structure;

   type TF_SessionOptions_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_SessionOptions;

   -- TF_Graph
   --
   subtype TF_Graph is swig.opaque_structure;

   type TF_Graph_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Graph;

   -- TF_OperationDescription
   --
   subtype TF_OperationDescription is swig.opaque_structure;

   type TF_OperationDescription_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_OperationDescription;

   -- TF_Operation
   --
   subtype TF_Operation is swig.opaque_structure;

   type TF_Operation_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_Operation;

   -- TF_Function
   --
   subtype TF_Function is swig.opaque_structure;

   type TF_Function_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Function;

   -- TF_FunctionOptions
   --
   subtype TF_FunctionOptions is swig.opaque_structure;

   type TF_FunctionOptions_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_FunctionOptions;

   -- TF_ImportGraphDefOptions
   --
   subtype TF_ImportGraphDefOptions is swig.opaque_structure;

   type TF_ImportGraphDefOptions_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_ImportGraphDefOptions;

   -- TF_ImportGraphDefResults
   --
   subtype TF_ImportGraphDefResults is swig.opaque_structure;

   type TF_ImportGraphDefResults_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_ImportGraphDefResults;

   -- TF_Session
   --
   subtype TF_Session is swig.opaque_structure;

   type TF_Session_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Session;

   -- TF_DeprecatedSession
   --
   subtype TF_DeprecatedSession is swig.opaque_structure;

   type TF_DeprecatedSession_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_DeprecatedSession;

   -- TF_DeviceList
   --
   subtype TF_DeviceList is swig.opaque_structure;

   type TF_DeviceList_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_DeviceList;

   -- TF_Library
   --
   subtype TF_Library is swig.opaque_structure;

   type TF_Library_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Library;

   -- TF_ApiDefMap
   --
   subtype TF_ApiDefMap is swig.opaque_structure;

   type TF_ApiDefMap_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .TF_ApiDefMap;

   -- TF_Server
   --
   subtype TF_Server is swig.opaque_structure;

   type TF_Server_array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C.TF_Server;

   -- Deallocator_T
   --
   type Deallocator_T is
     access
procedure
       (arg_3_1 : in swig.void_ptr; arg_3_2 : in Interfaces.C.size_t;
        arg_3_3 : in swig.void_ptr);
   pragma Convention (C, Deallocator_T);

   -- Deallocator_T_Array
   --
   type Deallocator_T_Array is
     array
       (Interfaces.C.size_t range <>) of aliased TensorFlow_C
       .Deallocator_T;

   TF_COMPLEX : aliased constant TensorFlow_C.TF_DataType := TF_COMPLEX64;

end TensorFlow_C;
