-- This file is generated by SWIG. Please do not modify by hand.
--
with TensorFlow_C.Pointers;
with TensorFlow_C.TF_AttrMetadata;
with TensorFlow_C.TF_Input;
with TensorFlow_C.TF_Output;
with TensorFlow_C.TF_WhileParams;
with TensorFlow_C.pointer_Pointers;
with Interfaces;
with Interfaces.C;
with Interfaces.C.Strings;
with swig;
with swig.pointers;
with Interfaces.C;

package TensorFlow_C.Binding is

   function TF_DataTypeSize
     (dt : in TensorFlow_C.TF_DataType) return Interfaces.C.size_t;

   function TF_NewStatus return TensorFlow_C.Pointers.TF_Status_Pointer;

   procedure TF_DeleteStatus
     (arg_1 : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SetStatus
     (s    : in TensorFlow_C.Pointers.TF_Status_Pointer;
      code : in TensorFlow_C.TF_Code;
      msg  : in Interfaces.C.Strings.chars_ptr);

   procedure TF_SetPayload
     (s     : in TensorFlow_C.Pointers.TF_Status_Pointer;
      key   : in Interfaces.C.Strings.chars_ptr;
      value : in Interfaces.C.Strings.chars_ptr);

   procedure TF_SetStatusFromIOError
     (s          : in TensorFlow_C.Pointers.TF_Status_Pointer;
      error_code : in Interfaces.C.int;
      context    : in Interfaces.C.Strings.chars_ptr);

   function TF_GetCode
     (s : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.TF_Code;

   function TF_Message
     (s : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   function TF_AllocateTensor
     (arg_1    : in TensorFlow_C.TF_DataType;
      dims     : in swig.pointers.int64_t_Pointer;
      num_dims : in Interfaces.C.int; len : in Interfaces.C.size_t)
      return TensorFlow_C.Pointers.TF_Tensor_Pointer;

   function TF_TensorMaybeMove
     (tensor : in TensorFlow_C.Pointers.TF_Tensor_Pointer)
      return TensorFlow_C.Pointers.TF_Tensor_Pointer;

   procedure TF_DeleteTensor
     (arg_1 : in TensorFlow_C.Pointers.TF_Tensor_Pointer);

   function TF_TensorType
     (arg_1 : in TensorFlow_C.Pointers.TF_Tensor_Pointer)
      return TensorFlow_C.TF_DataType;

   procedure TF_SetShape
     (tensor   : in TensorFlow_C.Pointers.TF_Tensor_Pointer;
      dims     : in swig.pointers.int64_t_Pointer;
      num_dims : in Interfaces.C.int);

   function TF_NumDims
     (arg_1 : in TensorFlow_C.Pointers.TF_Tensor_Pointer)
      return Interfaces.C.int;

   function TF_Dim
     (tensor    : in TensorFlow_C.Pointers.TF_Tensor_Pointer;
      dim_index : in Interfaces.C.int) return Interfaces.Integer_64;

   function TF_TensorByteSize
     (arg_1 : in TensorFlow_C.Pointers.TF_Tensor_Pointer)
      return Interfaces.C.size_t;

   function TF_TensorData
     (arg_1 : in TensorFlow_C.Pointers.TF_Tensor_Pointer)
      return swig.void_ptr;

   function TF_TensorElementCount
     (tensor : in TensorFlow_C.Pointers.TF_Tensor_Pointer)
      return Interfaces.Integer_64;

   procedure TF_TensorBitcastFrom
     (from         : in TensorFlow_C.Pointers.TF_Tensor_Pointer;
      the_type     : in TensorFlow_C.TF_DataType;
      to           : in TensorFlow_C.Pointers.TF_Tensor_Pointer;
      new_dims     : in swig.pointers.int64_t_Pointer;
      num_new_dims : in Interfaces.C.int;
      status       : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_TensorIsAligned
     (arg_1 : in TensorFlow_C.Pointers.TF_Tensor_Pointer)
      return swig.bool;

   procedure TF_StringInit
     (t : in TensorFlow_C.Pointers.TF_TString_Pointer);

   procedure TF_StringCopy
     (dst  : in TensorFlow_C.Pointers.TF_TString_Pointer;
      src  : in Interfaces.C.Strings.chars_ptr;
      size : in Interfaces.C.size_t);

   procedure TF_StringAssignView
     (dst  : in TensorFlow_C.Pointers.TF_TString_Pointer;
      src  : in Interfaces.C.Strings.chars_ptr;
      size : in Interfaces.C.size_t);

   function TF_StringGetDataPointer
     (tstr : in TensorFlow_C.Pointers.TF_TString_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   function TF_StringGetType
     (str : in TensorFlow_C.Pointers.TF_TString_Pointer)
      return TensorFlow_C.TF_TString_Type;

   function TF_StringGetSize
     (tstr : in TensorFlow_C.Pointers.TF_TString_Pointer)
      return Interfaces.C.size_t;

   function TF_StringGetCapacity
     (str : in TensorFlow_C.Pointers.TF_TString_Pointer)
      return Interfaces.C.size_t;

   procedure TF_StringDealloc
     (tstr : in TensorFlow_C.Pointers.TF_TString_Pointer);

   function TF_Version return Interfaces.C.Strings.chars_ptr;

   procedure TF_TensorFromProto
     (from   : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      to     : in TensorFlow_C.Pointers.TF_Tensor_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_NewSessionOptions
      return TensorFlow_C.Pointers.TF_SessionOptions_Pointer;

   procedure TF_SetTarget
     (options : in TensorFlow_C.Pointers.TF_SessionOptions_Pointer;
      target  : in Interfaces.C.Strings.chars_ptr);

   procedure TF_SetConfig
     (options : in TensorFlow_C.Pointers.TF_SessionOptions_Pointer;
      proto   : in swig.void_ptr; proto_len : in Interfaces.C.size_t;
      status  : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_DeleteSessionOptions
     (arg_1 : in TensorFlow_C.Pointers.TF_SessionOptions_Pointer);

   function TF_NewGraph return TensorFlow_C.Pointers.TF_Graph_Pointer;

   procedure TF_DeleteGraph
     (arg_1 : in TensorFlow_C.Pointers.TF_Graph_Pointer);

   procedure TF_GraphSetTensorShape
     (graph    : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      output   : in TensorFlow_C.TF_Output.Item;
      dims     : in swig.pointers.int64_t_Pointer;
      num_dims : in Interfaces.C.int;
      status   : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_GraphGetTensorNumDims
     (graph  : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      output : in TensorFlow_C.TF_Output.Item;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.int;

   procedure TF_GraphGetTensorShape
     (graph    : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      output   : in TensorFlow_C.TF_Output.Item;
      dims     : in swig.pointers.int64_t_Pointer;
      num_dims : in Interfaces.C.int;
      status   : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_NewOperationLocked
     (graph     : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      op_type   : in Interfaces.C.Strings.chars_ptr;
      oper_name : in Interfaces.C.Strings.chars_ptr)
      return TensorFlow_C.Pointers.TF_OperationDescription_Pointer;

   function TF_NewOperation
     (graph     : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      op_type   : in Interfaces.C.Strings.chars_ptr;
      oper_name : in Interfaces.C.Strings.chars_ptr)
      return TensorFlow_C.Pointers.TF_OperationDescription_Pointer;

   procedure TF_SetDevice
     (desc   : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      device : in Interfaces.C.Strings.chars_ptr);

   procedure TF_AddInput
     (desc  : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      input : in TensorFlow_C.TF_Output.Item);

   procedure TF_AddInputList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      inputs     : in TensorFlow_C.TF_Output.Pointer;
      num_inputs : in Interfaces.C.int);

   procedure TF_AddControlInput
     (desc  : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      input : in TensorFlow_C.Pointers.TF_Operation_Pointer);

   procedure TF_ColocateWith
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      op   : in TensorFlow_C.Pointers.TF_Operation_Pointer);

   procedure TF_SetAttrString
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in swig.void_ptr; length : in Interfaces.C.size_t);

   procedure TF_SetAttrStringList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in swig.pointers.void_ptr_Pointer;
      lengths    : in swig.pointers.size_t_Pointer;
      num_values : in Interfaces.C.int);

   procedure TF_SetAttrInt
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in Interfaces.Integer_64);

   procedure TF_SetAttrIntList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in swig.pointers.int64_t_Pointer;
      num_values : in Interfaces.C.int);

   procedure TF_SetAttrFloat
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in Interfaces.C.C_float);

   procedure TF_SetAttrFloatList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in swig.pointers.float_Pointer;
      num_values : in Interfaces.C.int);

   procedure TF_SetAttrBool
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in Interfaces.C.unsigned_char);

   procedure TF_SetAttrBoolList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in swig.pointers.unsigned_char_Pointer;
      num_values : in Interfaces.C.int);

   procedure TF_SetAttrType
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in TensorFlow_C.TF_DataType);

   procedure TF_SetAttrTypeList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in TensorFlow_C.Pointers.TF_DataType_Pointer;
      num_values : in Interfaces.C.int);

   procedure TF_SetAttrPlaceholder
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name   : in Interfaces.C.Strings.chars_ptr;
      placeholder : in Interfaces.C.Strings.chars_ptr);

   procedure TF_SetAttrFuncName
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in Interfaces.C.Strings.chars_ptr;
      length    : in Interfaces.C.size_t);

   procedure TF_SetAttrShape
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      dims      : in swig.pointers.int64_t_Pointer;
      num_dims  : in Interfaces.C.int);

   procedure TF_SetAttrShapeList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      dims       : in swig.pointers.int64_t_pointer_Pointer;
      num_dims   : in swig.pointers.int_Pointer;
      num_shapes : in Interfaces.C.int);

   procedure TF_SetAttrTensorShapeProto
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      proto     : in swig.void_ptr; proto_len : in Interfaces.C.size_t;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SetAttrTensorShapeProtoList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      protos     : in swig.pointers.void_ptr_Pointer;
      proto_lens : in swig.pointers.size_t_Pointer;
      num_shapes : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SetAttrTensor
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in TensorFlow_C.Pointers.TF_Tensor_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SetAttrTensorList
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values : in TensorFlow_C.pointer_Pointers.TF_Tensor_Pointer_Pointer;
      num_values : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SetAttrValueProto
     (desc : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      proto     : in swig.void_ptr; proto_len : in Interfaces.C.size_t;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_FinishOperationLocked
     (desc   : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Operation_Pointer;

   function TF_FinishOperation
     (desc   : in TensorFlow_C.Pointers.TF_OperationDescription_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Operation_Pointer;

   function TF_OperationName
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   function TF_OperationOpType
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   function TF_OperationDevice
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   function TF_OperationNumOutputs
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.int;

   function TF_OperationOutputType
     (oper_out : in TensorFlow_C.TF_Output.Item)
      return TensorFlow_C.TF_DataType;

   function TF_OperationOutputListLength
     (oper     : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      arg_name : in Interfaces.C.Strings.chars_ptr;
      status   : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.int;

   function TF_OperationNumInputs
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.int;

   function TF_OperationInputType
     (oper_in : in TensorFlow_C.TF_Input.Item)
      return TensorFlow_C.TF_DataType;

   function TF_OperationInputListLength
     (oper     : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      arg_name : in Interfaces.C.Strings.chars_ptr;
      status   : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.int;

   function TF_OperationInput
     (oper_in : in TensorFlow_C.TF_Input.Item)
      return TensorFlow_C.TF_Output.Item;

   procedure TF_OperationAllInputs
     (oper       : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      inputs     : in TensorFlow_C.TF_Output.Pointer;
      max_inputs : in Interfaces.C.int);

   function TF_OperationOutputNumConsumers
     (oper_out : in TensorFlow_C.TF_Output.Item) return Interfaces.C.int;

   function TF_OperationOutputConsumers
     (oper_out      : in TensorFlow_C.TF_Output.Item;
      consumers     : in TensorFlow_C.TF_Input.Pointer;
      max_consumers : in Interfaces.C.int) return Interfaces.C.int;

   function TF_OperationNumControlInputs
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.int;

   function TF_OperationGetControlInputs
     (oper           : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      control_inputs : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      max_control_inputs : in Interfaces.C.int) return Interfaces.C.int;

   function TF_OperationNumControlOutputs
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.int;

   function TF_OperationGetControlOutputs
     (oper            : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      control_outputs : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      max_control_outputs : in Interfaces.C.int) return Interfaces.C.int;

   function TF_OperationGetAttrMetadata
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.TF_AttrMetadata.Item;

   procedure TF_OperationGetAttrString
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in swig.void_ptr; max_length : in Interfaces.C.size_t;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrStringList
     (oper         : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name    : in Interfaces.C.Strings.chars_ptr;
      values       : in swig.pointers.void_ptr_Pointer;
      lengths      : in swig.pointers.size_t_Pointer;
      max_values   : in Interfaces.C.int; storage : in swig.void_ptr;
      storage_size : in Interfaces.C.size_t;
      status       : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrInt
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in swig.pointers.int64_t_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrIntList
     (oper       : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in swig.pointers.int64_t_Pointer;
      max_values : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrFloat
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in swig.pointers.float_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrFloatList
     (oper       : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in swig.pointers.float_Pointer;
      max_values : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrBool
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in swig.pointers.unsigned_char_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrBoolList
     (oper       : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in swig.pointers.unsigned_char_Pointer;
      max_values : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrType
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in TensorFlow_C.Pointers.TF_DataType_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrTypeList
     (oper       : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values     : in TensorFlow_C.Pointers.TF_DataType_Pointer;
      max_values : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrShape
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in swig.pointers.int64_t_Pointer;
      num_dims  : in Interfaces.C.int;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrShapeList
     (oper         : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name    : in Interfaces.C.Strings.chars_ptr;
      dims         : in swig.pointers.int64_t_pointer_Pointer;
      num_dims     : in swig.pointers.int_Pointer;
      num_shapes   : in Interfaces.C.int;
      storage      : in swig.pointers.int64_t_Pointer;
      storage_size : in Interfaces.C.int;
      status       : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrTensorShapeProto
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value     : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrTensorShapeProtoList
     (oper       : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values : in TensorFlow_C.pointer_Pointers.TF_Buffer_Pointer_Pointer;
      max_values : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrTensor
     (oper      : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      value : in TensorFlow_C.pointer_Pointers.TF_Tensor_Pointer_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrTensorList
     (oper       : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name  : in Interfaces.C.Strings.chars_ptr;
      values : in TensorFlow_C.pointer_Pointers.TF_Tensor_Pointer_Pointer;
      max_values : in Interfaces.C.int;
      status     : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_OperationGetAttrValueProto
     (oper              : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      attr_name         : in Interfaces.C.Strings.chars_ptr;
      output_attr_value : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status            : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_OperationGetNumAttrs
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer)
      return Interfaces.C.int;

   function TF_OperationGetAttrNameLength
     (oper : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      i    : in Interfaces.C.int) return Interfaces.C.int;

   procedure TF_OperationGetAttrName
     (oper   : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      i : in Interfaces.C.int; output : in Interfaces.C.Strings.chars_ptr;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_GraphOperationByName
     (graph     : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      oper_name : in Interfaces.C.Strings.chars_ptr)
      return TensorFlow_C.Pointers.TF_Operation_Pointer;

   function TF_GraphNextOperation
     (graph : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      pos   : in swig.pointers.size_t_Pointer)
      return TensorFlow_C.Pointers.TF_Operation_Pointer;

   procedure TF_GraphToGraphDef
     (graph            : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      output_graph_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status           : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_GraphGetOpDef
     (graph         : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      op_name       : in Interfaces.C.Strings.chars_ptr;
      output_op_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status        : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_GraphVersions
     (graph              : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      output_version_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status             : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_NewImportGraphDefOptions
      return TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;

   procedure TF_DeleteImportGraphDefOptions
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer);

   procedure TF_ImportGraphDefOptionsSetPrefix
     (opts   : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      prefix : in Interfaces.C.Strings.chars_ptr);

   procedure TF_ImportGraphDefOptionsSetDefaultDevice
     (opts   : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      device : in Interfaces.C.Strings.chars_ptr);

   procedure TF_ImportGraphDefOptionsSetUniquifyNames
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      uniquify_names : in Interfaces.C.unsigned_char);

   procedure TF_ImportGraphDefOptionsSetUniquifyPrefix
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      uniquify_prefix : in Interfaces.C.unsigned_char);

   procedure TF_ImportGraphDefOptionsAddInputMapping
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      src_name  : in Interfaces.C.Strings.chars_ptr;
      src_index : in Interfaces.C.int;
      dst       : in TensorFlow_C.TF_Output.Item);

   procedure TF_ImportGraphDefOptionsRemapControlDependency
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      src_name : in Interfaces.C.Strings.chars_ptr;
      dst      : in TensorFlow_C.Pointers.TF_Operation_Pointer);

   procedure TF_ImportGraphDefOptionsAddControlDependency
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      oper : in TensorFlow_C.Pointers.TF_Operation_Pointer);

   procedure TF_ImportGraphDefOptionsAddReturnOutput
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      oper_name : in Interfaces.C.Strings.chars_ptr;
      index     : in Interfaces.C.int);

   function TF_ImportGraphDefOptionsNumReturnOutputs
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer)
      return Interfaces.C.int;

   procedure TF_ImportGraphDefOptionsAddReturnOperation
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      oper_name : in Interfaces.C.Strings.chars_ptr);

   function TF_ImportGraphDefOptionsNumReturnOperations
     (opts : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer)
      return Interfaces.C.int;

   procedure TF_ImportGraphDefResultsReturnOutputs
     (results : in TensorFlow_C.Pointers.TF_ImportGraphDefResults_Pointer;
      num_outputs : in swig.pointers.int_Pointer;
      outputs     : in TensorFlow_C.TF_Output.Pointer_Pointer);

   procedure TF_ImportGraphDefResultsReturnOperations
     (results : in TensorFlow_C.Pointers.TF_ImportGraphDefResults_Pointer;
      num_opers : in swig.pointers.int_Pointer;
      opers     : in TensorFlow_C.TF_Operation_ptr_ptr_ptr);

   procedure TF_ImportGraphDefResultsMissingUnusedInputMappings
     (results : in TensorFlow_C.Pointers.TF_ImportGraphDefResults_Pointer;
      num_missing_unused_input_mappings : in swig.pointers.int_Pointer;
      src_names : in swig.pointers.chars_ptr_pointer_Pointer;
      src_indexes : in swig.pointers.int_pointer_Pointer);

   procedure TF_DeleteImportGraphDefResults
     (results : in TensorFlow_C.Pointers
        .TF_ImportGraphDefResults_Pointer);

   function TF_GraphImportGraphDefWithResults
     (graph     : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      graph_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      options : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_ImportGraphDefResults_Pointer;

   procedure TF_GraphImportGraphDefWithReturnOutputs
     (graph              : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      graph_def          : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      options : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      return_outputs     : in TensorFlow_C.TF_Output.Pointer;
      num_return_outputs : in Interfaces.C.int;
      status             : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_GraphImportGraphDef
     (graph     : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      graph_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      options : in TensorFlow_C.Pointers.TF_ImportGraphDefOptions_Pointer;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_GraphCopyFunction
     (g      : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      func   : in TensorFlow_C.Pointers.TF_Function_Pointer;
      grad   : in TensorFlow_C.Pointers.TF_Function_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_GraphNumFunctions
     (g : in TensorFlow_C.Pointers.TF_Graph_Pointer)
      return Interfaces.C.int;

   function TF_GraphGetFunctions
     (g     : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      funcs : in TensorFlow_C.pointer_Pointers
        .TF_Function_Pointer_Pointer;
      max_func : in Interfaces.C.int;
      status   : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.int;

   procedure TF_OperationToNodeDef
     (oper            : in TensorFlow_C.Pointers.TF_Operation_Pointer;
      output_node_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status          : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_FinishWhile
     (params  : in TensorFlow_C.TF_WhileParams.Pointer;
      status  : in TensorFlow_C.Pointers.TF_Status_Pointer;
      outputs : in TensorFlow_C.TF_Output.Pointer);

   procedure TF_AbortWhile
     (params : in TensorFlow_C.TF_WhileParams.Pointer);

   procedure TF_AddGradients
     (g      : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      y : in TensorFlow_C.TF_Output.Pointer; ny : in Interfaces.C.int;
      x : in TensorFlow_C.TF_Output.Pointer; nx : in Interfaces.C.int;
      dx     : in TensorFlow_C.TF_Output.Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer;
      dy     : in TensorFlow_C.TF_Output.Pointer);

   procedure TF_AddGradientsWithPrefix
     (g      : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      prefix : in Interfaces.C.Strings.chars_ptr;
      y : in TensorFlow_C.TF_Output.Pointer; ny : in Interfaces.C.int;
      x : in TensorFlow_C.TF_Output.Pointer; nx : in Interfaces.C.int;
      dx     : in TensorFlow_C.TF_Output.Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer;
      dy     : in TensorFlow_C.TF_Output.Pointer);

   function TF_GraphToFunction
     (fn_body                : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      fn_name                : in Interfaces.C.Strings.chars_ptr;
      append_hash_to_fn_name : in Interfaces.C.unsigned_char;
      num_opers              : in Interfaces.C.int;
      opers                  : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      ninputs      : in Interfaces.C.int;
      inputs       : in TensorFlow_C.TF_Output.Pointer;
      noutputs     : in Interfaces.C.int;
      outputs      : in TensorFlow_C.TF_Output.Pointer;
      output_names : in swig.pointers.chars_ptr_Pointer;
      opts         : in TensorFlow_C.Pointers.TF_FunctionOptions_Pointer;
      description  : in Interfaces.C.Strings.chars_ptr;
      status       : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Function_Pointer;

   function TF_GraphToFunctionWithControlOutputs
     (fn_body                : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      fn_name                : in Interfaces.C.Strings.chars_ptr;
      append_hash_to_fn_name : in Interfaces.C.unsigned_char;
      num_opers              : in Interfaces.C.int;
      opers                  : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      ninputs          : in Interfaces.C.int;
      inputs           : in TensorFlow_C.TF_Output.Pointer;
      noutputs         : in Interfaces.C.int;
      outputs          : in TensorFlow_C.TF_Output.Pointer;
      output_names     : in swig.pointers.chars_ptr_Pointer;
      ncontrol_outputs : in Interfaces.C.int;
      control_outputs  : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      control_output_names : in swig.pointers.chars_ptr_Pointer;
      opts : in TensorFlow_C.Pointers.TF_FunctionOptions_Pointer;
      description          : in Interfaces.C.Strings.chars_ptr;
      status               : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Function_Pointer;

   function TF_FunctionName
     (func : in TensorFlow_C.Pointers.TF_Function_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   procedure TF_FunctionToFunctionDef
     (func            : in TensorFlow_C.Pointers.TF_Function_Pointer;
      output_func_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status          : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_FunctionImportFunctionDef
     (proto  : in swig.void_ptr; proto_len : in Interfaces.C.size_t;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Function_Pointer;

   procedure TF_FunctionSetAttrValueProto
     (func      : in TensorFlow_C.Pointers.TF_Function_Pointer;
      attr_name : in Interfaces.C.Strings.chars_ptr;
      proto     : in swig.void_ptr; proto_len : in Interfaces.C.size_t;
      status    : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_FunctionGetAttrValueProto
     (func              : in TensorFlow_C.Pointers.TF_Function_Pointer;
      attr_name         : in Interfaces.C.Strings.chars_ptr;
      output_attr_value : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status            : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_DeleteFunction
     (func : in TensorFlow_C.Pointers.TF_Function_Pointer);

   function TF_TryEvaluateConstant
     (graph  : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      output : in TensorFlow_C.TF_Output.Item;
      result : in TensorFlow_C.pointer_Pointers.TF_Tensor_Pointer_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.unsigned_char;

   function TF_NewSession
     (graph  : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      opts   : in TensorFlow_C.Pointers.TF_SessionOptions_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Session_Pointer;

   function TF_LoadSessionFromSavedModel
     (session_options : in TensorFlow_C.Pointers
        .TF_SessionOptions_Pointer;
      run_options    : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      export_dir     : in Interfaces.C.Strings.chars_ptr;
      tags           : in swig.pointers.chars_ptr_Pointer;
      tags_len       : in Interfaces.C.int;
      graph          : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      meta_graph_def : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status         : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Session_Pointer;

   procedure TF_CloseSession
     (arg_1  : in TensorFlow_C.Pointers.TF_Session_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_DeleteSession
     (arg_1  : in TensorFlow_C.Pointers.TF_Session_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SessionRun
     (session      : in TensorFlow_C.Pointers.TF_Session_Pointer;
      run_options  : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      inputs       : in TensorFlow_C.TF_Output.Pointer;
      input_values : in TensorFlow_C.pointer_Pointers
        .TF_Tensor_Pointer_Pointer;
      ninputs       : in Interfaces.C.int;
      outputs       : in TensorFlow_C.TF_Output.Pointer;
      output_values : in TensorFlow_C.pointer_Pointers
        .TF_Tensor_Pointer_Pointer;
      noutputs     : in Interfaces.C.int;
      target_opers : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      ntargets     : in Interfaces.C.int;
      run_metadata : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      arg_1        : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SessionPRunSetup
     (arg_2_1      : in TensorFlow_C.Pointers.TF_Session_Pointer;
      inputs       : in TensorFlow_C.TF_Output.Pointer;
      ninputs      : in Interfaces.C.int;
      outputs      : in TensorFlow_C.TF_Output.Pointer;
      noutputs     : in Interfaces.C.int;
      target_opers : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      ntargets : in Interfaces.C.int;
      handle   : in swig.pointers.chars_ptr_Pointer;
      arg_2_2  : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_SessionPRun
     (arg_2_1      : in TensorFlow_C.Pointers.TF_Session_Pointer;
      handle       : in Interfaces.C.Strings.chars_ptr;
      inputs       : in TensorFlow_C.TF_Output.Pointer;
      input_values : in TensorFlow_C.pointer_Pointers
        .TF_Tensor_Pointer_Pointer;
      ninputs       : in Interfaces.C.int;
      outputs       : in TensorFlow_C.TF_Output.Pointer;
      output_values : in TensorFlow_C.pointer_Pointers
        .TF_Tensor_Pointer_Pointer;
      noutputs     : in Interfaces.C.int;
      target_opers : in TensorFlow_C.pointer_Pointers
        .TF_Operation_Pointer_Pointer;
      ntargets : in Interfaces.C.int;
      arg_2_2  : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_DeletePRunHandle
     (handle : in Interfaces.C.Strings.chars_ptr);

   function TF_NewDeprecatedSession
     (arg_1  : in TensorFlow_C.Pointers.TF_SessionOptions_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;

   procedure TF_CloseDeprecatedSession
     (arg_1  : in TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_DeleteDeprecatedSession
     (arg_1  : in TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_Reset
     (opt         : in TensorFlow_C.Pointers.TF_SessionOptions_Pointer;
      containers  : in swig.pointers.chars_ptr_Pointer;
      ncontainers : in Interfaces.C.int;
      status      : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_ExtendGraph
     (arg_2_1 : in TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;
      proto   : in swig.void_ptr; proto_len : in Interfaces.C.size_t;
      arg_2_2 : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_Run
     (arg_2_1 : in TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;
      run_options  : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      input_names  : in swig.pointers.chars_ptr_Pointer;
      inputs : in TensorFlow_C.pointer_Pointers.TF_Tensor_Pointer_Pointer;
      ninputs      : in Interfaces.C.int;
      output_names : in swig.pointers.chars_ptr_Pointer;
      outputs      : in TensorFlow_C.pointer_Pointers
        .TF_Tensor_Pointer_Pointer;
      noutputs          : in Interfaces.C.int;
      target_oper_names : in swig.pointers.chars_ptr_Pointer;
      ntargets          : in Interfaces.C.int;
      run_metadata      : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      arg_2_2           : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_PRunSetup
     (arg_2_1 : in TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;
      input_names       : in swig.pointers.chars_ptr_Pointer;
      ninputs           : in Interfaces.C.int;
      output_names      : in swig.pointers.chars_ptr_Pointer;
      noutputs          : in Interfaces.C.int;
      target_oper_names : in swig.pointers.chars_ptr_Pointer;
      ntargets          : in Interfaces.C.int;
      handle            : in swig.pointers.chars_ptr_Pointer;
      arg_2_2           : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_PRun
     (arg_2_1 : in TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;
      handle       : in Interfaces.C.Strings.chars_ptr;
      input_names  : in swig.pointers.chars_ptr_Pointer;
      inputs : in TensorFlow_C.pointer_Pointers.TF_Tensor_Pointer_Pointer;
      ninputs      : in Interfaces.C.int;
      output_names : in swig.pointers.chars_ptr_Pointer;
      outputs      : in TensorFlow_C.pointer_Pointers
        .TF_Tensor_Pointer_Pointer;
      noutputs          : in Interfaces.C.int;
      target_oper_names : in swig.pointers.chars_ptr_Pointer;
      ntargets          : in Interfaces.C.int;
      arg_2_2           : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_SessionListDevices
     (session : in TensorFlow_C.Pointers.TF_Session_Pointer;
      status  : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_DeviceList_Pointer;

   function TF_DeprecatedSessionListDevices
     (session : in TensorFlow_C.Pointers.TF_DeprecatedSession_Pointer;
      status  : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_DeviceList_Pointer;

   procedure TF_DeleteDeviceList
     (list : in TensorFlow_C.Pointers.TF_DeviceList_Pointer);

   function TF_DeviceListCount
     (list : in TensorFlow_C.Pointers.TF_DeviceList_Pointer)
      return Interfaces.C.int;

   function TF_DeviceListName
     (list   : in TensorFlow_C.Pointers.TF_DeviceList_Pointer;
      index  : in Interfaces.C.int;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   function TF_DeviceListType
     (list   : in TensorFlow_C.Pointers.TF_DeviceList_Pointer;
      index  : in Interfaces.C.int;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   function TF_DeviceListMemoryBytes
     (list   : in TensorFlow_C.Pointers.TF_DeviceList_Pointer;
      index  : in Interfaces.C.int;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.Integer_64;

   function TF_DeviceListIncarnation
     (list   : in TensorFlow_C.Pointers.TF_DeviceList_Pointer;
      index  : in Interfaces.C.int;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return Interfaces.Unsigned_64;

   function TF_LoadLibrary
     (library_filename : in Interfaces.C.Strings.chars_ptr;
      status           : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Library_Pointer;

   function TF_GetOpList
     (lib_handle : in TensorFlow_C.Pointers.TF_Library_Pointer)
      return TensorFlow_C.TF_Buffer;

   procedure TF_DeleteLibraryHandle
     (lib_handle : in TensorFlow_C.Pointers.TF_Library_Pointer);

   function TF_GetAllOpList
      return TensorFlow_C.Pointers.TF_Buffer_Pointer;

   function TF_NewApiDefMap
     (op_list_buffer : in TensorFlow_C.Pointers.TF_Buffer_Pointer;
      status         : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_ApiDefMap_Pointer;

   procedure TF_DeleteApiDefMap
     (apimap : in TensorFlow_C.Pointers.TF_ApiDefMap_Pointer);

   procedure TF_ApiDefMapPut
     (api_def_map : in TensorFlow_C.Pointers.TF_ApiDefMap_Pointer;
      text        : in Interfaces.C.Strings.chars_ptr;
      text_len    : in Interfaces.C.size_t;
      status      : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_ApiDefMapGet
     (api_def_map : in TensorFlow_C.Pointers.TF_ApiDefMap_Pointer;
      name        : in Interfaces.C.Strings.chars_ptr;
      name_len    : in Interfaces.C.size_t;
      status      : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Buffer_Pointer;

   function TF_GetAllRegisteredKernels
     (status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Buffer_Pointer;

   function TF_GetRegisteredKernelsForOp
     (name   : in Interfaces.C.Strings.chars_ptr;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Buffer_Pointer;

   procedure TF_UpdateEdge
     (graph   : in TensorFlow_C.Pointers.TF_Graph_Pointer;
      new_src : in TensorFlow_C.TF_Output.Item;
      dst     : in TensorFlow_C.TF_Input.Item;
      status  : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_NewServer
     (proto  : in swig.void_ptr; proto_len : in Interfaces.C.size_t;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer)
      return TensorFlow_C.Pointers.TF_Server_Pointer;

   procedure TF_ServerStart
     (server : in TensorFlow_C.Pointers.TF_Server_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_ServerStop
     (server : in TensorFlow_C.Pointers.TF_Server_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   procedure TF_ServerJoin
     (server : in TensorFlow_C.Pointers.TF_Server_Pointer;
      status : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_ServerTarget
     (server : in TensorFlow_C.Pointers.TF_Server_Pointer)
      return Interfaces.C.Strings.chars_ptr;

   procedure TF_DeleteServer
     (server : in TensorFlow_C.Pointers.TF_Server_Pointer);

   procedure TF_RegisterFilesystemPlugin
     (plugin_filename : in Interfaces.C.Strings.chars_ptr;
      status          : in TensorFlow_C.Pointers.TF_Status_Pointer);

   function TF_CreateNewTensor
     (data_type       : in TensorFlow_C.TF_DataType;
      dims            : in swig.pointers.int64_t_Pointer;
      num_dims        : in Interfaces.C.int; data : in swig.void_ptr;
      len             : in Interfaces.C.size_t;
      deallocator     : in TensorFlow_C.Deallocator_T;
      deallocator_arg : in swig.void_ptr)
      return TensorFlow_C.Pointers.TF_Tensor_Pointer;

private

   pragma Import (C, TF_DataTypeSize, "Ada_TF_DataTypeSize");
   pragma Import (C, TF_NewStatus, "Ada_TF_NewStatus");
   pragma Import (C, TF_DeleteStatus, "Ada_TF_DeleteStatus");
   pragma Import (C, TF_SetStatus, "Ada_TF_SetStatus");
   pragma Import (C, TF_SetPayload, "Ada_TF_SetPayload");
   pragma Import
     (C, TF_SetStatusFromIOError, "Ada_TF_SetStatusFromIOError");
   pragma Import (C, TF_GetCode, "Ada_TF_GetCode");
   pragma Import (C, TF_Message, "Ada_TF_Message");
   pragma Import (C, TF_AllocateTensor, "Ada_TF_AllocateTensor");
   pragma Import (C, TF_TensorMaybeMove, "Ada_TF_TensorMaybeMove");
   pragma Import (C, TF_DeleteTensor, "Ada_TF_DeleteTensor");
   pragma Import (C, TF_TensorType, "Ada_TF_TensorType");
   pragma Import (C, TF_SetShape, "Ada_TF_SetShape");
   pragma Import (C, TF_NumDims, "Ada_TF_NumDims");
   pragma Import (C, TF_Dim, "Ada_TF_Dim");
   pragma Import (C, TF_TensorByteSize, "Ada_TF_TensorByteSize");
   pragma Import (C, TF_TensorData, "Ada_TF_TensorData");
   pragma Import (C, TF_TensorElementCount, "Ada_TF_TensorElementCount");
   pragma Import (C, TF_TensorBitcastFrom, "Ada_TF_TensorBitcastFrom");
   pragma Import (C, TF_TensorIsAligned, "Ada_TF_TensorIsAligned");
   pragma Import (C, TF_StringInit, "Ada_TF_StringInit");
   pragma Import (C, TF_StringCopy, "Ada_TF_StringCopy");
   pragma Import (C, TF_StringAssignView, "Ada_TF_StringAssignView");
   pragma Import
     (C, TF_StringGetDataPointer, "Ada_TF_StringGetDataPointer");
   pragma Import (C, TF_StringGetType, "Ada_TF_StringGetType");
   pragma Import (C, TF_StringGetSize, "Ada_TF_StringGetSize");
   pragma Import (C, TF_StringGetCapacity, "Ada_TF_StringGetCapacity");
   pragma Import (C, TF_StringDealloc, "Ada_TF_StringDealloc");
   pragma Import (C, TF_Version, "Ada_TF_Version");
   pragma Import (C, TF_TensorFromProto, "Ada_TF_TensorFromProto");
   pragma Import (C, TF_NewSessionOptions, "Ada_TF_NewSessionOptions");
   pragma Import (C, TF_SetTarget, "Ada_TF_SetTarget");
   pragma Import (C, TF_SetConfig, "Ada_TF_SetConfig");
   pragma Import
     (C, TF_DeleteSessionOptions, "Ada_TF_DeleteSessionOptions");
   pragma Import (C, TF_NewGraph, "Ada_TF_NewGraph");
   pragma Import (C, TF_DeleteGraph, "Ada_TF_DeleteGraph");
   pragma Import
     (C, TF_GraphSetTensorShape, "Ada_TF_GraphSetTensorShape");
   pragma Import
     (C, TF_GraphGetTensorNumDims, "Ada_TF_GraphGetTensorNumDims");
   pragma Import
     (C, TF_GraphGetTensorShape, "Ada_TF_GraphGetTensorShape");
   pragma Import (C, TF_NewOperationLocked, "Ada_TF_NewOperationLocked");
   pragma Import (C, TF_NewOperation, "Ada_TF_NewOperation");
   pragma Import (C, TF_SetDevice, "Ada_TF_SetDevice");
   pragma Import (C, TF_AddInput, "Ada_TF_AddInput");
   pragma Import (C, TF_AddInputList, "Ada_TF_AddInputList");
   pragma Import (C, TF_AddControlInput, "Ada_TF_AddControlInput");
   pragma Import (C, TF_ColocateWith, "Ada_TF_ColocateWith");
   pragma Import (C, TF_SetAttrString, "Ada_TF_SetAttrString");
   pragma Import (C, TF_SetAttrStringList, "Ada_TF_SetAttrStringList");
   pragma Import (C, TF_SetAttrInt, "Ada_TF_SetAttrInt");
   pragma Import (C, TF_SetAttrIntList, "Ada_TF_SetAttrIntList");
   pragma Import (C, TF_SetAttrFloat, "Ada_TF_SetAttrFloat");
   pragma Import (C, TF_SetAttrFloatList, "Ada_TF_SetAttrFloatList");
   pragma Import (C, TF_SetAttrBool, "Ada_TF_SetAttrBool");
   pragma Import (C, TF_SetAttrBoolList, "Ada_TF_SetAttrBoolList");
   pragma Import (C, TF_SetAttrType, "Ada_TF_SetAttrType");
   pragma Import (C, TF_SetAttrTypeList, "Ada_TF_SetAttrTypeList");
   pragma Import (C, TF_SetAttrPlaceholder, "Ada_TF_SetAttrPlaceholder");
   pragma Import (C, TF_SetAttrFuncName, "Ada_TF_SetAttrFuncName");
   pragma Import (C, TF_SetAttrShape, "Ada_TF_SetAttrShape");
   pragma Import (C, TF_SetAttrShapeList, "Ada_TF_SetAttrShapeList");
   pragma Import
     (C, TF_SetAttrTensorShapeProto, "Ada_TF_SetAttrTensorShapeProto");
   pragma Import
     (C, TF_SetAttrTensorShapeProtoList,
      "Ada_TF_SetAttrTensorShapeProtoList");
   pragma Import (C, TF_SetAttrTensor, "Ada_TF_SetAttrTensor");
   pragma Import (C, TF_SetAttrTensorList, "Ada_TF_SetAttrTensorList");
   pragma Import (C, TF_SetAttrValueProto, "Ada_TF_SetAttrValueProto");
   pragma Import
     (C, TF_FinishOperationLocked, "Ada_TF_FinishOperationLocked");
   pragma Import (C, TF_FinishOperation, "Ada_TF_FinishOperation");
   pragma Import (C, TF_OperationName, "Ada_TF_OperationName");
   pragma Import (C, TF_OperationOpType, "Ada_TF_OperationOpType");
   pragma Import (C, TF_OperationDevice, "Ada_TF_OperationDevice");
   pragma Import
     (C, TF_OperationNumOutputs, "Ada_TF_OperationNumOutputs");
   pragma Import
     (C, TF_OperationOutputType, "Ada_TF_OperationOutputType");
   pragma Import
     (C, TF_OperationOutputListLength,
      "Ada_TF_OperationOutputListLength");
   pragma Import (C, TF_OperationNumInputs, "Ada_TF_OperationNumInputs");
   pragma Import (C, TF_OperationInputType, "Ada_TF_OperationInputType");
   pragma Import
     (C, TF_OperationInputListLength, "Ada_TF_OperationInputListLength");
   pragma Import (C, TF_OperationInput, "Ada_TF_OperationInput");
   pragma Import (C, TF_OperationAllInputs, "Ada_TF_OperationAllInputs");
   pragma Import
     (C, TF_OperationOutputNumConsumers,
      "Ada_TF_OperationOutputNumConsumers");
   pragma Import
     (C, TF_OperationOutputConsumers, "Ada_TF_OperationOutputConsumers");
   pragma Import
     (C, TF_OperationNumControlInputs,
      "Ada_TF_OperationNumControlInputs");
   pragma Import
     (C, TF_OperationGetControlInputs,
      "Ada_TF_OperationGetControlInputs");
   pragma Import
     (C, TF_OperationNumControlOutputs,
      "Ada_TF_OperationNumControlOutputs");
   pragma Import
     (C, TF_OperationGetControlOutputs,
      "Ada_TF_OperationGetControlOutputs");
   pragma Import
     (C, TF_OperationGetAttrMetadata, "Ada_TF_OperationGetAttrMetadata");
   pragma Import
     (C, TF_OperationGetAttrString, "Ada_TF_OperationGetAttrString");
   pragma Import
     (C, TF_OperationGetAttrStringList,
      "Ada_TF_OperationGetAttrStringList");
   pragma Import
     (C, TF_OperationGetAttrInt, "Ada_TF_OperationGetAttrInt");
   pragma Import
     (C, TF_OperationGetAttrIntList, "Ada_TF_OperationGetAttrIntList");
   pragma Import
     (C, TF_OperationGetAttrFloat, "Ada_TF_OperationGetAttrFloat");
   pragma Import
     (C, TF_OperationGetAttrFloatList,
      "Ada_TF_OperationGetAttrFloatList");
   pragma Import
     (C, TF_OperationGetAttrBool, "Ada_TF_OperationGetAttrBool");
   pragma Import
     (C, TF_OperationGetAttrBoolList, "Ada_TF_OperationGetAttrBoolList");
   pragma Import
     (C, TF_OperationGetAttrType, "Ada_TF_OperationGetAttrType");
   pragma Import
     (C, TF_OperationGetAttrTypeList, "Ada_TF_OperationGetAttrTypeList");
   pragma Import
     (C, TF_OperationGetAttrShape, "Ada_TF_OperationGetAttrShape");
   pragma Import
     (C, TF_OperationGetAttrShapeList,
      "Ada_TF_OperationGetAttrShapeList");
   pragma Import
     (C, TF_OperationGetAttrTensorShapeProto,
      "Ada_TF_OperationGetAttrTensorShapeProto");
   pragma Import
     (C, TF_OperationGetAttrTensorShapeProtoList,
      "Ada_TF_OperationGetAttrTensorShapeProtoList");
   pragma Import
     (C, TF_OperationGetAttrTensor, "Ada_TF_OperationGetAttrTensor");
   pragma Import
     (C, TF_OperationGetAttrTensorList,
      "Ada_TF_OperationGetAttrTensorList");
   pragma Import
     (C, TF_OperationGetAttrValueProto,
      "Ada_TF_OperationGetAttrValueProto");
   pragma Import
     (C, TF_OperationGetNumAttrs, "Ada_TF_OperationGetNumAttrs");
   pragma Import
     (C, TF_OperationGetAttrNameLength,
      "Ada_TF_OperationGetAttrNameLength");
   pragma Import
     (C, TF_OperationGetAttrName, "Ada_TF_OperationGetAttrName");
   pragma Import
     (C, TF_GraphOperationByName, "Ada_TF_GraphOperationByName");
   pragma Import (C, TF_GraphNextOperation, "Ada_TF_GraphNextOperation");
   pragma Import (C, TF_GraphToGraphDef, "Ada_TF_GraphToGraphDef");
   pragma Import (C, TF_GraphGetOpDef, "Ada_TF_GraphGetOpDef");
   pragma Import (C, TF_GraphVersions, "Ada_TF_GraphVersions");
   pragma Import
     (C, TF_NewImportGraphDefOptions, "Ada_TF_NewImportGraphDefOptions");
   pragma Import
     (C, TF_DeleteImportGraphDefOptions,
      "Ada_TF_DeleteImportGraphDefOptions");
   pragma Import
     (C, TF_ImportGraphDefOptionsSetPrefix,
      "Ada_TF_ImportGraphDefOptionsSetPrefix");
   pragma Import
     (C, TF_ImportGraphDefOptionsSetDefaultDevice,
      "Ada_TF_ImportGraphDefOptionsSetDefaultDevice");
   pragma Import
     (C, TF_ImportGraphDefOptionsSetUniquifyNames,
      "Ada_TF_ImportGraphDefOptionsSetUniquifyNames");
   pragma Import
     (C, TF_ImportGraphDefOptionsSetUniquifyPrefix,
      "Ada_TF_ImportGraphDefOptionsSetUniquifyPrefix");
   pragma Import
     (C, TF_ImportGraphDefOptionsAddInputMapping,
      "Ada_TF_ImportGraphDefOptionsAddInputMapping");
   pragma Import
     (C, TF_ImportGraphDefOptionsRemapControlDependency,
      "Ada_TF_ImportGraphDefOptionsRemapControlDependency");
   pragma Import
     (C, TF_ImportGraphDefOptionsAddControlDependency,
      "Ada_TF_ImportGraphDefOptionsAddControlDependency");
   pragma Import
     (C, TF_ImportGraphDefOptionsAddReturnOutput,
      "Ada_TF_ImportGraphDefOptionsAddReturnOutput");
   pragma Import
     (C, TF_ImportGraphDefOptionsNumReturnOutputs,
      "Ada_TF_ImportGraphDefOptionsNumReturnOutputs");
   pragma Import
     (C, TF_ImportGraphDefOptionsAddReturnOperation,
      "Ada_TF_ImportGraphDefOptionsAddReturnOperation");
   pragma Import
     (C, TF_ImportGraphDefOptionsNumReturnOperations,
      "Ada_TF_ImportGraphDefOptionsNumReturnOperations");
   pragma Import
     (C, TF_ImportGraphDefResultsReturnOutputs,
      "Ada_TF_ImportGraphDefResultsReturnOutputs");
   pragma Import
     (C, TF_ImportGraphDefResultsReturnOperations,
      "Ada_TF_ImportGraphDefResultsReturnOperations");
   pragma Import
     (C, TF_ImportGraphDefResultsMissingUnusedInputMappings,
      "Ada_TF_ImportGraphDefResultsMissingUnusedInputMappings");
   pragma Import
     (C, TF_DeleteImportGraphDefResults,
      "Ada_TF_DeleteImportGraphDefResults");
   pragma Import
     (C, TF_GraphImportGraphDefWithResults,
      "Ada_TF_GraphImportGraphDefWithResults");
   pragma Import
     (C, TF_GraphImportGraphDefWithReturnOutputs,
      "Ada_TF_GraphImportGraphDefWithReturnOutputs");
   pragma Import
     (C, TF_GraphImportGraphDef, "Ada_TF_GraphImportGraphDef");
   pragma Import (C, TF_GraphCopyFunction, "Ada_TF_GraphCopyFunction");
   pragma Import (C, TF_GraphNumFunctions, "Ada_TF_GraphNumFunctions");
   pragma Import (C, TF_GraphGetFunctions, "Ada_TF_GraphGetFunctions");
   pragma Import (C, TF_OperationToNodeDef, "Ada_TF_OperationToNodeDef");
   pragma Import (C, TF_FinishWhile, "Ada_TF_FinishWhile");
   pragma Import (C, TF_AbortWhile, "Ada_TF_AbortWhile");
   pragma Import (C, TF_AddGradients, "Ada_TF_AddGradients");
   pragma Import
     (C, TF_AddGradientsWithPrefix, "Ada_TF_AddGradientsWithPrefix");
   pragma Import (C, TF_GraphToFunction, "Ada_TF_GraphToFunction");
   pragma Import
     (C, TF_GraphToFunctionWithControlOutputs,
      "Ada_TF_GraphToFunctionWithControlOutputs");
   pragma Import (C, TF_FunctionName, "Ada_TF_FunctionName");
   pragma Import
     (C, TF_FunctionToFunctionDef, "Ada_TF_FunctionToFunctionDef");
   pragma Import
     (C, TF_FunctionImportFunctionDef,
      "Ada_TF_FunctionImportFunctionDef");
   pragma Import
     (C, TF_FunctionSetAttrValueProto,
      "Ada_TF_FunctionSetAttrValueProto");
   pragma Import
     (C, TF_FunctionGetAttrValueProto,
      "Ada_TF_FunctionGetAttrValueProto");
   pragma Import (C, TF_DeleteFunction, "Ada_TF_DeleteFunction");
   pragma Import
     (C, TF_TryEvaluateConstant, "Ada_TF_TryEvaluateConstant");
   pragma Import (C, TF_NewSession, "Ada_TF_NewSession");
   pragma Import
     (C, TF_LoadSessionFromSavedModel,
      "Ada_TF_LoadSessionFromSavedModel");
   pragma Import (C, TF_CloseSession, "Ada_TF_CloseSession");
   pragma Import (C, TF_DeleteSession, "Ada_TF_DeleteSession");
   pragma Import (C, TF_SessionRun, "Ada_TF_SessionRun");
   pragma Import (C, TF_SessionPRunSetup, "Ada_TF_SessionPRunSetup");
   pragma Import (C, TF_SessionPRun, "Ada_TF_SessionPRun");
   pragma Import (C, TF_DeletePRunHandle, "Ada_TF_DeletePRunHandle");
   pragma Import
     (C, TF_NewDeprecatedSession, "Ada_TF_NewDeprecatedSession");
   pragma Import
     (C, TF_CloseDeprecatedSession, "Ada_TF_CloseDeprecatedSession");
   pragma Import
     (C, TF_DeleteDeprecatedSession, "Ada_TF_DeleteDeprecatedSession");
   pragma Import (C, TF_Reset, "Ada_TF_Reset");
   pragma Import (C, TF_ExtendGraph, "Ada_TF_ExtendGraph");
   pragma Import (C, TF_Run, "Ada_TF_Run");
   pragma Import (C, TF_PRunSetup, "Ada_TF_PRunSetup");
   pragma Import (C, TF_PRun, "Ada_TF_PRun");
   pragma Import (C, TF_SessionListDevices, "Ada_TF_SessionListDevices");
   pragma Import
     (C, TF_DeprecatedSessionListDevices,
      "Ada_TF_DeprecatedSessionListDevices");
   pragma Import (C, TF_DeleteDeviceList, "Ada_TF_DeleteDeviceList");
   pragma Import (C, TF_DeviceListCount, "Ada_TF_DeviceListCount");
   pragma Import (C, TF_DeviceListName, "Ada_TF_DeviceListName");
   pragma Import (C, TF_DeviceListType, "Ada_TF_DeviceListType");
   pragma Import
     (C, TF_DeviceListMemoryBytes, "Ada_TF_DeviceListMemoryBytes");
   pragma Import
     (C, TF_DeviceListIncarnation, "Ada_TF_DeviceListIncarnation");
   pragma Import (C, TF_LoadLibrary, "Ada_TF_LoadLibrary");
   pragma Import (C, TF_GetOpList, "Ada_TF_GetOpList");
   pragma Import
     (C, TF_DeleteLibraryHandle, "Ada_TF_DeleteLibraryHandle");
   pragma Import (C, TF_GetAllOpList, "Ada_TF_GetAllOpList");
   pragma Import (C, TF_NewApiDefMap, "Ada_TF_NewApiDefMap");
   pragma Import (C, TF_DeleteApiDefMap, "Ada_TF_DeleteApiDefMap");
   pragma Import (C, TF_ApiDefMapPut, "Ada_TF_ApiDefMapPut");
   pragma Import (C, TF_ApiDefMapGet, "Ada_TF_ApiDefMapGet");
   pragma Import
     (C, TF_GetAllRegisteredKernels, "Ada_TF_GetAllRegisteredKernels");
   pragma Import
     (C, TF_GetRegisteredKernelsForOp,
      "Ada_TF_GetRegisteredKernelsForOp");
   pragma Import (C, TF_UpdateEdge, "Ada_TF_UpdateEdge");
   pragma Import (C, TF_NewServer, "Ada_TF_NewServer");
   pragma Import (C, TF_ServerStart, "Ada_TF_ServerStart");
   pragma Import (C, TF_ServerStop, "Ada_TF_ServerStop");
   pragma Import (C, TF_ServerJoin, "Ada_TF_ServerJoin");
   pragma Import (C, TF_ServerTarget, "Ada_TF_ServerTarget");
   pragma Import (C, TF_DeleteServer, "Ada_TF_DeleteServer");
   pragma Import
     (C, TF_RegisterFilesystemPlugin, "Ada_TF_RegisterFilesystemPlugin");
   pragma Import (C, TF_CreateNewTensor, "Ada_TF_CreateNewTensor");

end TensorFlow_C.Binding;
