-- This file is generated by SWIG. Please do not modify by hand.
--
with swig;
with Interfaces.C;
with Interfaces.C.Pointers;

package xcb.xcb_client_message_data_t is

   -- Item
   --

   type Item_variant is (data8_variant, data16_variant, data32_variant);

   type Item (union_Variant : Item_variant := Item_variant'First) is record
      case union_Variant is
         when data8_variant =>
            data8 : aliased swig.int8_t_Array (0 .. 19);
         when data16_variant =>
            data16 : aliased swig.uint16_t_Array (0 .. 9);
         when data32_variant =>
            data32 : aliased swig.uint32_t_Array (0 .. 4);
      end case;
   end record;

   pragma Unchecked_Union (Item);

   -- Item_Array
   --
   type Item_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.xcb_client_message_data_t
       .Item;

   -- Pointer
   --
   package C_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_client_message_data_t.Item,
      Element_Array      => xcb.xcb_client_message_data_t.Item_Array,
      Default_Terminator => (others => <>));

   subtype Pointer is C_Pointers.Pointer;

   -- Pointer_Array
   --
   type Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.xcb_client_message_data_t
       .Pointer;

   -- Pointer_Pointer
   --
   package C_Pointer_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_client_message_data_t.Pointer,
      Element_Array      => xcb.xcb_client_message_data_t.Pointer_Array,
      Default_Terminator => null);

   subtype Pointer_Pointer is C_Pointer_Pointers.Pointer;

end xcb.xcb_client_message_data_t;
