-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces;
with swig;
with xcb.xcb_charinfo_t;
with Interfaces.C;
with Interfaces.C.Pointers;

package xcb.xcb_query_font_reply_t is

   -- Item
   --

   type Item is record
      response_type     : aliased Interfaces.Unsigned_8;
      pad0              : aliased Interfaces.Unsigned_8;
      sequence          : aliased Interfaces.Unsigned_16;
      length            : aliased Interfaces.Unsigned_32;
      min_bounds        : aliased xcb.xcb_charinfo_t.Item;
      pad1              : aliased swig.int8_t_Array (0 .. 3);
      max_bounds        : aliased xcb.xcb_charinfo_t.Item;
      pad2              : aliased swig.int8_t_Array (0 .. 3);
      min_char_or_byte2 : aliased Interfaces.Unsigned_16;
      max_char_or_byte2 : aliased Interfaces.Unsigned_16;
      default_char      : aliased Interfaces.Unsigned_16;
      properties_len    : aliased Interfaces.Unsigned_16;
      draw_direction    : aliased Interfaces.Unsigned_8;
      min_byte1         : aliased Interfaces.Unsigned_8;
      max_byte1         : aliased Interfaces.Unsigned_8;
      all_chars_exist   : aliased Interfaces.Unsigned_8;
      font_ascent       : aliased Interfaces.Integer_16;
      font_descent      : aliased Interfaces.Integer_16;
      char_infos_len    : aliased Interfaces.Unsigned_32;
   end record;

   -- Item_Array
   --
   type Item_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.xcb_query_font_reply_t
       .Item;

   -- Pointer
   --
   package C_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_query_font_reply_t.Item,
      Element_Array      => xcb.xcb_query_font_reply_t.Item_Array,
      Default_Terminator => (others => <>));

   subtype Pointer is C_Pointers.Pointer;

   -- Pointer_Array
   --
   type Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.xcb_query_font_reply_t
       .Pointer;

   -- Pointer_Pointer
   --
   package C_Pointer_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_query_font_reply_t.Pointer,
      Element_Array      => xcb.xcb_query_font_reply_t.Pointer_Array,
      Default_Terminator => null);

   subtype Pointer_Pointer is C_Pointer_Pointers.Pointer;

end xcb.xcb_query_font_reply_t;
