-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces.C;
with Interfaces.C.Pointers;

package xcb.Pointers is

   -- xcb_connection_t_Pointer
   --
   package C_xcb_connection_t_Pointers is new interfaces.c.Pointers
     (Index              => interfaces.c.size_t,
      Element            => xcb.xcb_connection_t,
      element_Array      => xcb.xcb_connection_t_Array,
      default_Terminator => 0);

   subtype xcb_connection_t_Pointer is C_xcb_connection_t_Pointers.Pointer;

   -- xcb_connection_t_Pointer_Array
   --
   type xcb_connection_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_connection_t_Pointer;

   -- xcb_special_event_t_Pointer
   --
   package C_xcb_special_event_t_Pointers is new interfaces.c.Pointers
     (Index              => interfaces.c.size_t,
      Element            => xcb.xcb_special_event_t,
      element_Array      => xcb.xcb_special_event_t_Array,
      default_Terminator => 0);

   subtype xcb_special_event_t_Pointer is
     C_xcb_special_event_t_Pointers.Pointer;

   -- xcb_special_event_t_Pointer_Array
   --
   type xcb_special_event_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_special_event_t_Pointer;

   -- xcb_window_t_Pointer
   --
   package C_xcb_window_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_window_t,
      Element_Array      => xcb.xcb_window_t_array,
      Default_Terminator => 0);

   subtype xcb_window_t_Pointer is C_xcb_window_t_Pointers.Pointer;

   -- xcb_window_t_Pointer_Array
   --
   type xcb_window_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_window_t_Pointer;

   -- xcb_pixmap_t_Pointer
   --
   package C_xcb_pixmap_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_pixmap_t,
      Element_Array      => xcb.xcb_pixmap_t_array,
      Default_Terminator => 0);

   subtype xcb_pixmap_t_Pointer is C_xcb_pixmap_t_Pointers.Pointer;

   -- xcb_pixmap_t_Pointer_Array
   --
   type xcb_pixmap_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_pixmap_t_Pointer;

   -- xcb_cursor_t_Pointer
   --
   package C_xcb_cursor_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_cursor_t,
      Element_Array      => xcb.xcb_cursor_t_array,
      Default_Terminator => 0);

   subtype xcb_cursor_t_Pointer is C_xcb_cursor_t_Pointers.Pointer;

   -- xcb_cursor_t_Pointer_Array
   --
   type xcb_cursor_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_cursor_t_Pointer;

   -- xcb_font_t_Pointer
   --
   package C_xcb_font_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_font_t,
      Element_Array      => xcb.xcb_font_t_array,
      Default_Terminator => 0);

   subtype xcb_font_t_Pointer is C_xcb_font_t_Pointers.Pointer;

   -- xcb_font_t_Pointer_Array
   --
   type xcb_font_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_font_t_Pointer;

   -- xcb_gcontext_t_Pointer
   --
   package C_xcb_gcontext_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_gcontext_t,
      Element_Array      => xcb.xcb_gcontext_t_array,
      Default_Terminator => 0);

   subtype xcb_gcontext_t_Pointer is C_xcb_gcontext_t_Pointers.Pointer;

   -- xcb_gcontext_t_Pointer_Array
   --
   type xcb_gcontext_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_gcontext_t_Pointer;

   -- xcb_colormap_t_Pointer
   --
   package C_xcb_colormap_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_colormap_t,
      Element_Array      => xcb.xcb_colormap_t_array,
      Default_Terminator => 0);

   subtype xcb_colormap_t_Pointer is C_xcb_colormap_t_Pointers.Pointer;

   -- xcb_colormap_t_Pointer_Array
   --
   type xcb_colormap_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_colormap_t_Pointer;

   -- xcb_atom_t_Pointer
   --
   package C_xcb_atom_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_atom_t,
      Element_Array      => xcb.xcb_atom_t_array,
      Default_Terminator => 0);

   subtype xcb_atom_t_Pointer is C_xcb_atom_t_Pointers.Pointer;

   -- xcb_atom_t_Pointer_Array
   --
   type xcb_atom_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_atom_t_Pointer;

   -- xcb_drawable_t_Pointer
   --
   package C_xcb_drawable_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_drawable_t,
      Element_Array      => xcb.xcb_drawable_t_array,
      Default_Terminator => 0);

   subtype xcb_drawable_t_Pointer is C_xcb_drawable_t_Pointers.Pointer;

   -- xcb_drawable_t_Pointer_Array
   --
   type xcb_drawable_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_drawable_t_Pointer;

   -- xcb_fontable_t_Pointer
   --
   package C_xcb_fontable_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_fontable_t,
      Element_Array      => xcb.xcb_fontable_t_array,
      Default_Terminator => 0);

   subtype xcb_fontable_t_Pointer is C_xcb_fontable_t_Pointers.Pointer;

   -- xcb_fontable_t_Pointer_Array
   --
   type xcb_fontable_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_fontable_t_Pointer;

   -- xcb_bool32_t_Pointer
   --
   package C_xcb_bool32_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_bool32_t,
      Element_Array      => xcb.xcb_bool32_t_array,
      Default_Terminator => 0);

   subtype xcb_bool32_t_Pointer is C_xcb_bool32_t_Pointers.Pointer;

   -- xcb_bool32_t_Pointer_Array
   --
   type xcb_bool32_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_bool32_t_Pointer;

   -- xcb_visualid_t_Pointer
   --
   package C_xcb_visualid_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_visualid_t,
      Element_Array      => xcb.xcb_visualid_t_array,
      Default_Terminator => 0);

   subtype xcb_visualid_t_Pointer is C_xcb_visualid_t_Pointers.Pointer;

   -- xcb_visualid_t_Pointer_Array
   --
   type xcb_visualid_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_visualid_t_Pointer;

   -- xcb_timestamp_t_Pointer
   --
   package C_xcb_timestamp_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_timestamp_t,
      Element_Array      => xcb.xcb_timestamp_t_array,
      Default_Terminator => 0);

   subtype xcb_timestamp_t_Pointer is C_xcb_timestamp_t_Pointers.Pointer;

   -- xcb_timestamp_t_Pointer_Array
   --
   type xcb_timestamp_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_timestamp_t_Pointer;

   -- xcb_keysym_t_Pointer
   --
   package C_xcb_keysym_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_keysym_t,
      Element_Array      => xcb.xcb_keysym_t_array,
      Default_Terminator => 0);

   subtype xcb_keysym_t_Pointer is C_xcb_keysym_t_Pointers.Pointer;

   -- xcb_keysym_t_Pointer_Array
   --
   type xcb_keysym_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_keysym_t_Pointer;

   -- xcb_keycode_t_Pointer
   --
   package C_xcb_keycode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_keycode_t,
      Element_Array      => xcb.xcb_keycode_t_array,
      Default_Terminator => 0);

   subtype xcb_keycode_t_Pointer is C_xcb_keycode_t_Pointers.Pointer;

   -- xcb_keycode_t_Pointer_Array
   --
   type xcb_keycode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_keycode_t_Pointer;

   -- xcb_keycode32_t_Pointer
   --
   package C_xcb_keycode32_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_keycode32_t,
      Element_Array      => xcb.xcb_keycode32_t_array,
      Default_Terminator => 0);

   subtype xcb_keycode32_t_Pointer is C_xcb_keycode32_t_Pointers.Pointer;

   -- xcb_keycode32_t_Pointer_Array
   --
   type xcb_keycode32_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_keycode32_t_Pointer;

   -- xcb_button_t_Pointer
   --
   package C_xcb_button_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_button_t,
      Element_Array      => xcb.xcb_button_t_array,
      Default_Terminator => 0);

   subtype xcb_button_t_Pointer is C_xcb_button_t_Pointers.Pointer;

   -- xcb_button_t_Pointer_Array
   --
   type xcb_button_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_button_t_Pointer;

   -- xcb_visual_class_t_Pointer
   --
   package C_xcb_visual_class_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_visual_class_t,
      Element_Array      => xcb.xcb_visual_class_t_array,
      Default_Terminator => xcb.xcb_visual_class_t'Val (0));

   subtype xcb_visual_class_t_Pointer is C_xcb_visual_class_t_Pointers.Pointer;

   -- xcb_visual_class_t_Pointer_Array
   --
   type xcb_visual_class_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_visual_class_t_Pointer;

   -- xcb_event_mask_t_Pointer
   --
   package C_xcb_event_mask_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_event_mask_t,
      Element_Array      => xcb.xcb_event_mask_t_array,
      Default_Terminator => xcb.xcb_event_mask_t'Val (0));

   subtype xcb_event_mask_t_Pointer is C_xcb_event_mask_t_Pointers.Pointer;

   -- xcb_event_mask_t_Pointer_Array
   --
   type xcb_event_mask_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_event_mask_t_Pointer;

   -- xcb_backing_store_t_Pointer
   --
   package C_xcb_backing_store_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_backing_store_t,
      Element_Array      => xcb.xcb_backing_store_t_array,
      Default_Terminator => xcb.xcb_backing_store_t'Val (0));

   subtype xcb_backing_store_t_Pointer is
     C_xcb_backing_store_t_Pointers.Pointer;

   -- xcb_backing_store_t_Pointer_Array
   --
   type xcb_backing_store_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_backing_store_t_Pointer;

   -- xcb_image_order_t_Pointer
   --
   package C_xcb_image_order_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_image_order_t,
      Element_Array      => xcb.xcb_image_order_t_array,
      Default_Terminator => xcb.xcb_image_order_t'Val (0));

   subtype xcb_image_order_t_Pointer is C_xcb_image_order_t_Pointers.Pointer;

   -- xcb_image_order_t_Pointer_Array
   --
   type xcb_image_order_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_image_order_t_Pointer;

   -- xcb_mod_mask_t_Pointer
   --
   package C_xcb_mod_mask_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_mod_mask_t,
      Element_Array      => xcb.xcb_mod_mask_t_array,
      Default_Terminator => xcb.xcb_mod_mask_t'Val (0));

   subtype xcb_mod_mask_t_Pointer is C_xcb_mod_mask_t_Pointers.Pointer;

   -- xcb_mod_mask_t_Pointer_Array
   --
   type xcb_mod_mask_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_mod_mask_t_Pointer;

   -- xcb_key_but_mask_t_Pointer
   --
   package C_xcb_key_but_mask_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_key_but_mask_t,
      Element_Array      => xcb.xcb_key_but_mask_t_array,
      Default_Terminator => xcb.xcb_key_but_mask_t'Val (0));

   subtype xcb_key_but_mask_t_Pointer is C_xcb_key_but_mask_t_Pointers.Pointer;

   -- xcb_key_but_mask_t_Pointer_Array
   --
   type xcb_key_but_mask_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_key_but_mask_t_Pointer;

   -- xcb_window_enum_t_Pointer
   --
   package C_xcb_window_enum_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_window_enum_t,
      Element_Array      => xcb.xcb_window_enum_t_array,
      Default_Terminator => xcb.xcb_window_enum_t'Val (0));

   subtype xcb_window_enum_t_Pointer is C_xcb_window_enum_t_Pointers.Pointer;

   -- xcb_window_enum_t_Pointer_Array
   --
   type xcb_window_enum_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_window_enum_t_Pointer;

   -- xcb_button_mask_t_Pointer
   --
   package C_xcb_button_mask_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_button_mask_t,
      Element_Array      => xcb.xcb_button_mask_t_array,
      Default_Terminator => xcb.xcb_button_mask_t'Val (0));

   subtype xcb_button_mask_t_Pointer is C_xcb_button_mask_t_Pointers.Pointer;

   -- xcb_button_mask_t_Pointer_Array
   --
   type xcb_button_mask_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_button_mask_t_Pointer;

   -- xcb_motion_t_Pointer
   --
   package C_xcb_motion_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_motion_t,
      Element_Array      => xcb.xcb_motion_t_array,
      Default_Terminator => xcb.xcb_motion_t'Val (0));

   subtype xcb_motion_t_Pointer is C_xcb_motion_t_Pointers.Pointer;

   -- xcb_motion_t_Pointer_Array
   --
   type xcb_motion_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_motion_t_Pointer;

   -- xcb_notify_detail_t_Pointer
   --
   package C_xcb_notify_detail_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_notify_detail_t,
      Element_Array      => xcb.xcb_notify_detail_t_array,
      Default_Terminator => xcb.xcb_notify_detail_t'Val (0));

   subtype xcb_notify_detail_t_Pointer is
     C_xcb_notify_detail_t_Pointers.Pointer;

   -- xcb_notify_detail_t_Pointer_Array
   --
   type xcb_notify_detail_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_notify_detail_t_Pointer;

   -- xcb_notify_mode_t_Pointer
   --
   package C_xcb_notify_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_notify_mode_t,
      Element_Array      => xcb.xcb_notify_mode_t_array,
      Default_Terminator => xcb.xcb_notify_mode_t'Val (0));

   subtype xcb_notify_mode_t_Pointer is C_xcb_notify_mode_t_Pointers.Pointer;

   -- xcb_notify_mode_t_Pointer_Array
   --
   type xcb_notify_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_notify_mode_t_Pointer;

   -- xcb_visibility_t_Pointer
   --
   package C_xcb_visibility_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_visibility_t,
      Element_Array      => xcb.xcb_visibility_t_array,
      Default_Terminator => xcb.xcb_visibility_t'Val (0));

   subtype xcb_visibility_t_Pointer is C_xcb_visibility_t_Pointers.Pointer;

   -- xcb_visibility_t_Pointer_Array
   --
   type xcb_visibility_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_visibility_t_Pointer;

   -- xcb_place_t_Pointer
   --
   package C_xcb_place_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_place_t,
      Element_Array      => xcb.xcb_place_t_array,
      Default_Terminator => xcb.xcb_place_t'Val (0));

   subtype xcb_place_t_Pointer is C_xcb_place_t_Pointers.Pointer;

   -- xcb_place_t_Pointer_Array
   --
   type xcb_place_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_place_t_Pointer;

   -- xcb_property_t_Pointer
   --
   package C_xcb_property_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_property_t,
      Element_Array      => xcb.xcb_property_t_array,
      Default_Terminator => xcb.xcb_property_t'Val (0));

   subtype xcb_property_t_Pointer is C_xcb_property_t_Pointers.Pointer;

   -- xcb_property_t_Pointer_Array
   --
   type xcb_property_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_property_t_Pointer;

   -- xcb_time_t_Pointer
   --
   package C_xcb_time_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_time_t,
      Element_Array      => xcb.xcb_time_t_array,
      Default_Terminator => xcb.xcb_time_t'Val (0));

   subtype xcb_time_t_Pointer is C_xcb_time_t_Pointers.Pointer;

   -- xcb_time_t_Pointer_Array
   --
   type xcb_time_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_time_t_Pointer;

   -- xcb_atom_enum_t_Pointer
   --
   package C_xcb_atom_enum_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_atom_enum_t,
      Element_Array      => xcb.xcb_atom_enum_t_array,
      Default_Terminator => xcb.xcb_atom_enum_t'Val (0));

   subtype xcb_atom_enum_t_Pointer is C_xcb_atom_enum_t_Pointers.Pointer;

   -- xcb_atom_enum_t_Pointer_Array
   --
   type xcb_atom_enum_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_atom_enum_t_Pointer;

   -- xcb_colormap_state_t_Pointer
   --
   package C_xcb_colormap_state_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_colormap_state_t,
      Element_Array      => xcb.xcb_colormap_state_t_array,
      Default_Terminator => xcb.xcb_colormap_state_t'Val (0));

   subtype xcb_colormap_state_t_Pointer is
     C_xcb_colormap_state_t_Pointers.Pointer;

   -- xcb_colormap_state_t_Pointer_Array
   --
   type xcb_colormap_state_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_colormap_state_t_Pointer;

   -- xcb_colormap_enum_t_Pointer
   --
   package C_xcb_colormap_enum_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_colormap_enum_t,
      Element_Array      => xcb.xcb_colormap_enum_t_array,
      Default_Terminator => xcb.xcb_colormap_enum_t'Val (0));

   subtype xcb_colormap_enum_t_Pointer is
     C_xcb_colormap_enum_t_Pointers.Pointer;

   -- xcb_colormap_enum_t_Pointer_Array
   --
   type xcb_colormap_enum_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_colormap_enum_t_Pointer;

   -- xcb_mapping_t_Pointer
   --
   package C_xcb_mapping_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_mapping_t,
      Element_Array      => xcb.xcb_mapping_t_array,
      Default_Terminator => xcb.xcb_mapping_t'Val (0));

   subtype xcb_mapping_t_Pointer is C_xcb_mapping_t_Pointers.Pointer;

   -- xcb_mapping_t_Pointer_Array
   --
   type xcb_mapping_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_mapping_t_Pointer;

   -- xcb_window_class_t_Pointer
   --
   package C_xcb_window_class_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_window_class_t,
      Element_Array      => xcb.xcb_window_class_t_array,
      Default_Terminator => xcb.xcb_window_class_t'Val (0));

   subtype xcb_window_class_t_Pointer is C_xcb_window_class_t_Pointers.Pointer;

   -- xcb_window_class_t_Pointer_Array
   --
   type xcb_window_class_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_window_class_t_Pointer;

   -- xcb_cw_t_Pointer
   --
   package C_xcb_cw_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_cw_t,
      Element_Array      => xcb.xcb_cw_t_array,
      Default_Terminator => xcb.xcb_cw_t'Val (0));

   subtype xcb_cw_t_Pointer is C_xcb_cw_t_Pointers.Pointer;

   -- xcb_cw_t_Pointer_Array
   --
   type xcb_cw_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers.xcb_cw_t_Pointer;

   -- xcb_back_pixmap_t_Pointer
   --
   package C_xcb_back_pixmap_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_back_pixmap_t,
      Element_Array      => xcb.xcb_back_pixmap_t_array,
      Default_Terminator => xcb.xcb_back_pixmap_t'Val (0));

   subtype xcb_back_pixmap_t_Pointer is C_xcb_back_pixmap_t_Pointers.Pointer;

   -- xcb_back_pixmap_t_Pointer_Array
   --
   type xcb_back_pixmap_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_back_pixmap_t_Pointer;

   -- xcb_gravity_t_Pointer
   --
   package C_xcb_gravity_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_gravity_t,
      Element_Array      => xcb.xcb_gravity_t_array,
      Default_Terminator => xcb.xcb_gravity_t'Val (0));

   subtype xcb_gravity_t_Pointer is C_xcb_gravity_t_Pointers.Pointer;

   -- xcb_gravity_t_Pointer_Array
   --
   type xcb_gravity_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_gravity_t_Pointer;

   -- xcb_map_state_t_Pointer
   --
   package C_xcb_map_state_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_map_state_t,
      Element_Array      => xcb.xcb_map_state_t_array,
      Default_Terminator => xcb.xcb_map_state_t'Val (0));

   subtype xcb_map_state_t_Pointer is C_xcb_map_state_t_Pointers.Pointer;

   -- xcb_map_state_t_Pointer_Array
   --
   type xcb_map_state_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_map_state_t_Pointer;

   -- xcb_set_mode_t_Pointer
   --
   package C_xcb_set_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_set_mode_t,
      Element_Array      => xcb.xcb_set_mode_t_array,
      Default_Terminator => xcb.xcb_set_mode_t'Val (0));

   subtype xcb_set_mode_t_Pointer is C_xcb_set_mode_t_Pointers.Pointer;

   -- xcb_set_mode_t_Pointer_Array
   --
   type xcb_set_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_set_mode_t_Pointer;

   -- xcb_config_window_t_Pointer
   --
   package C_xcb_config_window_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_config_window_t,
      Element_Array      => xcb.xcb_config_window_t_array,
      Default_Terminator => xcb.xcb_config_window_t'Val (0));

   subtype xcb_config_window_t_Pointer is
     C_xcb_config_window_t_Pointers.Pointer;

   -- xcb_config_window_t_Pointer_Array
   --
   type xcb_config_window_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_config_window_t_Pointer;

   -- xcb_stack_mode_t_Pointer
   --
   package C_xcb_stack_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_stack_mode_t,
      Element_Array      => xcb.xcb_stack_mode_t_array,
      Default_Terminator => xcb.xcb_stack_mode_t'Val (0));

   subtype xcb_stack_mode_t_Pointer is C_xcb_stack_mode_t_Pointers.Pointer;

   -- xcb_stack_mode_t_Pointer_Array
   --
   type xcb_stack_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_stack_mode_t_Pointer;

   -- xcb_circulate_t_Pointer
   --
   package C_xcb_circulate_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_circulate_t,
      Element_Array      => xcb.xcb_circulate_t_array,
      Default_Terminator => xcb.xcb_circulate_t'Val (0));

   subtype xcb_circulate_t_Pointer is C_xcb_circulate_t_Pointers.Pointer;

   -- xcb_circulate_t_Pointer_Array
   --
   type xcb_circulate_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_circulate_t_Pointer;

   -- xcb_prop_mode_t_Pointer
   --
   package C_xcb_prop_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_prop_mode_t,
      Element_Array      => xcb.xcb_prop_mode_t_array,
      Default_Terminator => xcb.xcb_prop_mode_t'Val (0));

   subtype xcb_prop_mode_t_Pointer is C_xcb_prop_mode_t_Pointers.Pointer;

   -- xcb_prop_mode_t_Pointer_Array
   --
   type xcb_prop_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_prop_mode_t_Pointer;

   -- xcb_get_property_type_t_Pointer
   --
   package C_xcb_get_property_type_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_get_property_type_t,
      Element_Array      => xcb.xcb_get_property_type_t_array,
      Default_Terminator => xcb.xcb_get_property_type_t'Val (0));

   subtype xcb_get_property_type_t_Pointer is
     C_xcb_get_property_type_t_Pointers.Pointer;

   -- xcb_get_property_type_t_Pointer_Array
   --
   type xcb_get_property_type_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_get_property_type_t_Pointer;

   -- xcb_send_event_dest_t_Pointer
   --
   package C_xcb_send_event_dest_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_send_event_dest_t,
      Element_Array      => xcb.xcb_send_event_dest_t_array,
      Default_Terminator => xcb.xcb_send_event_dest_t'Val (0));

   subtype xcb_send_event_dest_t_Pointer is
     C_xcb_send_event_dest_t_Pointers.Pointer;

   -- xcb_send_event_dest_t_Pointer_Array
   --
   type xcb_send_event_dest_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_send_event_dest_t_Pointer;

   -- xcb_grab_mode_t_Pointer
   --
   package C_xcb_grab_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_grab_mode_t,
      Element_Array      => xcb.xcb_grab_mode_t_array,
      Default_Terminator => xcb.xcb_grab_mode_t'Val (0));

   subtype xcb_grab_mode_t_Pointer is C_xcb_grab_mode_t_Pointers.Pointer;

   -- xcb_grab_mode_t_Pointer_Array
   --
   type xcb_grab_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_grab_mode_t_Pointer;

   -- xcb_grab_status_t_Pointer
   --
   package C_xcb_grab_status_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_grab_status_t,
      Element_Array      => xcb.xcb_grab_status_t_array,
      Default_Terminator => xcb.xcb_grab_status_t'Val (0));

   subtype xcb_grab_status_t_Pointer is C_xcb_grab_status_t_Pointers.Pointer;

   -- xcb_grab_status_t_Pointer_Array
   --
   type xcb_grab_status_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_grab_status_t_Pointer;

   -- xcb_cursor_enum_t_Pointer
   --
   package C_xcb_cursor_enum_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_cursor_enum_t,
      Element_Array      => xcb.xcb_cursor_enum_t_array,
      Default_Terminator => xcb.xcb_cursor_enum_t'Val (0));

   subtype xcb_cursor_enum_t_Pointer is C_xcb_cursor_enum_t_Pointers.Pointer;

   -- xcb_cursor_enum_t_Pointer_Array
   --
   type xcb_cursor_enum_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_cursor_enum_t_Pointer;

   -- xcb_button_index_t_Pointer
   --
   package C_xcb_button_index_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_button_index_t,
      Element_Array      => xcb.xcb_button_index_t_array,
      Default_Terminator => xcb.xcb_button_index_t'Val (0));

   subtype xcb_button_index_t_Pointer is C_xcb_button_index_t_Pointers.Pointer;

   -- xcb_button_index_t_Pointer_Array
   --
   type xcb_button_index_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_button_index_t_Pointer;

   -- xcb_grab_t_Pointer
   --
   package C_xcb_grab_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_grab_t,
      Element_Array      => xcb.xcb_grab_t_array,
      Default_Terminator => xcb.xcb_grab_t'Val (0));

   subtype xcb_grab_t_Pointer is C_xcb_grab_t_Pointers.Pointer;

   -- xcb_grab_t_Pointer_Array
   --
   type xcb_grab_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_grab_t_Pointer;

   -- xcb_allow_t_Pointer
   --
   package C_xcb_allow_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_allow_t,
      Element_Array      => xcb.xcb_allow_t_array,
      Default_Terminator => xcb.xcb_allow_t'Val (0));

   subtype xcb_allow_t_Pointer is C_xcb_allow_t_Pointers.Pointer;

   -- xcb_allow_t_Pointer_Array
   --
   type xcb_allow_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_allow_t_Pointer;

   -- xcb_input_focus_t_Pointer
   --
   package C_xcb_input_focus_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_input_focus_t,
      Element_Array      => xcb.xcb_input_focus_t_array,
      Default_Terminator => xcb.xcb_input_focus_t'Val (0));

   subtype xcb_input_focus_t_Pointer is C_xcb_input_focus_t_Pointers.Pointer;

   -- xcb_input_focus_t_Pointer_Array
   --
   type xcb_input_focus_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_input_focus_t_Pointer;

   -- xcb_font_draw_t_Pointer
   --
   package C_xcb_font_draw_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_font_draw_t,
      Element_Array      => xcb.xcb_font_draw_t_array,
      Default_Terminator => xcb.xcb_font_draw_t'Val (0));

   subtype xcb_font_draw_t_Pointer is C_xcb_font_draw_t_Pointers.Pointer;

   -- xcb_font_draw_t_Pointer_Array
   --
   type xcb_font_draw_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_font_draw_t_Pointer;

   -- xcb_gc_t_Pointer
   --
   package C_xcb_gc_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_gc_t,
      Element_Array      => xcb.xcb_gc_t_array,
      Default_Terminator => xcb.xcb_gc_t'Val (0));

   subtype xcb_gc_t_Pointer is C_xcb_gc_t_Pointers.Pointer;

   -- xcb_gc_t_Pointer_Array
   --
   type xcb_gc_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers.xcb_gc_t_Pointer;

   -- xcb_gx_t_Pointer
   --
   package C_xcb_gx_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_gx_t,
      Element_Array      => xcb.xcb_gx_t_array,
      Default_Terminator => xcb.xcb_gx_t'Val (0));

   subtype xcb_gx_t_Pointer is C_xcb_gx_t_Pointers.Pointer;

   -- xcb_gx_t_Pointer_Array
   --
   type xcb_gx_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers.xcb_gx_t_Pointer;

   -- xcb_line_style_t_Pointer
   --
   package C_xcb_line_style_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_line_style_t,
      Element_Array      => xcb.xcb_line_style_t_array,
      Default_Terminator => xcb.xcb_line_style_t'Val (0));

   subtype xcb_line_style_t_Pointer is C_xcb_line_style_t_Pointers.Pointer;

   -- xcb_line_style_t_Pointer_Array
   --
   type xcb_line_style_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_line_style_t_Pointer;

   -- xcb_cap_style_t_Pointer
   --
   package C_xcb_cap_style_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_cap_style_t,
      Element_Array      => xcb.xcb_cap_style_t_array,
      Default_Terminator => xcb.xcb_cap_style_t'Val (0));

   subtype xcb_cap_style_t_Pointer is C_xcb_cap_style_t_Pointers.Pointer;

   -- xcb_cap_style_t_Pointer_Array
   --
   type xcb_cap_style_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_cap_style_t_Pointer;

   -- xcb_join_style_t_Pointer
   --
   package C_xcb_join_style_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_join_style_t,
      Element_Array      => xcb.xcb_join_style_t_array,
      Default_Terminator => xcb.xcb_join_style_t'Val (0));

   subtype xcb_join_style_t_Pointer is C_xcb_join_style_t_Pointers.Pointer;

   -- xcb_join_style_t_Pointer_Array
   --
   type xcb_join_style_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_join_style_t_Pointer;

   -- xcb_fill_style_t_Pointer
   --
   package C_xcb_fill_style_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_fill_style_t,
      Element_Array      => xcb.xcb_fill_style_t_array,
      Default_Terminator => xcb.xcb_fill_style_t'Val (0));

   subtype xcb_fill_style_t_Pointer is C_xcb_fill_style_t_Pointers.Pointer;

   -- xcb_fill_style_t_Pointer_Array
   --
   type xcb_fill_style_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_fill_style_t_Pointer;

   -- xcb_fill_rule_t_Pointer
   --
   package C_xcb_fill_rule_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_fill_rule_t,
      Element_Array      => xcb.xcb_fill_rule_t_array,
      Default_Terminator => xcb.xcb_fill_rule_t'Val (0));

   subtype xcb_fill_rule_t_Pointer is C_xcb_fill_rule_t_Pointers.Pointer;

   -- xcb_fill_rule_t_Pointer_Array
   --
   type xcb_fill_rule_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_fill_rule_t_Pointer;

   -- xcb_subwindow_mode_t_Pointer
   --
   package C_xcb_subwindow_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_subwindow_mode_t,
      Element_Array      => xcb.xcb_subwindow_mode_t_array,
      Default_Terminator => xcb.xcb_subwindow_mode_t'Val (0));

   subtype xcb_subwindow_mode_t_Pointer is
     C_xcb_subwindow_mode_t_Pointers.Pointer;

   -- xcb_subwindow_mode_t_Pointer_Array
   --
   type xcb_subwindow_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_subwindow_mode_t_Pointer;

   -- xcb_arc_mode_t_Pointer
   --
   package C_xcb_arc_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_arc_mode_t,
      Element_Array      => xcb.xcb_arc_mode_t_array,
      Default_Terminator => xcb.xcb_arc_mode_t'Val (0));

   subtype xcb_arc_mode_t_Pointer is C_xcb_arc_mode_t_Pointers.Pointer;

   -- xcb_arc_mode_t_Pointer_Array
   --
   type xcb_arc_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_arc_mode_t_Pointer;

   -- xcb_clip_ordering_t_Pointer
   --
   package C_xcb_clip_ordering_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_clip_ordering_t,
      Element_Array      => xcb.xcb_clip_ordering_t_array,
      Default_Terminator => xcb.xcb_clip_ordering_t'Val (0));

   subtype xcb_clip_ordering_t_Pointer is
     C_xcb_clip_ordering_t_Pointers.Pointer;

   -- xcb_clip_ordering_t_Pointer_Array
   --
   type xcb_clip_ordering_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_clip_ordering_t_Pointer;

   -- xcb_coord_mode_t_Pointer
   --
   package C_xcb_coord_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_coord_mode_t,
      Element_Array      => xcb.xcb_coord_mode_t_array,
      Default_Terminator => xcb.xcb_coord_mode_t'Val (0));

   subtype xcb_coord_mode_t_Pointer is C_xcb_coord_mode_t_Pointers.Pointer;

   -- xcb_coord_mode_t_Pointer_Array
   --
   type xcb_coord_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_coord_mode_t_Pointer;

   -- xcb_poly_shape_t_Pointer
   --
   package C_xcb_poly_shape_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_poly_shape_t,
      Element_Array      => xcb.xcb_poly_shape_t_array,
      Default_Terminator => xcb.xcb_poly_shape_t'Val (0));

   subtype xcb_poly_shape_t_Pointer is C_xcb_poly_shape_t_Pointers.Pointer;

   -- xcb_poly_shape_t_Pointer_Array
   --
   type xcb_poly_shape_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_poly_shape_t_Pointer;

   -- xcb_image_format_t_Pointer
   --
   package C_xcb_image_format_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_image_format_t,
      Element_Array      => xcb.xcb_image_format_t_array,
      Default_Terminator => xcb.xcb_image_format_t'Val (0));

   subtype xcb_image_format_t_Pointer is C_xcb_image_format_t_Pointers.Pointer;

   -- xcb_image_format_t_Pointer_Array
   --
   type xcb_image_format_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_image_format_t_Pointer;

   -- xcb_colormap_alloc_t_Pointer
   --
   package C_xcb_colormap_alloc_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_colormap_alloc_t,
      Element_Array      => xcb.xcb_colormap_alloc_t_array,
      Default_Terminator => xcb.xcb_colormap_alloc_t'Val (0));

   subtype xcb_colormap_alloc_t_Pointer is
     C_xcb_colormap_alloc_t_Pointers.Pointer;

   -- xcb_colormap_alloc_t_Pointer_Array
   --
   type xcb_colormap_alloc_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_colormap_alloc_t_Pointer;

   -- xcb_color_flag_t_Pointer
   --
   package C_xcb_color_flag_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_color_flag_t,
      Element_Array      => xcb.xcb_color_flag_t_array,
      Default_Terminator => xcb.xcb_color_flag_t'Val (0));

   subtype xcb_color_flag_t_Pointer is C_xcb_color_flag_t_Pointers.Pointer;

   -- xcb_color_flag_t_Pointer_Array
   --
   type xcb_color_flag_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_color_flag_t_Pointer;

   -- xcb_pixmap_enum_t_Pointer
   --
   package C_xcb_pixmap_enum_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_pixmap_enum_t,
      Element_Array      => xcb.xcb_pixmap_enum_t_array,
      Default_Terminator => xcb.xcb_pixmap_enum_t'Val (0));

   subtype xcb_pixmap_enum_t_Pointer is C_xcb_pixmap_enum_t_Pointers.Pointer;

   -- xcb_pixmap_enum_t_Pointer_Array
   --
   type xcb_pixmap_enum_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_pixmap_enum_t_Pointer;

   -- xcb_font_enum_t_Pointer
   --
   package C_xcb_font_enum_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_font_enum_t,
      Element_Array      => xcb.xcb_font_enum_t_array,
      Default_Terminator => xcb.xcb_font_enum_t'Val (0));

   subtype xcb_font_enum_t_Pointer is C_xcb_font_enum_t_Pointers.Pointer;

   -- xcb_font_enum_t_Pointer_Array
   --
   type xcb_font_enum_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_font_enum_t_Pointer;

   -- xcb_query_shape_of_t_Pointer
   --
   package C_xcb_query_shape_of_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_query_shape_of_t,
      Element_Array      => xcb.xcb_query_shape_of_t_array,
      Default_Terminator => xcb.xcb_query_shape_of_t'Val (0));

   subtype xcb_query_shape_of_t_Pointer is
     C_xcb_query_shape_of_t_Pointers.Pointer;

   -- xcb_query_shape_of_t_Pointer_Array
   --
   type xcb_query_shape_of_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_query_shape_of_t_Pointer;

   -- xcb_kb_t_Pointer
   --
   package C_xcb_kb_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_kb_t,
      Element_Array      => xcb.xcb_kb_t_array,
      Default_Terminator => xcb.xcb_kb_t'Val (0));

   subtype xcb_kb_t_Pointer is C_xcb_kb_t_Pointers.Pointer;

   -- xcb_kb_t_Pointer_Array
   --
   type xcb_kb_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers.xcb_kb_t_Pointer;

   -- xcb_led_mode_t_Pointer
   --
   package C_xcb_led_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_led_mode_t,
      Element_Array      => xcb.xcb_led_mode_t_array,
      Default_Terminator => xcb.xcb_led_mode_t'Val (0));

   subtype xcb_led_mode_t_Pointer is C_xcb_led_mode_t_Pointers.Pointer;

   -- xcb_led_mode_t_Pointer_Array
   --
   type xcb_led_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_led_mode_t_Pointer;

   -- xcb_auto_repeat_mode_t_Pointer
   --
   package C_xcb_auto_repeat_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_auto_repeat_mode_t,
      Element_Array      => xcb.xcb_auto_repeat_mode_t_array,
      Default_Terminator => xcb.xcb_auto_repeat_mode_t'Val (0));

   subtype xcb_auto_repeat_mode_t_Pointer is
     C_xcb_auto_repeat_mode_t_Pointers.Pointer;

   -- xcb_auto_repeat_mode_t_Pointer_Array
   --
   type xcb_auto_repeat_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_auto_repeat_mode_t_Pointer;

   -- xcb_blanking_t_Pointer
   --
   package C_xcb_blanking_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_blanking_t,
      Element_Array      => xcb.xcb_blanking_t_array,
      Default_Terminator => xcb.xcb_blanking_t'Val (0));

   subtype xcb_blanking_t_Pointer is C_xcb_blanking_t_Pointers.Pointer;

   -- xcb_blanking_t_Pointer_Array
   --
   type xcb_blanking_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_blanking_t_Pointer;

   -- xcb_exposures_t_Pointer
   --
   package C_xcb_exposures_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_exposures_t,
      Element_Array      => xcb.xcb_exposures_t_array,
      Default_Terminator => xcb.xcb_exposures_t'Val (0));

   subtype xcb_exposures_t_Pointer is C_xcb_exposures_t_Pointers.Pointer;

   -- xcb_exposures_t_Pointer_Array
   --
   type xcb_exposures_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_exposures_t_Pointer;

   -- xcb_host_mode_t_Pointer
   --
   package C_xcb_host_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_host_mode_t,
      Element_Array      => xcb.xcb_host_mode_t_array,
      Default_Terminator => xcb.xcb_host_mode_t'Val (0));

   subtype xcb_host_mode_t_Pointer is C_xcb_host_mode_t_Pointers.Pointer;

   -- xcb_host_mode_t_Pointer_Array
   --
   type xcb_host_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_host_mode_t_Pointer;

   -- xcb_family_t_Pointer
   --
   package C_xcb_family_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_family_t,
      Element_Array      => xcb.xcb_family_t_array,
      Default_Terminator => xcb.xcb_family_t'Val (0));

   subtype xcb_family_t_Pointer is C_xcb_family_t_Pointers.Pointer;

   -- xcb_family_t_Pointer_Array
   --
   type xcb_family_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_family_t_Pointer;

   -- xcb_access_control_t_Pointer
   --
   package C_xcb_access_control_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_access_control_t,
      Element_Array      => xcb.xcb_access_control_t_array,
      Default_Terminator => xcb.xcb_access_control_t'Val (0));

   subtype xcb_access_control_t_Pointer is
     C_xcb_access_control_t_Pointers.Pointer;

   -- xcb_access_control_t_Pointer_Array
   --
   type xcb_access_control_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_access_control_t_Pointer;

   -- xcb_close_down_t_Pointer
   --
   package C_xcb_close_down_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_close_down_t,
      Element_Array      => xcb.xcb_close_down_t_array,
      Default_Terminator => xcb.xcb_close_down_t'Val (0));

   subtype xcb_close_down_t_Pointer is C_xcb_close_down_t_Pointers.Pointer;

   -- xcb_close_down_t_Pointer_Array
   --
   type xcb_close_down_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_close_down_t_Pointer;

   -- xcb_kill_t_Pointer
   --
   package C_xcb_kill_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_kill_t,
      Element_Array      => xcb.xcb_kill_t_array,
      Default_Terminator => xcb.xcb_kill_t'Val (0));

   subtype xcb_kill_t_Pointer is C_xcb_kill_t_Pointers.Pointer;

   -- xcb_kill_t_Pointer_Array
   --
   type xcb_kill_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_kill_t_Pointer;

   -- xcb_screen_saver_t_Pointer
   --
   package C_xcb_screen_saver_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_screen_saver_t,
      Element_Array      => xcb.xcb_screen_saver_t_array,
      Default_Terminator => xcb.xcb_screen_saver_t'Val (0));

   subtype xcb_screen_saver_t_Pointer is C_xcb_screen_saver_t_Pointers.Pointer;

   -- xcb_screen_saver_t_Pointer_Array
   --
   type xcb_screen_saver_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_screen_saver_t_Pointer;

   -- xcb_mapping_status_t_Pointer
   --
   package C_xcb_mapping_status_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_mapping_status_t,
      Element_Array      => xcb.xcb_mapping_status_t_array,
      Default_Terminator => xcb.xcb_mapping_status_t'Val (0));

   subtype xcb_mapping_status_t_Pointer is
     C_xcb_mapping_status_t_Pointers.Pointer;

   -- xcb_mapping_status_t_Pointer_Array
   --
   type xcb_mapping_status_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_mapping_status_t_Pointer;

   -- xcb_map_index_t_Pointer
   --
   package C_xcb_map_index_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_map_index_t,
      Element_Array      => xcb.xcb_map_index_t_array,
      Default_Terminator => xcb.xcb_map_index_t'Val (0));

   subtype xcb_map_index_t_Pointer is C_xcb_map_index_t_Pointers.Pointer;

   -- xcb_map_index_t_Pointer_Array
   --
   type xcb_map_index_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_map_index_t_Pointer;

   -- xcb_render_pict_type_t_Pointer
   --
   package C_xcb_render_pict_type_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_pict_type_t,
      Element_Array      => xcb.xcb_render_pict_type_t_array,
      Default_Terminator => xcb.xcb_render_pict_type_t'Val (0));

   subtype xcb_render_pict_type_t_Pointer is
     C_xcb_render_pict_type_t_Pointers.Pointer;

   -- xcb_render_pict_type_t_Pointer_Array
   --
   type xcb_render_pict_type_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_pict_type_t_Pointer;

   -- xcb_render_picture_enum_t_Pointer
   --
   package C_xcb_render_picture_enum_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_picture_enum_t,
      Element_Array      => xcb.xcb_render_picture_enum_t_array,
      Default_Terminator => xcb.xcb_render_picture_enum_t'Val (0));

   subtype xcb_render_picture_enum_t_Pointer is
     C_xcb_render_picture_enum_t_Pointers.Pointer;

   -- xcb_render_picture_enum_t_Pointer_Array
   --
   type xcb_render_picture_enum_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_picture_enum_t_Pointer;

   -- xcb_render_pict_op_t_Pointer
   --
   package C_xcb_render_pict_op_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_pict_op_t,
      Element_Array      => xcb.xcb_render_pict_op_t_array,
      Default_Terminator => xcb.xcb_render_pict_op_t'Val (0));

   subtype xcb_render_pict_op_t_Pointer is
     C_xcb_render_pict_op_t_Pointers.Pointer;

   -- xcb_render_pict_op_t_Pointer_Array
   --
   type xcb_render_pict_op_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_pict_op_t_Pointer;

   -- xcb_render_poly_edge_t_Pointer
   --
   package C_xcb_render_poly_edge_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_poly_edge_t,
      Element_Array      => xcb.xcb_render_poly_edge_t_array,
      Default_Terminator => xcb.xcb_render_poly_edge_t'Val (0));

   subtype xcb_render_poly_edge_t_Pointer is
     C_xcb_render_poly_edge_t_Pointers.Pointer;

   -- xcb_render_poly_edge_t_Pointer_Array
   --
   type xcb_render_poly_edge_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_poly_edge_t_Pointer;

   -- xcb_render_poly_mode_t_Pointer
   --
   package C_xcb_render_poly_mode_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_poly_mode_t,
      Element_Array      => xcb.xcb_render_poly_mode_t_array,
      Default_Terminator => xcb.xcb_render_poly_mode_t'Val (0));

   subtype xcb_render_poly_mode_t_Pointer is
     C_xcb_render_poly_mode_t_Pointers.Pointer;

   -- xcb_render_poly_mode_t_Pointer_Array
   --
   type xcb_render_poly_mode_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_poly_mode_t_Pointer;

   -- xcb_render_cp_t_Pointer
   --
   package C_xcb_render_cp_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_cp_t,
      Element_Array      => xcb.xcb_render_cp_t_array,
      Default_Terminator => xcb.xcb_render_cp_t'Val (0));

   subtype xcb_render_cp_t_Pointer is C_xcb_render_cp_t_Pointers.Pointer;

   -- xcb_render_cp_t_Pointer_Array
   --
   type xcb_render_cp_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_cp_t_Pointer;

   -- xcb_render_sub_pixel_t_Pointer
   --
   package C_xcb_render_sub_pixel_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_sub_pixel_t,
      Element_Array      => xcb.xcb_render_sub_pixel_t_array,
      Default_Terminator => xcb.xcb_render_sub_pixel_t'Val (0));

   subtype xcb_render_sub_pixel_t_Pointer is
     C_xcb_render_sub_pixel_t_Pointers.Pointer;

   -- xcb_render_sub_pixel_t_Pointer_Array
   --
   type xcb_render_sub_pixel_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_sub_pixel_t_Pointer;

   -- xcb_render_repeat_t_Pointer
   --
   package C_xcb_render_repeat_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_repeat_t,
      Element_Array      => xcb.xcb_render_repeat_t_array,
      Default_Terminator => xcb.xcb_render_repeat_t'Val (0));

   subtype xcb_render_repeat_t_Pointer is
     C_xcb_render_repeat_t_Pointers.Pointer;

   -- xcb_render_repeat_t_Pointer_Array
   --
   type xcb_render_repeat_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_repeat_t_Pointer;

   -- xcb_render_glyph_t_Pointer
   --
   package C_xcb_render_glyph_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_glyph_t,
      Element_Array      => xcb.xcb_render_glyph_t_array,
      Default_Terminator => 0);

   subtype xcb_render_glyph_t_Pointer is C_xcb_render_glyph_t_Pointers.Pointer;

   -- xcb_render_glyph_t_Pointer_Array
   --
   type xcb_render_glyph_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_glyph_t_Pointer;

   -- xcb_render_glyphset_t_Pointer
   --
   package C_xcb_render_glyphset_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_glyphset_t,
      Element_Array      => xcb.xcb_render_glyphset_t_array,
      Default_Terminator => 0);

   subtype xcb_render_glyphset_t_Pointer is
     C_xcb_render_glyphset_t_Pointers.Pointer;

   -- xcb_render_glyphset_t_Pointer_Array
   --
   type xcb_render_glyphset_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_glyphset_t_Pointer;

   -- xcb_render_picture_t_Pointer
   --
   package C_xcb_render_picture_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_picture_t,
      Element_Array      => xcb.xcb_render_picture_t_array,
      Default_Terminator => 0);

   subtype xcb_render_picture_t_Pointer is
     C_xcb_render_picture_t_Pointers.Pointer;

   -- xcb_render_picture_t_Pointer_Array
   --
   type xcb_render_picture_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_picture_t_Pointer;

   -- xcb_render_pictformat_t_Pointer
   --
   package C_xcb_render_pictformat_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_pictformat_t,
      Element_Array      => xcb.xcb_render_pictformat_t_array,
      Default_Terminator => 0);

   subtype xcb_render_pictformat_t_Pointer is
     C_xcb_render_pictformat_t_Pointers.Pointer;

   -- xcb_render_pictformat_t_Pointer_Array
   --
   type xcb_render_pictformat_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_pictformat_t_Pointer;

   -- xcb_render_fixed_t_Pointer
   --
   package C_xcb_render_fixed_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_fixed_t,
      Element_Array      => xcb.xcb_render_fixed_t_array,
      Default_Terminator => 0);

   subtype xcb_render_fixed_t_Pointer is C_xcb_render_fixed_t_Pointers.Pointer;

   -- xcb_render_fixed_t_Pointer_Array
   --
   type xcb_render_fixed_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_fixed_t_Pointer;

   -- iovec_Pointer
   --
   package C_iovec_Pointers is new interfaces.c.Pointers
     (Index              => interfaces.c.size_t,
      Element            => xcb.iovec,
      element_Array      => xcb.iovec_Array,
      default_Terminator => 0);

   subtype iovec_Pointer is C_iovec_Pointers.Pointer;

   -- iovec_Pointer_Array
   --
   type iovec_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers.iovec_Pointer;

   -- xcb_send_request_flags_t_Pointer
   --
   package C_xcb_send_request_flags_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_send_request_flags_t,
      Element_Array      => xcb.xcb_send_request_flags_t_array,
      Default_Terminator => xcb.xcb_send_request_flags_t'Val (0));

   subtype xcb_send_request_flags_t_Pointer is
     C_xcb_send_request_flags_t_Pointers.Pointer;

   -- xcb_send_request_flags_t_Pointer_Array
   --
   type xcb_send_request_flags_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_send_request_flags_t_Pointer;

   -- xcb_pict_format_t_Pointer
   --
   package C_xcb_pict_format_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_pict_format_t,
      Element_Array      => xcb.xcb_pict_format_t_array,
      Default_Terminator => xcb.xcb_pict_format_t'Val (0));

   subtype xcb_pict_format_t_Pointer is C_xcb_pict_format_t_Pointers.Pointer;

   -- xcb_pict_format_t_Pointer_Array
   --
   type xcb_pict_format_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_pict_format_t_Pointer;

   -- xcb_pict_standard_t_Pointer
   --
   package C_xcb_pict_standard_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_pict_standard_t,
      Element_Array      => xcb.xcb_pict_standard_t_array,
      Default_Terminator => xcb.xcb_pict_standard_t'Val (0));

   subtype xcb_pict_standard_t_Pointer is
     C_xcb_pict_standard_t_Pointers.Pointer;

   -- xcb_pict_standard_t_Pointer_Array
   --
   type xcb_pict_standard_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_pict_standard_t_Pointer;

   -- xcb_render_util_composite_text_stream_t_Pointer
   --
   package C_xcb_render_util_composite_text_stream_t_Pointers is new interfaces
     .c
     .Pointers
     (Index              => interfaces.c.size_t,
      Element            => xcb.xcb_render_util_composite_text_stream_t,
      element_Array      => xcb.xcb_render_util_composite_text_stream_t_Array,
      default_Terminator => 0);

   subtype xcb_render_util_composite_text_stream_t_Pointer is
     C_xcb_render_util_composite_text_stream_t_Pointers.Pointer;

   -- xcb_render_util_composite_text_stream_t_Pointer_Array
   --
   type xcb_render_util_composite_text_stream_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_render_util_composite_text_stream_t_Pointer;

   -- xcb_glx_pixmap_t_Pointer
   --
   package C_xcb_glx_pixmap_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_pixmap_t,
      Element_Array      => xcb.xcb_glx_pixmap_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_pixmap_t_Pointer is C_xcb_glx_pixmap_t_Pointers.Pointer;

   -- xcb_glx_pixmap_t_Pointer_Array
   --
   type xcb_glx_pixmap_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_pixmap_t_Pointer;

   -- xcb_glx_context_t_Pointer
   --
   package C_xcb_glx_context_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_context_t,
      Element_Array      => xcb.xcb_glx_context_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_context_t_Pointer is C_xcb_glx_context_t_Pointers.Pointer;

   -- xcb_glx_context_t_Pointer_Array
   --
   type xcb_glx_context_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_context_t_Pointer;

   -- xcb_glx_pbuffer_t_Pointer
   --
   package C_xcb_glx_pbuffer_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_pbuffer_t,
      Element_Array      => xcb.xcb_glx_pbuffer_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_pbuffer_t_Pointer is C_xcb_glx_pbuffer_t_Pointers.Pointer;

   -- xcb_glx_pbuffer_t_Pointer_Array
   --
   type xcb_glx_pbuffer_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_pbuffer_t_Pointer;

   -- xcb_glx_window_t_Pointer
   --
   package C_xcb_glx_window_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_window_t,
      Element_Array      => xcb.xcb_glx_window_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_window_t_Pointer is C_xcb_glx_window_t_Pointers.Pointer;

   -- xcb_glx_window_t_Pointer_Array
   --
   type xcb_glx_window_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_window_t_Pointer;

   -- xcb_glx_fbconfig_t_Pointer
   --
   package C_xcb_glx_fbconfig_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_fbconfig_t,
      Element_Array      => xcb.xcb_glx_fbconfig_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_fbconfig_t_Pointer is C_xcb_glx_fbconfig_t_Pointers.Pointer;

   -- xcb_glx_fbconfig_t_Pointer_Array
   --
   type xcb_glx_fbconfig_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_fbconfig_t_Pointer;

   -- xcb_glx_drawable_t_Pointer
   --
   package C_xcb_glx_drawable_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_drawable_t,
      Element_Array      => xcb.xcb_glx_drawable_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_drawable_t_Pointer is C_xcb_glx_drawable_t_Pointers.Pointer;

   -- xcb_glx_drawable_t_Pointer_Array
   --
   type xcb_glx_drawable_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_drawable_t_Pointer;

   -- xcb_glx_float32_t_Pointer
   --
   package C_xcb_glx_float32_t_Pointers is new interfaces.c.Pointers
     (Index              => interfaces.c.size_t,
      Element            => xcb.xcb_glx_float32_t,
      element_Array      => xcb.xcb_glx_float32_t_Array,
      default_Terminator => 0.0);

   subtype xcb_glx_float32_t_Pointer is C_xcb_glx_float32_t_Pointers.Pointer;

   -- xcb_glx_float32_t_Pointer_Array
   --
   type xcb_glx_float32_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_float32_t_Pointer;

   -- xcb_glx_float64_t_Pointer
   --
   package C_xcb_glx_float64_t_Pointers is new interfaces.c.Pointers
     (Index              => interfaces.c.size_t,
      Element            => xcb.xcb_glx_float64_t,
      element_Array      => xcb.xcb_glx_float64_t_Array,
      default_Terminator => 0.0);

   subtype xcb_glx_float64_t_Pointer is C_xcb_glx_float64_t_Pointers.Pointer;

   -- xcb_glx_float64_t_Pointer_Array
   --
   type xcb_glx_float64_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_float64_t_Pointer;

   -- xcb_glx_bool32_t_Pointer
   --
   package C_xcb_glx_bool32_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_bool32_t,
      Element_Array      => xcb.xcb_glx_bool32_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_bool32_t_Pointer is C_xcb_glx_bool32_t_Pointers.Pointer;

   -- xcb_glx_bool32_t_Pointer_Array
   --
   type xcb_glx_bool32_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_bool32_t_Pointer;

   -- xcb_glx_context_tag_t_Pointer
   --
   package C_xcb_glx_context_tag_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_context_tag_t,
      Element_Array      => xcb.xcb_glx_context_tag_t_array,
      Default_Terminator => 0);

   subtype xcb_glx_context_tag_t_Pointer is
     C_xcb_glx_context_tag_t_Pointers.Pointer;

   -- xcb_glx_context_tag_t_Pointer_Array
   --
   type xcb_glx_context_tag_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_context_tag_t_Pointer;

   -- xcb_glx_pbcet_t_Pointer
   --
   package C_xcb_glx_pbcet_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_pbcet_t,
      Element_Array      => xcb.xcb_glx_pbcet_t_array,
      Default_Terminator => xcb.xcb_glx_pbcet_t'Val (0));

   subtype xcb_glx_pbcet_t_Pointer is C_xcb_glx_pbcet_t_Pointers.Pointer;

   -- xcb_glx_pbcet_t_Pointer_Array
   --
   type xcb_glx_pbcet_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_pbcet_t_Pointer;

   -- xcb_glx_pbcdt_t_Pointer
   --
   package C_xcb_glx_pbcdt_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_pbcdt_t,
      Element_Array      => xcb.xcb_glx_pbcdt_t_array,
      Default_Terminator => xcb.xcb_glx_pbcdt_t'Val (0));

   subtype xcb_glx_pbcdt_t_Pointer is C_xcb_glx_pbcdt_t_Pointers.Pointer;

   -- xcb_glx_pbcdt_t_Pointer_Array
   --
   type xcb_glx_pbcdt_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_pbcdt_t_Pointer;

   -- xcb_glx_gc_t_Pointer
   --
   package C_xcb_glx_gc_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_gc_t,
      Element_Array      => xcb.xcb_glx_gc_t_array,
      Default_Terminator => xcb.xcb_glx_gc_t'Val (0));

   subtype xcb_glx_gc_t_Pointer is C_xcb_glx_gc_t_Pointers.Pointer;

   -- xcb_glx_gc_t_Pointer_Array
   --
   type xcb_glx_gc_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_gc_t_Pointer;

   -- xcb_glx_rm_t_Pointer
   --
   package C_xcb_glx_rm_t_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_rm_t,
      Element_Array      => xcb.xcb_glx_rm_t_array,
      Default_Terminator => xcb.xcb_glx_rm_t'Val (0));

   subtype xcb_glx_rm_t_Pointer is C_xcb_glx_rm_t_Pointers.Pointer;

   -- xcb_glx_rm_t_Pointer_Array
   --
   type xcb_glx_rm_t_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .xcb_glx_rm_t_Pointer;

   -- Display_Pointer
   --
   package C_Display_Pointers is new interfaces.c.Pointers
     (Index              => interfaces.c.size_t,
      Element            => xcb.Display,
      element_Array      => xcb.Display_Array,
      default_Terminator => 0);

   subtype Display_Pointer is C_Display_Pointers.Pointer;

   -- Display_Pointer_Array
   --
   type Display_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers.Display_Pointer;

   -- XEventQueueOwner_Pointer
   --
   package C_XEventQueueOwner_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.XEventQueueOwner,
      Element_Array      => xcb.XEventQueueOwner_array,
      Default_Terminator => xcb.XEventQueueOwner'Val (0));

   subtype XEventQueueOwner_Pointer is C_XEventQueueOwner_Pointers.Pointer;

   -- XEventQueueOwner_Pointer_Array
   --
   type XEventQueueOwner_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.Pointers
       .XEventQueueOwner_Pointer;

end xcb.Pointers;
