-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces;
with Interfaces.C;
with Interfaces.C.Pointers;

package xcb.xcb_screen_t is

   -- Item
   --

   type Item is record
      root                  : aliased xcb.xcb_window_t;
      default_colormap      : aliased xcb.xcb_colormap_t;
      white_pixel           : aliased Interfaces.Unsigned_32;
      black_pixel           : aliased Interfaces.Unsigned_32;
      current_input_masks   : aliased Interfaces.Unsigned_32;
      width_in_pixels       : aliased Interfaces.Unsigned_16;
      height_in_pixels      : aliased Interfaces.Unsigned_16;
      width_in_millimeters  : aliased Interfaces.Unsigned_16;
      height_in_millimeters : aliased Interfaces.Unsigned_16;
      min_installed_maps    : aliased Interfaces.Unsigned_16;
      max_installed_maps    : aliased Interfaces.Unsigned_16;
      root_visual           : aliased xcb.xcb_visualid_t;
      backing_stores        : aliased Interfaces.Unsigned_8;
      save_unders           : aliased Interfaces.Unsigned_8;
      root_depth            : aliased Interfaces.Unsigned_8;
      allowed_depths_len    : aliased Interfaces.Unsigned_8;
   end record;

   -- Item_Array
   --
   type Item_Array is
     array (Interfaces.C.size_t range <>) of aliased xcb.xcb_screen_t.Item;

   -- Pointer
   --
   package C_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_screen_t.Item,
      Element_Array      => xcb.xcb_screen_t.Item_Array,
      Default_Terminator => (others => <>));

   subtype Pointer is C_Pointers.Pointer;

   -- Pointer_Array
   --
   type Pointer_Array is
     array (Interfaces.C.size_t range <>) of aliased xcb.xcb_screen_t.Pointer;

   -- Pointer_Pointer
   --
   package C_Pointer_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_screen_t.Pointer,
      Element_Array      => xcb.xcb_screen_t.Pointer_Array,
      Default_Terminator => null);

   subtype Pointer_Pointer is C_Pointer_Pointers.Pointer;

end xcb.xcb_screen_t;
