-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces;
with Interfaces.C;
with Interfaces.C.Pointers;

package xcb.xcb_glx_read_pixels_request_t is

   -- Item
   --

   type Item is record
      major_opcode : aliased Interfaces.Unsigned_8;
      minor_opcode : aliased Interfaces.Unsigned_8;
      length       : aliased Interfaces.Unsigned_16;
      context_tag  : aliased xcb.xcb_glx_context_tag_t;
      x            : aliased Interfaces.Integer_32;
      y            : aliased Interfaces.Integer_32;
      width        : aliased Interfaces.Integer_32;
      height       : aliased Interfaces.Integer_32;
      format       : aliased Interfaces.Unsigned_32;
      the_type     : aliased Interfaces.Unsigned_32;
      swap_bytes   : aliased Interfaces.Unsigned_8;
      lsb_first    : aliased Interfaces.Unsigned_8;
   end record;

   -- Item_Array
   --
   type Item_Array is
     array
       (Interfaces.C
          .size_t range <>) of aliased xcb.xcb_glx_read_pixels_request_t
       .Item;

   -- Pointer
   --
   package C_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_read_pixels_request_t.Item,
      Element_Array      => xcb.xcb_glx_read_pixels_request_t.Item_Array,
      Default_Terminator => (others => <>));

   subtype Pointer is C_Pointers.Pointer;

   -- Pointer_Array
   --
   type Pointer_Array is
     array
       (Interfaces.C
          .size_t range <>) of aliased xcb.xcb_glx_read_pixels_request_t
       .Pointer;

   -- Pointer_Pointer
   --
   package C_Pointer_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_glx_read_pixels_request_t.Pointer,
      Element_Array      => xcb.xcb_glx_read_pixels_request_t.Pointer_Array,
      Default_Terminator => null);

   subtype Pointer_Pointer is C_Pointer_Pointers.Pointer;

end xcb.xcb_glx_read_pixels_request_t;
