-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces.C;
with Interfaces.C.Pointers;

package xcb.xcb_render_transform_t is

   -- Item
   --

   type Item is record
      matrix11 : aliased xcb.xcb_render_fixed_t;
      matrix12 : aliased xcb.xcb_render_fixed_t;
      matrix13 : aliased xcb.xcb_render_fixed_t;
      matrix21 : aliased xcb.xcb_render_fixed_t;
      matrix22 : aliased xcb.xcb_render_fixed_t;
      matrix23 : aliased xcb.xcb_render_fixed_t;
      matrix31 : aliased xcb.xcb_render_fixed_t;
      matrix32 : aliased xcb.xcb_render_fixed_t;
      matrix33 : aliased xcb.xcb_render_fixed_t;
   end record;

   -- Item_Array
   --
   type Item_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.xcb_render_transform_t
       .Item;

   -- Pointer
   --
   package C_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_transform_t.Item,
      Element_Array      => xcb.xcb_render_transform_t.Item_Array,
      Default_Terminator => (others => <>));

   subtype Pointer is C_Pointers.Pointer;

   -- Pointer_Array
   --
   type Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased xcb.xcb_render_transform_t
       .Pointer;

   -- Pointer_Pointer
   --
   package C_Pointer_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_render_transform_t.Pointer,
      Element_Array      => xcb.xcb_render_transform_t.Pointer_Array,
      Default_Terminator => null);

   subtype Pointer_Pointer is C_Pointer_Pointers.Pointer;

end xcb.xcb_render_transform_t;
