-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces;
with swig;
with Interfaces.C;
with Interfaces.C.Pointers;

package xcb.xcb_setup_t is

   -- Item
   --

   type Item is record
      status                      : aliased Interfaces.Unsigned_8;
      pad0                        : aliased Interfaces.Unsigned_8;
      protocol_major_version      : aliased Interfaces.Unsigned_16;
      protocol_minor_version      : aliased Interfaces.Unsigned_16;
      length                      : aliased Interfaces.Unsigned_16;
      release_number              : aliased Interfaces.Unsigned_32;
      resource_id_base            : aliased Interfaces.Unsigned_32;
      resource_id_mask            : aliased Interfaces.Unsigned_32;
      motion_buffer_size          : aliased Interfaces.Unsigned_32;
      vendor_len                  : aliased Interfaces.Unsigned_16;
      maximum_request_length      : aliased Interfaces.Unsigned_16;
      roots_len                   : aliased Interfaces.Unsigned_8;
      pixmap_formats_len          : aliased Interfaces.Unsigned_8;
      image_byte_order            : aliased Interfaces.Unsigned_8;
      bitmap_format_bit_order     : aliased Interfaces.Unsigned_8;
      bitmap_format_scanline_unit : aliased Interfaces.Unsigned_8;
      bitmap_format_scanline_pad  : aliased Interfaces.Unsigned_8;
      min_keycode                 : aliased xcb.xcb_keycode_t;
      max_keycode                 : aliased xcb.xcb_keycode_t;
      pad1                        : aliased swig.int8_t_Array (0 .. 3);
   end record;

   -- Item_Array
   --
   type Item_Array is
     array (Interfaces.C.size_t range <>) of aliased xcb.xcb_setup_t.Item;

   -- Pointer
   --
   package C_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_setup_t.Item,
      Element_Array      => xcb.xcb_setup_t.Item_Array,
      Default_Terminator => (others => <>));

   subtype Pointer is C_Pointers.Pointer;

   -- Pointer_Array
   --
   type Pointer_Array is
     array (Interfaces.C.size_t range <>) of aliased xcb.xcb_setup_t.Pointer;

   -- Pointer_Pointer
   --
   package C_Pointer_Pointers is new Interfaces.C.Pointers
     (Index              => Interfaces.C.size_t,
      Element            => xcb.xcb_setup_t.Pointer,
      Element_Array      => xcb.xcb_setup_t.Pointer_Array,
      Default_Terminator => null);

   subtype Pointer_Pointer is C_Pointer_Pointers.Pointer;

end xcb.xcb_setup_t;
