#!/bin/bash

echo
echo Removing prior build.
echo

rm *.ads
rm *.c


echo
echo Generating the binding.
echo

swig_ada  -ada  -I/usr/include  -I/usr/include/linux  -I/usr/lib/gcc/x86_64-linux-gnu/4.3/include   clib.i 


echo
echo Pretty printing.
echo

gnatpp  -rnb  -I/usr/local/include   *.ads
indent  -sob  -di16                  *.c


# Clean up.
#
rm *~


