/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
#if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#define SWIGTEMPLATEDISAMBIGUATOR template
#elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#define SWIGTEMPLATEDISAMBIGUATOR template
#else
#define SWIGTEMPLATEDISAMBIGUATOR
#endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#define SWIGINLINE inline
#else
#define SWIGINLINE
#endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
#if defined(__GNUC__)
#if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#define SWIGUNUSED __attribute__ ((__unused__))
#else
#define SWIGUNUSED
#endif
#elif defined(__ICC)
#define SWIGUNUSED __attribute__ ((__unused__))
#else
#define SWIGUNUSED
#endif
#endif

#ifndef SWIGUNUSEDPARM
#ifdef __cplusplus
#define SWIGUNUSEDPARM(p)
#else
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
#define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#ifndef GCC_HASCLASSVISIBILITY
#define GCC_HASCLASSVISIBILITY
#endif
#endif

#ifndef SWIGEXPORT
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#if defined(STATIC_LINKED)
#define SWIGEXPORT
#else
#define SWIGEXPORT __declspec(dllexport)
#endif
#else
#if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#define SWIGEXPORT __attribute__ ((visibility("default")))
#else
#define SWIGEXPORT
#endif
#endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#define SWIGSTDCALL __stdcall
#else
#define SWIGSTDCALL
#endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
#define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
#define _SCL_SECURE_NO_DEPRECATE
#endif

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#if defined(_WIN32) || defined(__CYGWIN32__)
#define DllExport   __declspec( dllexport )
#define SWIGSTDCALL __stdcall
#else
#define DllExport
#define SWIGSTDCALL
#endif

#ifdef __cplusplus
#include <new>
#endif

/* Support for throwing Ada exceptions from C/C++ */

typedef enum
{
  SWIG_AdaException,
  SWIG_AdaOutOfMemoryException,
  SWIG_AdaIndexOutOfRangeException,
  SWIG_AdaDivideByZeroException,
  SWIG_AdaArgumentOutOfRangeException,
  SWIG_AdaNullReferenceException
} SWIG_AdaExceptionCodes;

typedef void    (SWIGSTDCALL * SWIG_AdaExceptionCallback_t) (const char *);

typedef struct
{
  SWIG_AdaExceptionCodes code;
  SWIG_AdaExceptionCallback_t callback;
}
SWIG_AdaExceptions_t;

static          SWIG_AdaExceptions_t SWIG_ada_exceptions[] = {
  {SWIG_AdaException, NULL},
  {SWIG_AdaOutOfMemoryException, NULL},
  {SWIG_AdaIndexOutOfRangeException, NULL},
  {SWIG_AdaDivideByZeroException, NULL},
  {SWIG_AdaArgumentOutOfRangeException, NULL},
  {SWIG_AdaNullReferenceException, NULL}
};

static void
SWIG_AdaThrowException (SWIG_AdaExceptionCodes code, const char *msg)
{
  SWIG_AdaExceptionCallback_t callback =
    SWIG_ada_exceptions[SWIG_AdaException].callback;
  if (code >= 0
      && (size_t) code <
      sizeof (SWIG_ada_exceptions) / sizeof (SWIG_AdaExceptions_t))
    {
      callback = SWIG_ada_exceptions[code].callback;
    }
  callback (msg);
}

#ifdef __cplusplus
extern          "C"
#endif
                DllExport void SWIGSTDCALL
SWIGRegisterExceptionCallbacks_CORE_MODULE (SWIG_AdaExceptionCallback_t
					    systemException,
					    SWIG_AdaExceptionCallback_t
					    outOfMemory,
					    SWIG_AdaExceptionCallback_t
					    indexOutOfRange,
					    SWIG_AdaExceptionCallback_t
					    divideByZero,
					    SWIG_AdaExceptionCallback_t
					    argumentOutOfRange,
					    SWIG_AdaExceptionCallback_t
					    nullReference)
{
  SWIG_ada_exceptions[SWIG_AdaException].callback = systemException;
  SWIG_ada_exceptions[SWIG_AdaOutOfMemoryException].callback = outOfMemory;
  SWIG_ada_exceptions[SWIG_AdaIndexOutOfRangeException].callback =
    indexOutOfRange;
  SWIG_ada_exceptions[SWIG_AdaDivideByZeroException].callback = divideByZero;
  SWIG_ada_exceptions[SWIG_AdaArgumentOutOfRangeException].callback =
    argumentOutOfRange;
  SWIG_ada_exceptions[SWIG_AdaNullReferenceException].callback =
    nullReference;
}

/* Callback for returning strings to Ada without leaking memory */

typedef char   *(SWIGSTDCALL * SWIG_AdaStringHelperCallback) (const char *);
static SWIG_AdaStringHelperCallback SWIG_ada_string_callback = NULL;

/* probably obsolete ...
#ifdef __cplusplus
extern "C" 
#endif
DllExport void SWIGSTDCALL SWIGRegisterStringCallback_CORE_MODULE(SWIG_AdaStringHelperCallback callback) {
  SWIG_ada_string_callback = callback;
}
*/

/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_AdaThrowException(SWIG_AdaArgumentOutOfRangeException, msg); return nullreturn; } else

#define protected public
#define private   public

#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <locale.h>
#include <math.h>
#include <setjmp.h>
#include <time.h>

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

#include <string.h>

int
lc_CTYPE ()
{
  return LC_CTYPE;
};

int
lc_NUMERIC ()
{
  return LC_NUMERIC;
};

int
lc_TIME ()
{
  return LC_TIME;
};

int
lc_COLLATE ()
{
  return LC_COLLATE;
};

int
lc_MONETARY ()
{
  return LC_MONETARY;
};

int
lc_MESSAGES ()
{
  return LC_MESSAGES;
};

int
lc_ALL ()
{
  return LC_ALL;
};

int
lc_PAPER ()
{
  return LC_PAPER;
};

int
lc_NAME ()
{
  return LC_NAME;
};

int
lc_ADDRESS ()
{
  return LC_ADDRESS;
};

int
lc_TELEPHONE ()
{
  return LC_TELEPHONE;
};

int
lc_MEASUREMENT ()
{
  return LC_MEASUREMENT;
};

int
lc_IDENTIFICATION ()
{
  return LC_IDENTIFICATION;
};

#if defined (USE_32bit_time_t)
typedef int     time_t;
#endif

#if defined (USE_64bit_time_t)
typedef long    time_t;
#endif

#undef protected
#undef private
#ifdef __cplusplus
extern          "C"
{
#endif
  DllExport void SWIGSTDCALL Ada_delete_lconv (void *jarg1)
  {
    struct lconv   *arg1 = (struct lconv *) 0;

                    arg1 = (struct lconv *) jarg1;

                    free ((char *) arg1);

  }

  DllExport char *SWIGSTDCALL Ada_setlocale (int jarg1, char *jarg2)
  {
    char           *jresult;
    int             arg1;
    char           *arg2 = (char *) 0;
    char           *result = 0;

    arg1 = (int) jarg1;

    arg2 = jarg2;

    result = (char *) setlocale (arg1, (char const *) arg2);
    jresult = result;

    return jresult;

  }

  DllExport void *SWIGSTDCALL Ada_localeconv ()
  {
    void           *jresult;
    struct lconv   *result = 0;

    result = (struct lconv *) localeconv ();
    jresult = (void *) result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_CTYPE ()
  {
    int             jresult;
    int             result;

    result = (int) lc_CTYPE ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_NUMERIC ()
  {
    int             jresult;
    int             result;

    result = (int) lc_NUMERIC ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_TIME ()
  {
    int             jresult;
    int             result;

    result = (int) lc_TIME ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_COLLATE ()
  {
    int             jresult;
    int             result;

    result = (int) lc_COLLATE ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_MONETARY ()
  {
    int             jresult;
    int             result;

    result = (int) lc_MONETARY ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_MESSAGES ()
  {
    int             jresult;
    int             result;

    result = (int) lc_MESSAGES ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_ALL ()
  {
    int             jresult;
    int             result;

    result = (int) lc_ALL ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_PAPER ()
  {
    int             jresult;
    int             result;

    result = (int) lc_PAPER ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_NAME ()
  {
    int             jresult;
    int             result;

    result = (int) lc_NAME ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_ADDRESS ()
  {
    int             jresult;
    int             result;

    result = (int) lc_ADDRESS ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_TELEPHONE ()
  {
    int             jresult;
    int             result;

    result = (int) lc_TELEPHONE ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_MEASUREMENT ()
  {
    int             jresult;
    int             result;

    result = (int) lc_MEASUREMENT ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_lc_IDENTIFICATION ()
  {
    int             jresult;
    int             result;

    result = (int) lc_IDENTIFICATION ();
    jresult = result;

    return jresult;

  }

  DllExport void SWIGSTDCALL Ada_delete_timeval (void *jarg1)
  {
    struct timeval *arg1 = (struct timeval *) 0;

    arg1 = (struct timeval *) jarg1;

    free ((char *) arg1);

  }

#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
extern          "C"
{
#endif
#ifdef __cplusplus
}
#endif
