-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with clib.lconv;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package clib.Binding is

   function setlocale
     (a_a_category : in Interfaces.C.int;
      a_a_locale   : in Interfaces.C.Strings.chars_ptr)
      return Interfaces.C.Strings.chars_ptr;

   function localeconv return access clib.lconv.Item;

   function lc_CTYPE return Interfaces.C.int;

   function lc_NUMERIC return Interfaces.C.int;

   function lc_TIME return Interfaces.C.int;

   function lc_COLLATE return Interfaces.C.int;

   function lc_MONETARY return Interfaces.C.int;

   function lc_MESSAGES return Interfaces.C.int;

   function lc_ALL return Interfaces.C.int;

   function lc_PAPER return Interfaces.C.int;

   function lc_NAME return Interfaces.C.int;

   function lc_ADDRESS return Interfaces.C.int;

   function lc_TELEPHONE return Interfaces.C.int;

   function lc_MEASUREMENT return Interfaces.C.int;

   function lc_IDENTIFICATION return Interfaces.C.int;

private

   pragma Import (C, setlocale, "setlocale");
   pragma Import (C, localeconv, "localeconv");
   pragma Import (C, lc_CTYPE, "lc_CTYPE");
   pragma Import (C, lc_NUMERIC, "lc_NUMERIC");
   pragma Import (C, lc_TIME, "lc_TIME");
   pragma Import (C, lc_COLLATE, "lc_COLLATE");
   pragma Import (C, lc_MONETARY, "lc_MONETARY");
   pragma Import (C, lc_MESSAGES, "lc_MESSAGES");
   pragma Import (C, lc_ALL, "lc_ALL");
   pragma Import (C, lc_PAPER, "lc_PAPER");
   pragma Import (C, lc_NAME, "lc_NAME");
   pragma Import (C, lc_ADDRESS, "lc_ADDRESS");
   pragma Import (C, lc_TELEPHONE, "lc_TELEPHONE");
   pragma Import (C, lc_MEASUREMENT, "lc_MEASUREMENT");
   pragma Import (C, lc_IDENTIFICATION, "lc_IDENTIFICATION");

end clib.Binding;
