-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package clib.Pointers is

   -- time_t_Pointer
   --
   type time_t_Pointer is access all clib.time_t;

   -- time_t_Pointers
   --
   type time_t_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased clib.Pointers.time_t_Pointer;

   -- FILE_Pointer
   --
   type FILE_Pointer is access all clib.FILE;

   -- FILE_Pointers
   --
   type FILE_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased clib.Pointers.FILE_Pointer;

end clib.Pointers;
