-- This file is generated by SWIG. Please do *not* modify by hand.
--
with speech_tools_c;
with speech_tools_c.Pointers;
with interfaces.C;



package festival.FT_ff_pref_func is

   -- Item
   -- 
   type Item is access 

     function   (arg_2_1 : in speech_tools_c.Pointers.EST_Item_Pointer;
                 arg_2_2 : in speech_tools_c.Pointers.EST_String_Pointer) return speech_tools_c.EST_Val;
   pragma convention (C, Item);

   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased festival.FT_ff_pref_func.Item;



   -- Pointer
   -- 
   type Pointer is access all festival.FT_ff_pref_func.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased festival.FT_ff_pref_func.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all festival.FT_ff_pref_func.Pointer;










end festival.FT_ff_pref_func;
