-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.c;
with interfaces.c.strings;
with swig;
with interfaces.C;



package Festival is

   -- FILE
   -- 
   subtype FILE is swig.opaque_structure;

   type FILE_array is array (interfaces.C.Size_t range <>) of aliased festival.FILE;

   -- ostream
   -- 
   subtype ostream is swig.incomplete_class;

   type ostream_array is array (interfaces.C.Size_t range <>) of aliased festival.ostream;

   -- ModuleDescription
   -- 
   subtype ModuleDescription is swig.opaque_structure;

   type ModuleDescription_array is array (interfaces.C.Size_t range <>) of aliased festival.ModuleDescription;


   ft_server_socket      : aliased interfaces.c.int;
   festival_version      : aliased interfaces.c.strings.chars_ptr;
   FESTIVAL_DEFAULT_PORT : constant := 1314;
   FESTIVAL_HEAP_SIZE    : constant := 1000000;



private

   pragma import (CPP, ft_server_socket, "_ZN8festival16ft_server_socketE");
   pragma import (CPP, festival_version, "_ZN8festival16festival_versionE");

end Festival;
