-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.C;



package festival.Pointers is

   -- FILE_Pointer
   -- 
   type FILE_Pointer is access all festival.FILE;

   -- FILE_Pointers
   -- 
   type FILE_Pointers is array (interfaces.C.Size_t range <>) of aliased festival.Pointers.FILE_Pointer;



   -- ostream_Pointer
   -- 
   type ostream_Pointer is access all festival.ostream;

   -- ostream_Pointers
   -- 
   type ostream_Pointers is array (interfaces.C.Size_t range <>) of aliased festival.Pointers.ostream_Pointer;



   -- ModuleDescription_Pointer
   -- 
   type ModuleDescription_Pointer is access all festival.ModuleDescription;

   -- ModuleDescription_Pointers
   -- 
   type ModuleDescription_Pointers is array (interfaces.C.Size_t range <>) of aliased festival.Pointers.ModuleDescription_Pointer;


end festival.Pointers;
